Repository home-assistant/brands, pull requests merged in 2020-06, with the labels that each got.

#1674 Remove gearbest integration (ADR-0004)
  core_integrations/gearbest/icon.png
  core_integrations/gearbest/icon@2x.png
  core_integrations/gearbest/logo.png
  core_integrations/gearbest/logo@2x.png
Labels: has-parent

#1291 Add brand images for hvv_departures integration
  src/hvv_departures/icon.png
  src/hvv_departures/icon@2x.png
  src/hvv_departures/logo.png
  src/hvv_departures/logo@2x.png
Labels: awaits-parent, has-parent

#1709 Added floureon brand
  custom_integrations/floureon/logo.png
  custom_integrations/floureon/logo@2x.png
Labels: in-progress

#1715 Remove lockitron integration
  core_integrations/lockitron/icon.png
  core_integrations/lockitron/icon@2x.png
  core_integrations/lockitron/logo.png
  core_integrations/lockitron/logo@2x.png
Labels: cleanup, has-parent

#1673 Add icons for humidifier integration
  core_integrations/humidifier/icon.png
  core_integrations/humidifier/icon@2x.png
Labels: awaits-parent, has-parent

#1717 Remove fortigate integration
  core_integrations/fortigate/icon.png
  core_integrations/fortigate/icon@2x.png
Labels: cleanup

#1721 Add logo for pymusiccast
  custom_integrations/pymusiccast/icon.png
  custom_integrations/pymusiccast/icon@2x.png
  custom_integrations/pymusiccast/logo.png
  custom_integrations/pymusiccast/logo@2x.png
Labels: in-progress
