Repository home-assistant/brands, pull requests merged in 2020-10, with the labels that each got.

#1895 Add icons to fail2ban
  core_integrations/fail2ban/icon.png
  core_integrations/fail2ban/icon@2x.png
Labels: Hacktoberfest

#1898 Add brand images for geizhals
  core_integrations/geizhals/icon.png
  core_integrations/geizhals/icon@2x.png
  core_integrations/geizhals/logo.png
  core_integrations/geizhals/logo@2x.png
Labels: Hacktoberfest

#1903 Add icons for DSMR Reader
  core_integrations/dsmr_reader/icon.png
  core_integrations/dsmr_reader/icon@2x.png
Labels: Hacktoberfest

#1904 Create symlink for profiler
  core_integrations/profiler
Labels: has-parent

#1852 Add Ruckus Unleashed integration logos
  core_integrations/ruckus_unleashed/icon.png
  core_integrations/ruckus_unleashed/icon@2x.png
  core_integrations/ruckus_unleashed/logo.png
  core_integrations/ruckus_unleashed/logo@2x.png
Labels: awaits-parent, has-parent

#1868 add Tasmota
  core_integrations/tasmota/icon.png
  core_integrations/tasmota/icon@2x.png
  core_integrations/tasmota/logo.png
  core_integrations/tasmota/logo@2x.png
Labels: awaits-parent, has-parent

#1910 Submit logo for Securifi
  custom_integrations/securifi/icon.png
  custom_integrations/securifi/icon@2x.png
  custom_integrations/securifi/logo.png
  custom_integrations/securifi/logo@2x.png
Labels: in-progress

#1733 Gree integration logos
  core_integrations/gree/icon.png
  core_integrations/gree/icon@2x.png
  core_integrations/gree/logo.png
  core_integrations/gree/logo@2x.png
Labels: awaits-parent, has-parent

#1939 Remove BOM integration
  core_integrations/bom/icon.png
  core_integrations/bom/icon@2x.png
  core_integrations/bom/logo.png
  core_integrations/bom/logo@2x.png
Labels: cleanup, has-parent, parent-merged

#1960 Add husqvarna_automower
  custom_integrations/automower/icon.png
  custom_integrations/automower/icon@2x.png
  custom_integrations/automower/logo.png
  custom_integrations/automower/logo@2x.png
Labels: in-progress

#1968 Add additional policies to README.md (from #1938)
  README.md
Labels: in-progress

#1976 Samsung TV Tizen Integration Icon
  custom_integrations/samsungtv_tizen/icon.png
  custom_integrations/samsungtv_tizen/icon@2x.png
Labels: in-progress

#1977 Add brand for custom integration media_player.template
  custom_integrations/media_player_template/icon.png
  custom_integrations/media_player_template/icon@2x.png
Labels: in-progress
