Repository home-assistant/brands, pull requests merged in 2020-03, with the labels that each got.

#56 Adds icon & logo for pvpc_hourly_pricing integration
  src/pvpc_hourly_pricing/icon.png
  src/pvpc_hourly_pricing/icon@2x.png
  src/pvpc_hourly_pricing/logo.png
  src/pvpc_hourly_pricing/logo@2x.png
Labels: has-parent, parent-merged

#61 Change placeholder fallback logic
  README.md
  netlify.toml
  scripts/build.sh
Labels: enhancement, in-progress

#57 Add logos for Internet Printing Protocol
  src/ipp/icon.png
  src/ipp/icon@2x.png
Labels: has-parent
