Repository home-assistant/brands, pull requests merged in 2020-11, with the labels that each got.

#1997 Update HomeWizard Energy icons
  custom_integrations/homewizard_energy/icon.png
  custom_integrations/homewizard_energy/icon@2x.png
Labels: hacktoberfest-accepted

#1996 tryfi icon
  custom_integrations/tryfi/icon.png
Labels: hacktoberfest-accepted

#1995 Add bsblan icon and logo
  core_integrations/bsblan/icon.png
  core_integrations/bsblan/icon@2x.png
  core_integrations/bsblan/logo.png
  core_integrations/bsblan/logo@2x.png
Labels: hacktoberfest-accepted

#1992 Add logo and icon for xiaomi_miio_plug and xiaomi_miio_raw
  custom_integrations/xiaomi_miio_plug/icon.png
  custom_integrations/xiaomi_miio_plug/icon@2x.png
  custom_integrations/xiaomi_miio_plug/logo.png
  custom_integrations/xiaomi_miio_plug/logo@2x.png
  custom_integrations/xiaomi_miio_raw/icon.png
  custom_integrations/xiaomi_miio_raw/icon@2x.png
  custom_integrations/xiaomi_miio_raw/logo.png
  custom_integrations/xiaomi_miio_raw/logo@2x.png
Labels: hacktoberfest-accepted

#1989 Add brand images for pushsafer
  core_integrations/pushsafer/icon.png
  core_integrations/pushsafer/icon@2x.png
  core_integrations/pushsafer/logo.png
Labels: hacktoberfest-accepted

#1991 Update Fronius logo
  core_integrations/fronius/logo.png
Labels: hacktoberfest-accepted

#1990 Add (missing) brand images for Fronius
  core_integrations/fronius/icon.png
  core_integrations/fronius/icon@2x.png
  core_integrations/fronius/logo@2x.png
Labels: hacktoberfest-accepted

#1987 Add brand images for OhmConnect
  core_integrations/ohmconnect/icon.png
  core_integrations/ohmconnect/icon@2x.png
  core_integrations/ohmconnect/logo.png
  core_integrations/ohmconnect/logo@2x.png
Labels: hacktoberfest-accepted

#1983 Add brand images for custom component Bureau of Meteorology
  custom_integrations/bureau_of_meteorology/icon.png
  custom_integrations/bureau_of_meteorology/icon@2x.png
  custom_integrations/bureau_of_meteorology/logo.png
  custom_integrations/bureau_of_meteorology/logo@2x.png
Labels: hacktoberfest-accepted, in-progress

#1893 Add new srp_energy integration logos
  core_integrations/srp_energy/icon.png
  core_integrations/srp_energy/icon@2x.png
  core_integrations/srp_energy/logo.png
  core_integrations/srp_energy/logo@2x.png
Labels: awaits-parent, hacktoberfest-accepted, has-config-flow, has-parent

#2036 Remove salt logos
  core_integrations/salt/icon.png
  core_integrations/salt/icon@2x.png
  core_integrations/salt/logo.png
  core_integrations/salt/logo@2x.png
Labels: cleanup, has-parent

#2029 Add iAlarm integration icon
  custom_integrations/ialarm/icon.png
Labels: in-progress

#1954 Add assets for the Twinkly integration
  core_integrations/twinkly/icon.png
  core_integrations/twinkly/icon@2x.png
  core_integrations/twinkly/logo.png
  core_integrations/twinkly/logo@2x.png
Labels: awaits-parent, hacktoberfest-accepted, has-parent

#2013 Add Motion Blinds integration
  core_integrations/motion_blinds/icon.png
  core_integrations/motion_blinds/icon@2x.png
  core_integrations/motion_blinds/logo.png
  core_integrations/motion_blinds/logo@2x.png
Labels: awaits-parent, has-parent, parent-merged

#2045 added ytube_music_player
  custom_integrations/ytube_music_player/icon.png
  custom_integrations/ytube_music_player/icon@2x.png
  custom_integrations/ytube_music_player/logo.png
  custom_integrations/ytube_music_player/logo@2x.png
Labels: in-progress
