Repository home-assistant/brands, pull requests merged in 2020-05, with the labels that each got.

#1487 Add brand images for BleBox
  src/blebox/icon.png
  src/blebox/icon@2x.png
  src/blebox/logo.png
  src/blebox/logo@2x.png
Labels: awaits-parent, has-parent

#59 Add devolo_home_control product icon
  src/devolo_home_control/icon.png
  src/devolo_home_control/icon@2x.png
Labels: awaits-parent, has-parent

#1502 Universal Powerline Bus
  src/upb/icon.png
  src/upb/icon@2x.png
Labels: has-parent

#1516 Flick Electric
  src/flick_electric/icon.png
  src/flick_electric/icon@2x.png
Labels: awaits-parent, has-parent

#1589 Add zerproc icons
  core_integrations/zerproc/icon.png
  core_integrations/zerproc/icon@2x.png
  core_integrations/zerproc/logo.png
  core_integrations/zerproc/logo@2x.png
Labels: awaits-parent, has-parent

#1614 Rename zwave_mqtt to ozw
  core_integrations/ozw
Labels: has-parent

#1548 Add branding for Rollease Acmeda integration
  src/acmeda/icon.png
  src/acmeda/logo.png
Labels: awaits-parent, has-parent

#1638 Add Securitas logo
  custom_integrations/securitas/icon.png
  custom_integrations/securitas/icon@2x.png
  custom_integrations/securitas/logo.png
  custom_integrations/securitas/logo@2x.png
Labels: in-progress

#1657 Brands for new integration - circuit
  core_integrations/circuit/icon.png
  core_integrations/circuit/icon@2x.png
  core_integrations/circuit/logo.png
  core_integrations/circuit/logo@2x.png
Labels: has-parent

#1641 Remove WWLLN branding
  core_integrations/wwlln/logo.png
  core_integrations/wwlln/logo@2x.png
Labels: awaits-parent, has-parent

#1647 Added icon for vistapool custom integration
  custom_integrations/vistapool/icon.png
Labels: in-progress

#1489 Add images for Elexa Guardian
  src/guardian/icon.png
  src/guardian/logo.png
Labels: awaits-parent, has-parent
