Repository home-assistant/brands, pull requests merged in 2020-12, with the labels that each got.

#2060 Remove Ubee Router integration (ADR-0004)
  core_integrations/ubee/icon.png
  core_integrations/ubee/icon@2x.png
  core_integrations/ubee/logo.png
  core_integrations/ubee/logo@2x.png
Labels: cleanup, has-parent

#1999 Add logo for Number integration
  core_integrations/number
Labels: awaits-parent, has-parent

#1973 Add brand images for Kuler Sky integration
  core_integrations/kulersky/icon.png
  core_integrations/kulersky/icon@2x.png
  core_integrations/kulersky/logo.png
  core_integrations/kulersky/logo@2x.png
Labels: awaits-parent, hacktoberfest-accepted, has-parent

#2064 Add N2YO Satellitetracker Icon
  custom_integrations/satellitetracker/icon.png
Labels: in-progress

#2074 Added Winix
  custom_integrations/winix/icon.png
  custom_integrations/winix/icon@2x.png
  custom_integrations/winix/logo.png
  custom_integrations/winix/logo@2x.png
Labels: in-progress

#2113 Cleanup removed avri integration brand images
  core_integrations/avri/icon.png
  core_integrations/avri/icon@2x.png
Labels: cleanup

#1859 Added AirNow Logo and Icon
  core_integrations/airnow/icon.png
  core_integrations/airnow/icon@2x.png
  core_integrations/airnow/logo.png
  core_integrations/airnow/logo@2x.png
Labels: awaits-parent, has-parent
