Repository home-assistant/brands, pull requests merged in 2020-04, with the labels that each got.

#961 Add yandextts icon
  src/yandextts/icon.png
  src/yandextts/icon@2x.png
  src/yandextts/logo.png
  src/yandextts/logo@2x.png
Labels: in-progress

#1058 Added icons for aftership.
  src/aftership/icon.png
  src/aftership/icon@2x.png
  src/aftership/logo.png
  src/aftership/logo@2x.png
Labels: in-progress

#876 Add config flow to Synology DSM
  src/synology_dsm
Labels: has-parent

#1237 Add icons and logos for NSW Fuel StationPrice
  src/nsw_fuel_station/icon.png
  src/nsw_fuel_station/logo.png
Labels: in-progress

#1469 Remove Yahoo Weather integration
  src/yweather/icon.png
  src/yweather/icon@2x.png
Labels: has-parent

#1478 Added Proliphix Brand images
  src/proliphix/icon.png
  src/proliphix/logo.png
Labels: in-progress

#1480 Atag
  src/atag/icon.png
  src/atag/icon@2x.png
  src/atag/logo.png
  src/atag/logo@2x.png
Labels: awaits-parent, has-parent

#1119 Add logo for numato integration
  src/numato/icon.png
  src/numato/icon@2x.png
  src/numato/logo.png
  src/numato/logo@2x.png
Labels: awaits-parent, has-parent
