Repository home-assistant/brands, pull requests merged in 2020-08, with the labels that each got.

#1738 Add Control4 images
  core_integrations/control4/icon.png
  core_integrations/control4/icon@2x.png
  core_integrations/control4/logo.png
  core_integrations/control4/logo@2x.png
Labels: awaits-parent, has-parent

#1723 Add AccuWeather brand images
  core_integrations/accuweather/icon.png
  core_integrations/accuweather/icon@2x.png
  core_integrations/accuweather/logo.png
  core_integrations/accuweather/logo@2x.png
Labels: awaits-parent, has-parent

#1771 Add Lyric Icons from to custom_integration
  custom_integrations/lyric/icon.png
  custom_integrations/lyric/icon@2x.png
  custom_integrations/lyric/logo.png
  custom_integrations/lyric/logo@2x.png
Labels: in-progress

#1655 Add OVO Energy Brand
  core_integrations/ovo_energy/icon.png
  core_integrations/ovo_energy/icon@2x.png
  core_integrations/ovo_energy/logo.png
  core_integrations/ovo_energy/logo@2x.png
Labels: awaits-parent, has-parent

#1784 Add icons for SoX custom integration
  custom_integrations/sox/icon.png
Labels: in-progress

#1789 Remove prezzi benzina icons
  core_integrations/prezzibenzina/icon.png
  core_integrations/prezzibenzina/icon@2x.png
Labels: awaits-parent, has-parent

#1779 Add support for core integration Nightscout
  core_integrations/nightscout/icon.png
  core_integrations/nightscout/icon@2x.png
  core_integrations/nightscout/logo.png
  core_integrations/nightscout/logo@2x.png
Labels: has-parent, parent-merged

#1793 Add Flo icons
  core_integrations/flo/icon.png
  core_integrations/flo/icon@2x.png
Labels: has-parent

#1769 Add Roon icons and logos.
  core_integrations/roon/icon.png
  core_integrations/roon/icon@2x.png
  core_integrations/roon/logo.png
  core_integrations/roon/logo@2x.png
Labels: awaits-parent, has-parent

#1795 Add scheduler component
  custom_integrations/scheduler/icon.png
  custom_integrations/scheduler/icon@2x.png
Labels: in-progress

#1782 Added logos for Midea Inventor dehumidifier integration.
  custom_integrations/midea_dehumidifier/icon.png
  custom_integrations/midea_dehumidifier/logo.png
  custom_integrations/midea_dehumidifier/logo@2x.png
Labels: in-progress

#1745 Move Shelly from custom to core
  core_integrations/shelly_mqtt/icon.png
  core_integrations/shelly_mqtt/icon@2x.png
  core_integrations/shelly_mqtt/logo.png
  core_integrations/shelly_mqtt/logo@2x.png
Labels: awaits-parent, has-parent

#1642 Icons for wilight integration - core PR #35867, home-assistant.io PR #13546
  core_integrations/wilight/icon.png
  core_integrations/wilight/icon@2x.png
Labels: awaits-parent, has-parent, parent-merged

#1810 Remove Yr sensor
  core_integrations/yr/icon.png
  core_integrations/yr/icon@2x.png
Labels: has-parent

#1807 Add Smart Meter Texas logo
  core_integrations/smart_meter_texas/icon.png
  core_integrations/smart_meter_texas/icon@2x.png
  core_integrations/smart_meter_texas/logo.png
  core_integrations/smart_meter_texas/logo@2x.png
Labels: in-progress

#1754 Added logos for ProgettiHWSW inteegration.
  core_integrations/progettihwsw/icon.png
  core_integrations/progettihwsw/icon@2x.png
  core_integrations/progettihwsw/logo.png
  core_integrations/progettihwsw/logo@2x.png
Labels: awaits-parent, has-parent, parent-merged

#1762 Move sharkiq files to core integrations
  core_integrations/sharkiq/icon.png
  core_integrations/sharkiq/icon@2x.png
  core_integrations/sharkiq/logo.png
  core_integrations/sharkiq/logo@2x.png
Labels: awaits-parent, has-parent
