Repository home-assistant/brands, pull requests merged in 2021-05, with the labels that each got.

#2532 Add EcoDevices RT2 (GCE) images
  custom_integrations/ecodevices_rt2/icon.png
  custom_integrations/ecodevices_rt2/logo.png
Labels: cla-signed

#2533 Add Lobe brands
  custom_integrations/lobe/icon.png
  custom_integrations/lobe/icon@2x.png
  custom_integrations/lobe/logo.png
  custom_integrations/lobe/logo@2x.png
Labels: cla-signed

#2534 Make nello images sharper
  core_integrations/nello/icon.png
  core_integrations/nello/icon@2x.png
  core_integrations/nello/logo.png
  core_integrations/nello/logo@2x.png
Labels: cla-signed

#2536 Create domains.json
  netlify.toml
  scripts/build.sh
Labels: cla-signed

#2537 Make ness_alarm images transparent
  core_integrations/ness_alarm/icon.png
  core_integrations/ness_alarm/icon@2x.png
  core_integrations/ness_alarm/logo.png
  core_integrations/ness_alarm/logo@2x.png
Labels: cla-signed

#2503 Make keyboard_remote icon sharper
  core_integrations/keyboard_remote/icon.png
  core_integrations/keyboard_remote/icon@2x.png
Labels: cla-signed

#2539 Link compensation to Home Assistant assets
  core_integrations/compensation
Labels: cla-signed

#2540 Add logos for Kostal Plenticore
  core_integrations/kostal_plenticore/logo.png
  core_integrations/kostal_plenticore/logo@2x.png
Labels: cla-signed

#2351 Add icon and logo for System Bridge
  core_integrations/system_bridge/icon.png
  core_integrations/system_bridge/icon@2x.png
  core_integrations/system_bridge/logo.png
  core_integrations/system_bridge/logo@2x.png
Labels: cla-signed, has-parent

#2542 Split core/custom domains
  scripts/build.sh
Labels: cla-signed

#2556 Remove N26 branding
  core_integrations/n26/icon.png
  core_integrations/n26/icon@2x.png
  core_integrations/n26/logo.png
  core_integrations/n26/logo@2x.png
Labels: cla-signed

#1774 Add syncthing icons and logos
  core_integrations/syncthing/icon.png
  core_integrations/syncthing/icon@2x.png
  core_integrations/syncthing/logo.png
  core_integrations/syncthing/logo@2x.png
Labels: awaits-parent, has-parent

#2558 Add Nuvo brand for custom integration
  custom_integrations/nuvo_serial/icon.png
  custom_integrations/nuvo_serial/icon@2x.png
  custom_integrations/nuvo_serial/logo.png
  custom_integrations/nuvo_serial/logo@2x.png
Labels: cla-signed

#2550 Improve nsw fuel station images
  core_integrations/nsw_fuel_station/icon.png
  core_integrations/nsw_fuel_station/icon@2x.png
  core_integrations/nsw_fuel_station/logo.png
  core_integrations/nsw_fuel_station/logo@2x.png
Labels: cla-signed

#2551 Add technicolor
  custom_integrations/technicolor/logo.png
  custom_integrations/technicolor/logo@2x.png
Labels: cla-signed, in-progress

#2548 Update aqualogic images
  core_integrations/aqualogic/icon.png
  core_integrations/aqualogic/icon@2x.png
  core_integrations/aqualogic/logo.png
  core_integrations/aqualogic/logo@2x.png
Labels: cla-signed, in-progress

#2549 Add icon for Panasonic Smart App
  custom_integrations/panasonic_smart_app/icon.png
  custom_integrations/panasonic_smart_app/icon@2x.png
  custom_integrations/panasonic_smart_app/logo.png
  custom_integrations/panasonic_smart_app/logo@2x.png
Labels: cla-signed, in-progress

#2552 Add RedPocket Mobile logos
  custom_integrations/redpocket/icon.png
  custom_integrations/redpocket/icon@2x.png
  custom_integrations/redpocket/logo.png
  custom_integrations/redpocket/logo@2x.png
Labels: cla-signed

#2554 Add xiaomi_miio_cooker
  custom_integrations/xiaomi_miio_cooker/icon.png
  custom_integrations/xiaomi_miio_cooker/icon@2x.png
  custom_integrations/xiaomi_miio_cooker/logo.png
  custom_integrations/xiaomi_miio_cooker/logo@2x.png
Labels: cla-signed

#2557 Improve nsw_rural_fire images
  core_integrations/nsw_rural_fire_service_feed/icon.png
  core_integrations/nsw_rural_fire_service_feed/icon@2x.png
  core_integrations/nsw_rural_fire_service_feed/logo.png
  core_integrations/nsw_rural_fire_service_feed/logo@2x.png
Labels: cla-signed

#2547 Add logos for wyzeapi
  custom_integrations/wyzeapi/icon.png
  custom_integrations/wyzeapi/icon@2x.png
  custom_integrations/wyzeapi/logo.png
  custom_integrations/wyzeapi/logo@2x.png
Labels: cla-signed, in-progress

#2553 Add xiaomi_miio_fan
  custom_integrations/xiaomi_miio_fan/icon.png
  custom_integrations/xiaomi_miio_fan/icon@2x.png
  custom_integrations/xiaomi_miio_fan/logo.png
  custom_integrations/xiaomi_miio_fan/logo@2x.png
Labels: cla-signed

#2546 Add nextbus images
  core_integrations/nextbus/icon.png
  core_integrations/nextbus/icon@2x.png
  core_integrations/nextbus/logo.png
  core_integrations/nextbus/logo@2x.png
Labels: cla-signed

#2545 Add: jellyfin
  custom_integrations/jellyfin/icon.png
  custom_integrations/jellyfin/icon@2x.png
  custom_integrations/jellyfin/logo.png
  custom_integrations/jellyfin/logo@2x.png
Labels: cla-signed

#2560 Remove defunct Spot Crime integration
  core_integrations/spotcrime/icon.png
  core_integrations/spotcrime/icon@2x.png
  core_integrations/spotcrime/logo.png
  core_integrations/spotcrime/logo@2x.png
Labels: cla-signed, cleanup, has-parent

#2566 add surepetcarebeta
  custom_integrations/surepetcarebeta/icon.png
  custom_integrations/surepetcarebeta/icon@2x.png
  custom_integrations/surepetcarebeta/logo.png
  custom_integrations/surepetcarebeta/logo@2x.png
Labels: cla-signed, in-progress

#2568 Add hDPI nuimo_controller logo
  core_integrations/nuimo_controller/icon.png
  core_integrations/nuimo_controller/icon@2x.png
  core_integrations/nuimo_controller/logo.png
  core_integrations/nuimo_controller/logo@2x.png
Labels: cla-signed

#2567 Add LINE logos
  custom_integrations/line_bot/icon.png
  custom_integrations/line_bot/icon@2x.png
  custom_integrations/line_bot/logo.png
  custom_integrations/line_bot/logo@2x.png
Labels: cla-signed

#2571 Add yi_hack brands
  custom_integrations/yi_hack/icon.png
  custom_integrations/yi_hack/icon@2x.png
Labels: cla-signed

#2570 Add OpenCWB (Opendat CWB)
  custom_integrations/opencwb/icon.png
  custom_integrations/opencwb/icon@2x.png
Labels: cla-error

#2573 Don't limit to directory to allow symlink
  scripts/build.sh
Labels: cla-signed

#2577 Added logo for Heatmiser Wifi
  custom_integrations/heatmiser_wifi/icon.png
  custom_integrations/heatmiser_wifi/icon@2x.png
  custom_integrations/heatmiser_wifi/logo.png
  custom_integrations/heatmiser_wifi/logo@2x.png
Labels: cla-signed

#2576 Icon for emulated_color_temp
  custom_integrations/emulated_color_temp/icon.png
Labels: cla-signed

#2574 Add brands for StartTime integration
  custom_integrations/start_time/icon.png
  custom_integrations/start_time/icon@2x.png
Labels: cla-signed

#2575 Add icon and logo for presence simulation integration
  custom_integrations/presence_simulation/icon.png
  custom_integrations/presence_simulation/icon@2x.png
Labels: cla-signed, in-progress

#1164 Added icons and logos for Bosch SHC integration.
  core_integrations/bosch_shc/icon.png
  core_integrations/bosch_shc/icon@2x.png
  core_integrations/bosch_shc/logo.png
  core_integrations/bosch_shc/logo@2x.png
Labels: awaits-parent, has-parent

#2579 Add brands for MorphNumbers integration
  custom_integrations/morph_numbers/icon.png
  custom_integrations/morph_numbers/icon@2x.png
Labels: cla-signed

#2572 Add icon/logo for kraken
  core_integrations/kraken/icon.png
  core_integrations/kraken/icon@2x.png
  core_integrations/kraken/logo.png
  core_integrations/kraken/logo@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2012 Adding icons for Garages Amsterdam integration
  core_integrations/garages_amsterdam/icon.png
  core_integrations/garages_amsterdam/icon@2x.png
Labels: awaits-parent, has-parent

#2584 Fix duplicate bosch_shc domain
  custom_integrations/bosch_shc/icon.png
  custom_integrations/bosch_shc/icon@2x.png
  custom_integrations/bosch_shc/logo.png
  custom_integrations/bosch_shc/logo@2x.png
Labels: cla-signed

#2580 Make niko icon transparent
  core_integrations/niko_home_control/icon.png
  core_integrations/niko_home_control/icon@2x.png
Labels: cla-signed, in-progress

#2569 Add Vimar platform
  custom_integrations/vimar/icon.png
  custom_integrations/vimar/icon@2x.png
  custom_integrations/vimar/logo.png
  custom_integrations/vimar/logo@2x.png
Labels: cla-signed, in-progress

#2586 Make noip images transparent
  core_integrations/noip/icon.png
  core_integrations/noip/icon@2x.png
  core_integrations/noip/logo.png
  core_integrations/noip/logo@2x.png
Labels: cla-signed

#2587 Upload mdadm_state icons
  custom_integrations/mdadm_state/icon.png
  custom_integrations/mdadm_state/icon@2x.png
Labels: cla-signed, in-progress

#2588 Add hDPI oasa_telematics icon
  core_integrations/oasa_telematics/icon.png
  core_integrations/oasa_telematics/icon@2x.png
Labels: cla-signed

#2589 Update the Hyperion icon & logo
  core_integrations/hyperion/icon.png
  core_integrations/hyperion/icon@2x.png
  core_integrations/hyperion/logo.png
Labels: cla-signed

#2582 Add brand images for CryptoState
  custom_integrations/cryptostate/icon.png
  custom_integrations/cryptostate/icon@2x.png
  custom_integrations/cryptostate/logo.png
  custom_integrations/cryptostate/logo@2x.png
Labels: cla-signed, in-progress

#2592 Compressed and added warzone custom integration images
  custom_integrations/warzone/icon.png
  custom_integrations/warzone/icon@2x.png
  custom_integrations/warzone/logo.png
  custom_integrations/warzone/logo@2x.png
Labels: cla-signed

#2353 Add icons for wallbox integration
  core_integrations/wallbox/icon.png
  core_integrations/wallbox/icon@2x.png
  core_integrations/wallbox/logo.png
  core_integrations/wallbox/logo@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2593 add myjdownloader icons (custom component)
  custom_integrations/myjdownloader/icon.png
  custom_integrations/myjdownloader/icon@2x.png
Labels: cla-signed

#2601 Adding logos for Nos news
  custom_integrations/nosnews/icon.png
  custom_integrations/nosnews/icon@2x.png
Labels: cla-signed

#2599 Automate Blinds Hub Icon
  custom_integrations/automate/icon.png
  custom_integrations/automate/logo.png
  custom_integrations/automate/logo@2x.png
Labels: cla-signed

#2595 Add DroneMobile Images
  custom_integrations/drone_mobile/icon.png
  custom_integrations/drone_mobile/icon@2x.png
  custom_integrations/drone_mobile/logo.png
  custom_integrations/drone_mobile/logo@2x.png
Labels: cla-signed

#2604 Updating DroneMobile Images
  custom_integrations/drone_mobile/icon.png
  custom_integrations/drone_mobile/icon@2x.png
  custom_integrations/drone_mobile/logo.png
  custom_integrations/drone_mobile/logo@2x.png
Labels: cla-signed

#2578 Ambihue
  custom_integrations/philips_ambilight+hue/icon.png
  custom_integrations/philips_ambilight+hue/icon@2x.png
  custom_integrations/philips_ambilight+hue/logo.png
  custom_integrations/philips_ambilight+hue/logo@2x.png
Labels: cla-signed, in-progress

#2606 Add brand images for Dahua custom integration
  custom_integrations/dahua/icon.png
  custom_integrations/dahua/icon@2x.png
  custom_integrations/dahua/logo.png
  custom_integrations/dahua/logo@2x.png
Labels: cla-signed

#2610 Add Multizone Controller Images
  custom_integrations/multizone_controller/icon.png
  custom_integrations/multizone_controller/icon@2x.png
  custom_integrations/multizone_controller/logo.png
  custom_integrations/multizone_controller/logo@2x.png
Labels: cla-signed

#2612 Move sia logo's to core_integrations
  core_integrations/sia/icon.png
  core_integrations/sia/icon@2x.png
  core_integrations/sia/logo.png
  core_integrations/sia/logo@2x.png
Labels: cla-signed

#2609 Added new images for integration [jadson179/consul]
  custom_integrations/consul/icon.png
  custom_integrations/consul/logo.png
Labels: cla-signed
