Repository home-assistant/brands, pull requests merged in 2021-06, with the labels that each got.

#2613 Added brandriskute
  custom_integrations/brandriskute/icon.png
  custom_integrations/brandriskute/icon@2x.png
Labels: cla-signed

#2614 Link network to Home Assistant assets
  core_integrations/network
Labels: cla-signed

#2615 Added sunspec brand images
  custom_integrations/sunspec/icon.png
  custom_integrations/sunspec/icon@2x.png
  custom_integrations/sunspec/logo.png
  custom_integrations/sunspec/logo@2x.png
Labels: cla-signed

#2621 Add hue_power icons
  custom_integrations/hue_power/icon.png
  custom_integrations/hue_power/icon@2x.png
  custom_integrations/hue_power/logo.png
  custom_integrations/hue_power/logo@2x.png
Labels: cla-signed

#2620 added Helium logos
  custom_integrations/helium/icon.png
  custom_integrations/helium/icon@2x.png
  custom_integrations/helium/logo.png
  custom_integrations/helium/logo@2x.png
Labels: cla-signed

#2627 Add Ambee brand
  core_integrations/ambee/icon.png
  core_integrations/ambee/icon@2x.png
  core_integrations/ambee/logo.png
  core_integrations/ambee/logo@2x.png
Labels: cla-signed, has-parent, parent-merged

#2631 rename noip to no_ip
  core_integrations/no_ip/icon.png
  core_integrations/no_ip/icon@2x.png
  core_integrations/no_ip/logo.png
  core_integrations/no_ip/logo@2x.png
Labels: cla-signed

#2611 Create icon.png
  custom_integrations/met_alerts_hu/icon.png
Labels: cla-signed, in-progress

#2628 ABB Power-One logos/icons for a custom component
  custom_integrations/abb_powerone_pvi_sunspec/icon.png
  custom_integrations/abb_powerone_pvi_sunspec/icon@2x.png
  custom_integrations/abb_powerone_pvi_sunspec/logo.png
  custom_integrations/abb_powerone_pvi_sunspec/logo@2x.png
Labels: cla-signed

#2625 Powercalc icons
  custom_integrations/hue_power/icon.png
  custom_integrations/hue_power/icon@2x.png
  custom_integrations/hue_power/logo.png
  custom_integrations/hue_power/logo@2x.png
  custom_integrations/powercalc/icon.png
  custom_integrations/powercalc/icon@2x.png
Labels: cla-signed

#2626 Adding modern_forms band
  core_integrations/modern_forms/icon.png
  core_integrations/modern_forms/icon@2x.png
  core_integrations/modern_forms/logo.png
  core_integrations/modern_forms/logo@2x.png
Labels: cla-signed, has-parent, parent-merged

#2632 Added icons for new AIMP custom integration
  custom_integrations/aimp/icon.png
  custom_integrations/aimp/icon@2x.png
Labels: cla-signed

#2622 Add images for custom integration dwd
  custom_integrations/dwd/icon.png
  custom_integrations/dwd/logo.png
Labels: cla-signed

#2633 Add variable_history icons
  custom_integrations/variable_history/icon.png
  custom_integrations/variable_history/icon@2x.png
Labels: cla-signed

#2635 Change directory name to match domain
  custom_integrations/variable/icon.png
  custom_integrations/variable/icon@2x.png
Labels: cla-signed

#2638 Update WLED logo
  core_integrations/wled/logo.png
  core_integrations/wled/logo@2x.png
Labels: cla-signed

#2639 Add the stihl_imow brand logo
  custom_integrations/stihl_imow/icon.png
  custom_integrations/stihl_imow/icon@2x.png
  custom_integrations/stihl_imow/logo.png
  custom_integrations/stihl_imow/logo@2x.png
Labels: cla-signed

#2616 Add Came logo and icon
  custom_integrations/came/icon.png
  custom_integrations/came/icon@2x.png
Labels: cla-signed, in-progress

#2649 Added new integration [alryaz/hass-yandex-music-browser]
  custom_integrations/yandex_music_browser/icon.png
  custom_integrations/yandex_music_browser/icon@2x.png
  custom_integrations/yandex_music_browser/logo.png
  custom_integrations/yandex_music_browser/logo@2x.png
Labels: cla-signed

#2641 Adds new integration [alryaz/hass-lkcomu-interrao]
  custom_integrations/lkcomu_interrao/icon.png
  custom_integrations/lkcomu_interrao/icon@2x.png
  custom_integrations/lkcomu_interrao/logo.png
  custom_integrations/lkcomu_interrao/logo@2x.png
Labels: cla-signed

#2648 Added iparcelbox brand icon and logo
  custom_integrations/iparcelbox/icon.png
  custom_integrations/iparcelbox/icon@2x.png
  custom_integrations/iparcelbox/logo.png
  custom_integrations/iparcelbox/logo@2x.png
Labels: cla-signed

#2646 Add niu custom integration
  custom_integrations/niu/icon.png
  custom_integrations/niu/icon@2x.png
  custom_integrations/niu/logo.png
  custom_integrations/niu/logo@2x.png
Labels: cla-signed

#2640 Add weight_gurus
  custom_integrations/weight_gurus/icon.png
  custom_integrations/weight_gurus/icon@2x.png
Labels: cla-signed

#2637 Adding PirateWeather Custom Brand
  custom_integrations/pirateweather/icon.png
  custom_integrations/pirateweather/icon@2x.png
  custom_integrations/pirateweather/logo.png
  custom_integrations/pirateweather/logo@2x.png
Labels: cla-error, cla-signed, in-progress

#2645 Add Signalmessenger integration
  custom_integrations/signalmessenger/icon.png
  custom_integrations/signalmessenger/icon@2x.png
Labels: cla-signed, in-progress

#2655 Add brand images for Forecast.Solar
  core_integrations/forecast_solar/icon.png
  core_integrations/forecast_solar/icon@2x.png
Labels: cla-signed, has-parent

#2656 Add Thermal Vision integration
  custom_integrations/thermal_vision/icon.png
  custom_integrations/thermal_vision/icon@2x.png
Labels: cla-signed

#2597 Make octoprint images transparent
  core_integrations/octoprint/icon.png
  core_integrations/octoprint/icon@2x.png
  core_integrations/octoprint/logo.png
  core_integrations/octoprint/logo@2x.png
Labels: cla-signed

#2654 Add icons for climate_ewelink
  custom_integrations/climate_ewelink/icon.png
  custom_integrations/climate_ewelink/icon@2x.png
  custom_integrations/climate_ewelink/logo.png
  custom_integrations/climate_ewelink/logo@2x.png
Labels: cla-signed

#2643 Add Falcon Pi Player Custom Integration
  custom_integrations/falcon_pi_player/icon.png
  custom_integrations/falcon_pi_player/logo.png
Labels: cla-signed

#2647 Added MOOX Track custom integration.
  custom_integrations/moox_track/icon.png
  custom_integrations/moox_track/icon@2x.png
Labels: cla-signed

#2658 Bootstrap icons
  custom_integrations/bootstrap-icons/icon.png
  custom_integrations/bootstrap-icons/icon@2x.png
Labels: cla-signed

#2660 Add new FordPass China Integrations
  custom_integrations/fordpass_china/icon.png
  custom_integrations/fordpass_china/icon@2x.png
  custom_integrations/fordpass_china/logo.png
  custom_integrations/fordpass_china/logo@2x.png
Labels: cla-signed

#2636 Add select integration
  core_integrations/select/icon.png
  core_integrations/select/icon@2x.png
Labels: cla-signed, has-parent, parent-merged

#2661 Add icon for KNMI
  custom_integrations/knmi/icon.png
  custom_integrations/knmi/icon@2x.png
Labels: cla-signed

#2253 Add brand images for Freedompro
  core_integrations/freedompro/icon.png
  core_integrations/freedompro/icon@2x.png
  core_integrations/freedompro/logo.png
  core_integrations/freedompro/logo@2x.png
Labels: awaits-parent, cla-signed, has-parent
