Repository home-assistant/brands, pull requests merged in 2021-02, with the labels that each got.

#2226 Add logo for Hilo custom integration
  custom_integrations/hilo/icon.png
Labels: cla-signed

#2224 Add mbapi2020 logo
  custom_integrations/mbapi2020/icon.png
Labels: cla-signed

#2225 Add icons for the custom integration Plex Assistant
  custom_integrations/plex_assistant/icon.png
  custom_integrations/plex_assistant/icon@2x.png
Labels: cla-signed

#2221 Add icons for mazda integration
  core_integrations/mazda/icon.png
  core_integrations/mazda/icon@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2232 Add TDAmeritrade
  custom_integrations/tdameritrade/icon.png
  custom_integrations/tdameritrade/icon@2x.png
  custom_integrations/tdameritrade/logo.png
  custom_integrations/tdameritrade/logo@2x.png
Labels: cla-signed

#2199 Images for upcoming Yale Doorman integration.
  custom_integrations/yale_doorman_via_smarthub/icon.png
  custom_integrations/yale_doorman_via_smarthub/icon@2x.png
Labels: cla-error, in-progress

#2231 Added icon and logo for n3rgy custom integration.
  custom_integrations/n3rgy/icon.png
  custom_integrations/n3rgy/logo.png
Labels: cla-signed, in-progress

#2230 Add icon for custom integration 'meteoalarmeu'
  custom_integrations/meteoalarmeu/icon.png
  custom_integrations/meteoalarmeu/logo.png
Labels: cla-signed

#2234 Add brand images for brandstofprijzen
  custom_integrations/brandstofprijzen/icon.png
  custom_integrations/brandstofprijzen/icon@2x.png
  custom_integrations/brandstofprijzen/logo.png
  custom_integrations/brandstofprijzen/logo@2x.png
Labels: cla-error

#2235 Add brand images for Rituals
  custom_integrations/rituals_genie/icon.png
  custom_integrations/rituals_genie/icon@2x.png
  custom_integrations/rituals_genie/logo.png
  custom_integrations/rituals_genie/logo@2x.png
Labels: cla-signed

#2216 Add pics for Yeelight_v2 custom integration
  custom_integrations/yeelight_v2/icon.png
  custom_integrations/yeelight_v2/icon@2x.png
  custom_integrations/yeelight_v2/logo.png
  custom_integrations/yeelight_v2/logo@2x.png
Labels: cla-signed

#2240 Updated logo and icon image for n3rgy custom integration.
  custom_integrations/n3rgy/icon.png
  custom_integrations/n3rgy/logo.png
Labels: cla-signed

#2242 Add home assistant icon for my integration
  my
Labels: awaits-parent, cla-signed, has-parent

#2241 Add ha_connector icon and logo
  custom_integrations/ha_connector/icon.png
  custom_integrations/ha_connector/logo.png
Labels: cla-signed

#2245 Add Zaptec icon and logo
  custom_integrations/zaptec/icon.png
  custom_integrations/zaptec/icon@2x.png
  custom_integrations/zaptec/logo.png
  custom_integrations/zaptec/logo@2x.png
Labels: cla-signed

#2246 Add irrigation_unlimited logos and icons
  custom_integrations/irrigation_unlimited/icon.png
  custom_integrations/irrigation_unlimited/icon@2x.png
  custom_integrations/irrigation_unlimited/logo.png
  custom_integrations/irrigation_unlimited/logo@2x.png
Labels: cla-signed

#2249 Add librus icons
  custom_integrations/librus/icon.png
  custom_integrations/librus/icon@2x.png
  custom_integrations/librus/logo.png
  custom_integrations/librus/logo@2x.png
Labels: cla-signed

#2252 Add local_weather_rss new icon and logo
  custom_integrations/local_weather_rss/icon.png
  custom_integrations/local_weather_rss/logo.png
Labels: cla-signed

#2248 adds outgoing_octopus logo and icon
  custom_integrations/outgoing_octopus/icon.png
  custom_integrations/outgoing_octopus/logo.png
Labels: cla-error

#2251 Porscheconnect
  custom_integrations/porscheconnect/icon.png
  custom_integrations/porscheconnect/icon@2x.png
  custom_integrations/porscheconnect/logo.png
  custom_integrations/porscheconnect/logo@2x.png
Labels: cla-signed, in-progress

#2257 add hella_onyx integration
  custom_integrations/hella_onyx/icon.png
  custom_integrations/hella_onyx/icon@2x.png
  custom_integrations/hella_onyx/logo.png
  custom_integrations/hella_onyx/logo@2x.png
Labels: cla-signed

#2258 Adding images for traeger
  custom_integrations/traeger/icon.png
  custom_integrations/traeger/icon@2x.png
  custom_integrations/traeger/logo.png
  custom_integrations/traeger/logo@2x.png
Labels: cla-signed

#2157 Add AEMET OpenData
  core_integrations/aemet/icon.png
  core_integrations/aemet/icon@2x.png
  core_integrations/aemet/logo.png
  core_integrations/aemet/logo@2x.png
Labels: awaits-parent, has-parent

#2259 images for astroweather
  custom_integrations/astroweather/icon.png
  custom_integrations/astroweather/icon@2x.png
  custom_integrations/astroweather/logo.png
  custom_integrations/astroweather/logo@2x.png
Labels: cla-signed

#2265 Remove defunct CoinMarketCap integration
  core_integrations/coinmarketcap/icon.png
  core_integrations/coinmarketcap/icon@2x.png
  core_integrations/coinmarketcap/logo.png
  core_integrations/coinmarketcap/logo@2x.png
Labels: cla-signed

#2269 Add airthings integration assets
  custom_integrations/airthings_integration/icon.png
  custom_integrations/airthings_integration/icon@2x.png
  custom_integrations/airthings_integration/logo.png
  custom_integrations/airthings_integration/logo@2x.png
Labels: cla-signed

#2271 Add wemportal icons
  custom_integrations/wemportal/icon.png
  custom_integrations/wemportal/icon@2x.png
  custom_integrations/wemportal/logo.png
  custom_integrations/wemportal/logo@2x.png
Labels: cla-signed

#1744 Add SmartTub icon
  core_integrations/smarttub/icon.png
Labels: awaits-parent, has-parent, parent-merged

#2243 Add Rituals Perfume Genie core integration brand images
  core_integrations/rituals_perfume_genie/icon.png
  core_integrations/rituals_perfume_genie/icon@2x.png
  core_integrations/rituals_perfume_genie/logo.png
  core_integrations/rituals_perfume_genie/logo@2x.png
Labels: awaits-parent, cla-signed, has-parent, parent-merged

#1631 Added Subaru logos.
  src/subaru/icon.png
  src/subaru/icon@2x.png
  src/subaru/logo.png
  src/subaru/logo@2x.png
Labels: awaits-parent, has-parent, parent-merged

#1926 Add KMtronic logo
  core_integrations/kmtronic/icon.png
Labels: awaits-parent, hacktoberfest-accepted, has-parent

#2275 Add images for Teracom
  custom_integrations/teracom/icon.png
  custom_integrations/teracom/icon@2x.png
  custom_integrations/teracom/logo.png
  custom_integrations/teracom/logo@2x.png
Labels: cla-signed

#2273 🍱 Add Pencom icon and logo
  core_integrations/pencom/icon.png
  core_integrations/pencom/logo.png
Labels: cla-signed

#2277 adding proof icons
  custom_integrations/proof/icon.png
  custom_integrations/proof/icon@2x.png
  custom_integrations/proof/logo.png
  custom_integrations/proof/logo@2x.png
Labels: cla-signed

#2268 added images for integration controlid
  custom_integrations/controlid/icon.png
  custom_integrations/controlid/logo.png
Labels: cla-signed

#2282 Add logo and icon for Zonneplan ONE custom integration
  custom_integrations/zonneplan_one/icon.png
  custom_integrations/zonneplan_one/icon@2x.png
  custom_integrations/zonneplan_one/logo.png
  custom_integrations/zonneplan_one/logo@2x.png
Labels: cla-error

#2228 Move litterrobot images to core_integrations
  core_integrations/litterrobot/icon.png
  core_integrations/litterrobot/icon@2x.png
  core_integrations/litterrobot/logo.png
  core_integrations/litterrobot/logo@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2283 Fix subaru file locations
  core_integrations/subaru/icon.png
  core_integrations/subaru/icon@2x.png
  core_integrations/subaru/logo.png
  core_integrations/subaru/logo@2x.png
Labels: cla-signed

#1692 Add climacell brand logos and icons
  core_integrations/climacell/icon.png
  core_integrations/climacell/icon@2x.png
  core_integrations/climacell/logo.png
  core_integrations/climacell/logo@2x.png
Labels: awaits-parent, has-parent

#1763 Add new Mullvad VPN integration brand images
  core_integrations/mullvad/icon.png
  core_integrations/mullvad/icon@2x.png
  core_integrations/mullvad/logo.png
  core_integrations/mullvad/logo@2x.png
Labels: awaits-parent, has-parent

#2286 Add logo and icon for HomeSeer custom integration
  custom_integrations/homeseer/icon.png
  custom_integrations/homeseer/logo.png
Labels: cla-signed

#2287 Add brand icon for Pollen-HU integration
  custom_integrations/pollen_hu/icon.png
Labels: cla-signed

#1913 Add faadelays icons
  core_integrations/faadelays/icon.png
  core_integrations/faadelays/icon@2x.png
Labels: awaits-parent, hacktoberfest-accepted, has-parent

#2289 added images for deltasol integration
  custom_integrations/deltasol/icon.png
  custom_integrations/deltasol/icon@2x.png
  custom_integrations/deltasol/logo.png
  custom_integrations/deltasol/logo@2x.png
Labels: cla-signed
