Repository home-assistant/brands, pull requests merged in 2021-11, with the labels that each got.

#2925 Add brand Smart Thermostat
  custom_integrations/smart_thermostat/icon.png
  custom_integrations/smart_thermostat/icon@2x.png
Labels: cla-signed

#2924 Add brand openHAB
  custom_integrations/openhab/icon.png
  custom_integrations/openhab/logo.png
Labels: cla-signed

#2923 Add button entity
  core_integrations/button
Labels: cla-signed, parent-merged, hacktoberfest-accepted

#2927 FoxESS brand
  custom_integrations/foxess/icon.png
  custom_integrations/foxess/icon@2x.png
  custom_integrations/foxess/logo.png
  custom_integrations/foxess/logo@2x.png
Labels: cla-signed

#2928 Add Huawei Solar icon
  custom_integrations/huawei_solar/icon.png
  custom_integrations/huawei_solar/icon@2x.png
Labels: cla-signed

#2938 Remove Dyson integration
  core_integrations/dyson/icon.png
  core_integrations/dyson/icon@2x.png
  core_integrations/dyson/logo.png
  core_integrations/dyson/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2931 add barneyman icons
  custom_integrations/barneyman/icon.png
  custom_integrations/barneyman/icon@2x.png
Labels: cla-signed

#2930 Add Brands for custom_component (integration) clage_homeserver (continuous waterheater)
  custom_integrations/clage_homeserver/icon.png
  custom_integrations/clage_homeserver/icon@2x.png
  custom_integrations/clage_homeserver/logo.png
  custom_integrations/clage_homeserver/logo@2x.png
Labels: cla-signed

#2940 Symlink energy to homeassistant
  core_integrations/energy
Labels: cla-signed

#2926 Centrometal peltec wood pellet firing bolier with optional wifi module
  custom_integrations/peltec/icon.png
  custom_integrations/peltec/icon@2x.png
  custom_integrations/peltec/logo.png
  custom_integrations/peltec/logo@2x.png
Labels: cla-signed, cla-error

#2943 Add logo and icon of damda_ev
  custom_integrations/damda_evcharger/icon.png
  custom_integrations/damda_evcharger/icon@2x.png
  custom_integrations/damda_evcharger/logo.png
  custom_integrations/damda_evcharger/logo@2x.png
Labels: cla-signed

#2936 Add Enedis Brand (french electricity network operator)
  custom_integrations/enedis/icon.png
  custom_integrations/enedis/icon@2x.png
  custom_integrations/enedis/logo.png
  custom_integrations/enedis/logo@2x.png
Labels: cla-signed

#2947 Remove mychevy from brands
  core_integrations/mychevy/icon.png
  core_integrations/mychevy/icon@2x.png
  core_integrations/mychevy/logo.png
  core_integrations/mychevy/logo@2x.png
Labels: cla-signed

#2946 Add icons for custom_component schedule_state
  custom_integrations/schedule_state/icon.png
  custom_integrations/schedule_state/icon@2x.png
Labels: cla-signed

#2945 Add icon for waste_collection_schedule
  custom_integrations/waste_collection_schedule/icon.png
Labels: cla-signed

#2944 [ADD] ai_thermostat
  custom_integrations/ai_thermostat/icon.png
  custom_integrations/ai_thermostat/icon@2x.png
Labels: cla-signed

#2918 add brand images for polyaire airtouch4 integration
  custom_integrations/polyaire/icon.png
  custom_integrations/polyaire/icon@2x.png
  custom_integrations/polyaire/logo.png
  custom_integrations/polyaire/logo@2x.png
Labels: cla-signed, hacktoberfest-accepted

#2929 Move RDW assets from custom to core
  core_integrations/rdw/icon.png
  core_integrations/rdw/icon@2x.png
Labels: cla-signed, parent-merged, has-parent

#2227 Add icons for devolo_home_network
  core_integrations/devolo_home_network/icon.png
  core_integrations/devolo_home_network/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2099 Add Jellyfin logo and icon
  core_integrations/jellyfin/icon.png
  core_integrations/jellyfin/icon@2x.png
  core_integrations/jellyfin/logo.png
  core_integrations/jellyfin/logo@2x.png
  custom_integrations/jellyfin/icon.png
  custom_integrations/jellyfin/icon@2x.png
  custom_integrations/jellyfin/logo.png
  custom_integrations/jellyfin/logo@2x.png
Labels: cla-signed, parent-merged, awaits-parent, has-parent

#2950 Added images for domain weatherflow
  custom_integrations/weatherflow/icon.png
  custom_integrations/weatherflow/icon@2x.png
  custom_integrations/weatherflow/logo.png
  custom_integrations/weatherflow/logo@2x.png
Labels: cla-signed

#2956 Add SP110E icon and logo
  custom_integrations/sp110e/icon.png
  custom_integrations/sp110e/icon@2x.png
  custom_integrations/sp110e/logo.png
  custom_integrations/sp110e/logo@2x.png
Labels: cla-signed

#2955 Added NEA logos and icons
  custom_integrations/nea_sg_weather/icon.png
  custom_integrations/nea_sg_weather/icon@2x.png
  custom_integrations/nea_sg_weather/logo.png
  custom_integrations/nea_sg_weather/logo@2x.png
Labels: cla-signed

#2957 Add irrigationprogram icon
  custom_integrations/irrigationprogram/icon.png
  custom_integrations/irrigationprogram/icon@2x.png
Labels: cla-signed, in-progress

#2958 Add icons for the rct_power domain
  custom_integrations/rct_power/icon.png
  custom_integrations/rct_power/icon@2x.png
Labels: cla-signed

#2960 Add Vconnex CC icon
  custom_integrations/vconnex_cc/icon.png
  custom_integrations/vconnex_cc/icon@2x.png
Labels: cla-signed

#2961 Add hass_agent_notifier
  custom_integrations/hass_agent_notifier/icon.png
  custom_integrations/hass_agent_notifier/icon@2x.png
Labels: cla-signed

#2964 Move balboa from custom to core now that it's an integration
  core_integrations/balboa/icon.png
  core_integrations/balboa/icon@2x.png
  core_integrations/balboa/logo.png
  core_integrations/balboa/logo@2x.png
Labels: cla-signed

#2972 Add ipx800v5 custom integration
  custom_integrations/ipx800v5/icon.png
  custom_integrations/ipx800v5/icon@2x.png
  custom_integrations/ipx800v5/logo.png
Labels: cla-signed

#2966 Adds netdaemon custom integration icons
  custom_integrations/netdaemon/icon.png
  custom_integrations/netdaemon/icon@2x.png
Labels: cla-signed

#2971 Add geoJson icon/logos
  core_integrations/geo_json_events/icon.png
  core_integrations/geo_json_events/logo.png
  core_integrations/geo_json_events/logo@2x.png
Labels: cla-signed

#2970 Add flexpoolinfo custom component icons and logos
  custom_integrations/flexpoolinfo/icon.png
  custom_integrations/flexpoolinfo/icon@2x.png
  custom_integrations/flexpoolinfo/logo.png
  custom_integrations/flexpoolinfo/logo@2x.png
Labels: cla-signed

#2967 Add logos for Senz integration
  custom_integrations/senz/icon.png
  custom_integrations/senz/icon@2x.png
  custom_integrations/senz/logo.png
  custom_integrations/senz/logo@2x.png
Labels: cla-signed

#2969 include multizone_thermostat
  custom_integrations/multizone_thermostat/icon.png
Labels: cla-signed

#2965 Add icons & logos for iCloud3 custom component
  custom_integrations/icloud3/icon.png
  custom_integrations/icloud3/icon@2x.png
  custom_integrations/icloud3/logo.png
  custom_integrations/icloud3/logo@2x.png
Labels: cla-signed, in-progress

#2954 Add tesla_wall_connector
  core_integrations/tesla_wall_connector
Labels: cla-signed

#2983 Add MeteoAlarm icons
  core_integrations/meteoalarm/icon.png
  core_integrations/meteoalarm/icon@2x.png
Labels: cla-signed

#2984 Add Norway Air icons
  core_integrations/norway_air/icon.png
  core_integrations/norway_air/icon@2x.png
  core_integrations/norway_air/logo.png
  core_integrations/norway_air/logo@2x.png
Labels: cla-signed

#2982 Add LiteJet icons
  core_integrations/litejet/icon.png
  core_integrations/litejet/icon@2x.png
Labels: cla-signed

#2981 Add iAlarm images
  core_integrations/ialarm/icon.png
  core_integrations/ialarm/icon@2x.png
  core_integrations/ialarm/logo.png
  core_integrations/ialarm/logo@2x.png
Labels: cla-signed

#2980 Better quality for Senz logo
  custom_integrations/senz/logo.png
  custom_integrations/senz/logo@2x.png
Labels: cla-signed
