Repository home-assistant/brands, pull requests merged in 2021-03, with the labels that each got.

#2299 Remove griddy integration
  core_integrations/griddy/icon.png
  core_integrations/griddy/logo.png
Labels: cla-signed

#2295 Add icon for Auto Backup
  custom_integrations/auto_backup/icon.png
  custom_integrations/auto_backup/icon@2x.png
Labels: cla-signed

#2301 Add icon for narodmon custom component
  custom_integrations/narodmon/icon.png
Labels: cla-signed

#2293 Add broadlink s1c
  custom_integrations/broadlink_s1c/icon.png
  custom_integrations/broadlink_s1c/icon@2x.png
  custom_integrations/broadlink_s1c/logo.png
  custom_integrations/broadlink_s1c/logo@2x.png
Labels: cla-needed, in-progress

#2304 Add icon and logo for Beward integration custom component
  custom_integrations/beward/icon.png
  custom_integrations/beward/logo.png
  custom_integrations/beward/logo@2x.png
Labels: cla-signed

#2305 Add icons for Snowtire Sensor custom component
  custom_integrations/snowtire/icon.png
  custom_integrations/snowtire/icon@2x.png
Labels: cla-signed

#2306 Add clientraw custom component icons
  custom_integrations/clientraw/icon.png
  custom_integrations/clientraw/icon@2x.png
  custom_integrations/clientraw/logo.png
  custom_integrations/clientraw/logo@2x.png
Labels: cla-signed

#2308 New person_location custom integration
  custom_integrations/person_location/icon.png
  custom_integrations/person_location/icon@2x.png
Labels: cla-signed

#2312 Add icon for IAQUK custom component
  custom_integrations/iaquk/icon.png
Labels: cla-signed

#2311 Add icons and logos for Gismeteo Weather custom component
  custom_integrations/gismeteo/icon.png
  custom_integrations/gismeteo/icon@2x.png
  custom_integrations/gismeteo/logo.png
  custom_integrations/gismeteo/logo@2x.png
Labels: cla-signed

#2302 Add icon for average sensor custom component
  custom_integrations/average/icon.png
  custom_integrations/average/icon@2x.png
Labels: cla-signed

#2313 Add icons for JQ-300 Integration custom component
  custom_integrations/jq300/icon.png
  custom_integrations/jq300/icon@2x.png
Labels: cla-signed

#2274 🍱 Add Open Exchange Rates icon
  core_integrations/openexchangerates/icon.png
Labels: cla-signed

#2317 Add icons for ha-google-home
  custom_integrations/ha-google-home/icon.png
  custom_integrations/ha-google-home/icon@2x.png
Labels: cla-signed

#2319 Add SAJ icons and logos
  custom_integrations/saj_modbus/icon.png
  custom_integrations/saj_modbus/icon@2x.png
  custom_integrations/saj_modbus/logo.png
  custom_integrations/saj_modbus/logo@2x.png
Labels: cla-signed

#2320 add attributes custom_component icons
  custom_integrations/attributes/icon.png
  custom_integrations/attributes/icon@2x.png
  custom_integrations/attributes/logo.png
  custom_integrations/attributes/logo@2x.png
Labels: cla-signed

#2322 Added NIWA icon and logo
  custom_integrations/niwa_tides/icon.png
  custom_integrations/niwa_tides/icon@2x.png
  custom_integrations/niwa_tides/logo.png
  custom_integrations/niwa_tides/logo@2x.png
Labels: cla-needed

#2323 Change name from ha-google-home to google_home
  custom_integrations/google_home/icon.png
  custom_integrations/google_home/icon@2x.png
Labels: cla-signed

#2316 Icons for my new custom integration spzb0001_thermostat
  custom_integrations/spzb0001_thermostat/icon.png
  custom_integrations/spzb0001_thermostat/icon@2x.png
Labels: cla-signed

#2276 Add nicehash images
  custom_integrations/nicehash/icon.png
  custom_integrations/nicehash/icon@2x.png
  custom_integrations/nicehash/logo.png
  custom_integrations/nicehash/logo@2x.png
Labels: cla-signed

#2318 Rename ipx800 to ipx800v4
  custom_integrations/ipx800v4/icon.png
  custom_integrations/ipx800v4/icon@2x.png
  custom_integrations/ipx800v4/logo.png
Labels: cla-signed

#1855 Move Lyric to core
  core_integrations/lyric/icon.png
  core_integrations/lyric/icon@2x.png
  core_integrations/lyric/logo.png
  core_integrations/lyric/logo@2x.png
Labels: awaits-parent, has-parent

#2332 Add qubino wire pilot logo
  custom_integrations/qubino_wire_pilot/icon.png
  custom_integrations/qubino_wire_pilot/icon@2x.png
  custom_integrations/qubino_wire_pilot/logo.png
  custom_integrations/qubino_wire_pilot/logo@2x.png
Labels: cla-signed

#2331 Images for Channels DVR Recently Recorded custom component
  custom_integrations/channels_dvr_recently_recorded/icon.png
  custom_integrations/channels_dvr_recently_recorded/icon@2x.png
  custom_integrations/channels_dvr_recently_recorded/logo.png
  custom_integrations/channels_dvr_recently_recorded/logo@2x.png
Labels: cla-signed

#2330 Add Ruuvi brand to custom integrations
  custom_integrations/ruuvi/icon.png
  custom_integrations/ruuvi/logo.png
Labels: cla-signed

#2298 stl new custom integration
  custom_integrations/stl/icon.png
  custom_integrations/stl/logo.png
Labels: cla-signed

#2324 Add Casambi icons
  custom_integrations/casambi/icon.png
  custom_integrations/casambi/icon@2x.png
  custom_integrations/casambi/logo.png
  custom_integrations/casambi/logo@2x.png
Labels: cla-signed

#2327 add custom integration Deebot for Home Assistant
  custom_integrations/deebot/icon.png
  custom_integrations/deebot/icon@2x.png
  custom_integrations/deebot/logo.png
  custom_integrations/deebot/logo@2x.png
Labels: cla-signed

#2326 Update Sonos branding
  core_integrations/sonos/logo.png
  core_integrations/sonos/logo@2x.png
Labels: cla-signed

#2334 Add screenlogic
  core_integrations/screenlogic/icon.png
  core_integrations/screenlogic/icon@2x.png
  core_integrations/screenlogic/logo.png
Labels: awaits-parent, cla-signed, has-parent

#2333 Add icons for MLGW custom integration
  custom_integrations/mlgw/icon.png
  custom_integrations/mlgw/icon@2x.png
  custom_integrations/mlgw/logo.png
  custom_integrations/mlgw/logo@2x.png
Labels: cla-signed

#2340 New integration brand: MagicSwitchbot
  custom_integrations/magicswitchbot/icon.png
  custom_integrations/magicswitchbot/logo.png
Labels: cla-error

#2343 Made Garmin Connect images transparent
  core_integrations/garmin_connect/icon.png
  core_integrations/garmin_connect/icon@2x.png
  core_integrations/garmin_connect/logo.png
  core_integrations/garmin_connect/logo@2x.png
Labels: cla-signed

#2348 Add Nobø brand to custom integrations
  custom_integrations/nobo_hub/icon.png
  custom_integrations/nobo_hub/icon@2x.png
  custom_integrations/nobo_hub/logo.png
Labels: cla-signed, in-progress

#2347 Add ubee logos and icons
  custom_integrations/ubee/icon.png
  custom_integrations/ubee/icon@2x.png
  custom_integrations/ubee/logo.png
  custom_integrations/ubee/logo@2x.png
Labels: cla-signed

#2350 Add toyota brand images for my custom integration toyota
  custom_integrations/toyota/icon.png
  custom_integrations/toyota/icon@2x.png
Labels: cla-signed

#2346 added new integration vapix
  custom_integrations/vapix/icon.png
  custom_integrations/vapix/icon@2x.png
  custom_integrations/vapix/logo.png
  custom_integrations/vapix/logo@2x.png
Labels: cla-error, cla-signed, in-progress

#2354 delete integration
  custom_integrations/delete/icon.png
  custom_integrations/delete/icon@2x.png
  custom_integrations/delete/logo.png
  custom_integrations/delete/logo@2x.png
Labels: cla-signed

#2359 Add Jumbo Brand to Custom Integrations
  custom_integrations/jumbo/icon.png
  custom_integrations/jumbo/icon@2x.png
  custom_integrations/jumbo/logo.png
  custom_integrations/jumbo/logo@2x.png
Labels: cla-signed

#2366 Add icon and logo for custom integration Zadnego Ale
  custom_integrations/zadnego_ale/icon.png
  custom_integrations/zadnego_ale/icon@2x.png
  custom_integrations/zadnego_ale/logo.png
  custom_integrations/zadnego_ale/logo@2x.png
Labels: cla-signed

#2272 Add Legrand Home+ Control logos and icons.
  core_integrations/home_plus_control/icon.png
  core_integrations/home_plus_control/icon@2x.png
  core_integrations/home_plus_control/logo.png
  core_integrations/home_plus_control/logo@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2368 Add a new logo or icon for a custom integration (damda_pad)
  custom_integrations/damda_pad/icon.png
  custom_integrations/damda_pad/icon@2x.png
  custom_integrations/damda_pad/logo.png
  custom_integrations/damda_pad/logo@2x.png
Labels: cla-signed

#2371 Added meross_lan custom integration brand images
  custom_integrations/meross_lan/icon.png
  custom_integrations/meross_lan/icon@2x.png
  custom_integrations/meross_lan/logo.png
  custom_integrations/meross_lan/logo@2x.png
Labels: cla-signed

#2358 Add icons for analytics integration
  core_integrations/analytics/icon.png
  core_integrations/analytics/icon@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2374 Add Govee brand icon/logo
  custom_integrations/govee/icon.png
  custom_integrations/govee/icon@2x.png
  custom_integrations/govee/logo.png
  custom_integrations/govee/logo@2x.png
Labels: cla-signed

#2375 Add missing internal domains
  core_integrations/calendar
  core_integrations/image_processing
  core_integrations/mailbox
  core_integrations/trace
Labels: cla-signed

#2376 Correct FAA Delays integration domain
  core_integrations/faa_delays/icon.png
  core_integrations/faa_delays/icon@2x.png
Labels: cla-signed

#2377 Add icons for Ferroamp custom integration
  custom_integrations/ferroamp/icon.png
  custom_integrations/ferroamp/icon@2x.png
  custom_integrations/ferroamp/logo.png
  custom_integrations/ferroamp/logo@2x.png
Labels: cla-signed
