Repository home-assistant/brands, pull requests merged in 2021-08, with the labels that each got.

#2727 Adaptive lighting
  custom_integrations/adaptive_lighting/icon.png
  custom_integrations/adaptive_lighting/icon@2x.png
  custom_integrations/adaptive_lighting/logo.png
Labels: cla-signed

#2726 Added brand images for internode
  custom_integrations/internode/icon.png
  custom_integrations/internode/icon@2x.png
  custom_integrations/internode/logo.png
  custom_integrations/internode/logo@2x.png
Labels: cla-signed

#2724 - added oppo_udp images
  custom_integrations/oppo_udp/icon.png
  custom_integrations/oppo_udp/icon@2x.png
  custom_integrations/oppo_udp/logo.png
  custom_integrations/oppo_udp/logo@2x.png
Labels: cla-signed

#2723 Added brand images for auroraplus
  custom_integrations/auroraplus/icon.png
  custom_integrations/auroraplus/icon@2x.png
  custom_integrations/auroraplus/logo.png
  custom_integrations/auroraplus/logo@2x.png
Labels: cla-signed

#2721 Adding NSWCovid
  custom_integrations/nswcovid/icon.png
  custom_integrations/nswcovid/icon@2x.png
  custom_integrations/nswcovid/logo.png
  custom_integrations/nswcovid/logo@2x.png
Labels: cla-signed

#1825 Add new component renault logo and icon
  core_integrations/renault/icon.png
  core_integrations/renault/icon@2x.png
  core_integrations/renault/logo.png
  core_integrations/renault/logo@2x.png
Labels: awaits-parent, has-parent

#2600 Move tractive logos to core integrations
  core_integrations/tractive/icon.png
  core_integrations/tractive/icon@2x.png
  core_integrations/tractive/logo.png
  core_integrations/tractive/logo@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2738 add teletask logos
  custom_integrations/teletask/icon.png
  custom_integrations/teletask/icon@2x.png
Labels: cla-signed, in-progress

#2739 add MyBmw logos
  custom_integrations/bmw_connected/icon.png
  custom_integrations/bmw_connected/icon@2x.png
Labels: cla-signed

#2737 Add ge_home custom integration
  custom_integrations/ge_home/icon.png
  custom_integrations/ge_home/icon@2x.png
  custom_integrations/ge_home/logo.png
  custom_integrations/ge_home/logo@2x.png
Labels: cla-signed

#2734 Adds brand images for CasaTunes
  custom_integrations/casatunes/icon.png
  custom_integrations/casatunes/icon@2x.png
  custom_integrations/casatunes/logo.png
  custom_integrations/casatunes/logo@2x.png
Labels: cla-signed

#2733 add aria2 custom integration brand
  custom_integrations/aria2/icon.png
  custom_integrations/aria2/icon@2x.png
Labels: cla-signed

#2735 Update icon and logo for uptimerobot
  core_integrations/uptimerobot/icon.png
  core_integrations/uptimerobot/icon@2x.png
  core_integrations/uptimerobot/logo.png
  core_integrations/uptimerobot/logo@2x.png
Labels: cla-signed

#2736 Add support for images optimized for dark themes
  .github/workflows/validate/validate.sh
  README.md
  core_integrations/uptimerobot/dark_logo.png
  core_integrations/uptimerobot/dark_logo@2x.png
  netlify.toml
  scripts/build.sh
Labels: cla-signed

#2731 Add honor_x3 integration.
  custom_integrations/honor_x3/icon.png
  custom_integrations/honor_x3/logo.png
Labels: cla-signed, in-progress

#2741 Add AMD brand images for ha_pyamdgpuinfo
  custom_integrations/ha_pyamdgpuinfo/icon.png
  custom_integrations/ha_pyamdgpuinfo/icon@2x.png
Labels: cla-signed

#2745 Add Youless Images
  core_integrations/youless/icon.png
  core_integrations/youless/logo.png
Labels: cla-signed

#2744 Add IntesisHome logo
  core_integrations/intesishome/icon.png
  core_integrations/intesishome/logo.png
  core_integrations/intesishome/logo@2x.png
Labels: cla-signed

#2747 Add New midea_ac_lan Integration
  custom_integrations/midea_ac_lan/icon.png
  custom_integrations/midea_ac_lan/icon@2x.png
  custom_integrations/midea_ac_lan/logo.png
  custom_integrations/midea_ac_lan/logo@2x.png
Labels: cla-signed

#2748 Add uvfive Images
  custom_integrations/uvfive/icon.png
  custom_integrations/uvfive/icon@2x.png
  custom_integrations/uvfive/logo.png
  custom_integrations/uvfive/logo@2x.png
Labels: cla-signed

#2749 Move automate to custom_integrations from core
  core_integrations/automate/icon.png
  core_integrations/automate/logo.png
  core_integrations/automate/logo@2x.png
  custom_integrations/automate/icon.png
  custom_integrations/automate/icon@2x.png
  custom_integrations/automate/logo.png
  custom_integrations/automate/logo@2x.png
Labels: cla-signed

#2746 Add Anniversary integration
  custom_integrations/anniversary/icon.png
Labels: cla-signed

#2751 Add icons for gree_ext, gree extension functionality custom component
  custom_integrations/gree_ext/icon.png
  custom_integrations/gree_ext/icon@2x.png
  custom_integrations/gree_ext/logo.png
  custom_integrations/gree_ext/logo@2x.png
Labels: cla-signed, cla-error

#2729 Added [energosbyt_plus]
  custom_integrations/energosbyt_plus/icon.png
  custom_integrations/energosbyt_plus/icon@2x.png
  custom_integrations/energosbyt_plus/logo.png
  custom_integrations/energosbyt_plus/logo@2x.png
Labels: cla-signed

#2718 Add brand image for 'WaterMyYard-Pro'
  custom_integrations/watermyyard-pro/icon.png
  custom_integrations/watermyyard-pro/icon@2x.png
  custom_integrations/watermyyard-pro/logo.png
  custom_integrations/watermyyard-pro/logo@2x.png
Labels: cla-error

#2753 Add covid19_kr icon and logo
  custom_integrations/covid19_kr/icon.png
  custom_integrations/covid19_kr/logo.png
Labels: cla-signed

#2038 logos for airtouch 4 integration
  core_integrations/airtouch4/icon.png
  core_integrations/airtouch4/icon@2x.png
  core_integrations/airtouch4/logo.png
  core_integrations/airtouch4/logo@2x.png
Labels: awaits-parent, has-parent

#2763 Add new meizu_remoter_gateway integration
  custom_integrations/meizu_remoter_gateway/icon.png
  custom_integrations/meizu_remoter_gateway/icon@2x.png
  custom_integrations/meizu_remoter_gateway/logo.png
  custom_integrations/meizu_remoter_gateway/logo@2x.png
Labels: cla-signed

#2762 Add lan_smartthings images
  custom_integrations/lan_smartthings/icon.png
  custom_integrations/lan_smartthings/icon@2x.png
  custom_integrations/lan_smartthings/logo.png
  custom_integrations/lan_smartthings/logo@2x.png
Labels: cla-signed

#2764 Update xiaomi-related brand logos and icons
  core_integrations/xiaomi/icon.png
  core_integrations/xiaomi/icon@2x.png
  core_integrations/xiaomi/logo.png
  core_integrations/xiaomi/logo@2x.png
  custom_integrations/xiaomi_miot/icon.png
  custom_integrations/xiaomi_miot/icon@2x.png
  custom_integrations/xiaomi_miot/logo.png
  custom_integrations/xiaomi_miot/logo@2x.png
Labels: cla-signed

#2754 Adding icons for p1 monitor integration
  core_integrations/p1_monitor/icon.png
  core_integrations/p1_monitor/icon@2x.png
Labels: cla-signed, has-parent

#2697 Add logo for fjaraskupan
  core_integrations/fjaraskupan/icon.png
  core_integrations/fjaraskupan/icon@2x.png
  core_integrations/fjaraskupan/logo.png
  core_integrations/fjaraskupan/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2765 Update custom_integrate xiaomi-related logos
  custom_integrations/xiaomi_cloud_map_extractor/icon.png
  custom_integrations/xiaomi_cloud_map_extractor/icon@2x.png
  custom_integrations/xiaomi_cloud_map_extractor/logo.png
  custom_integrations/xiaomi_cloud_map_extractor/logo@2x.png
  custom_integrations/xiaomi_gateway3/icon.png
  custom_integrations/xiaomi_gateway3/icon@2x.png
  custom_integrations/xiaomi_gateway3/logo.png
  custom_integrations/xiaomi_gateway3/logo@2x.png
  custom_integrations/xiaomi_miio_airconditioningcompanion/icon.png
  custom_integrations/xiaomi_miio_airconditioningcompanion/icon@2x.png
  custom_integrations/xiaomi_miio_airconditioningcompanion/logo.png
  custom_integrations/xiaomi_miio_airconditioningcompanion/logo@2x.png
  custom_integrations/xiaomi_miio_airpurifier/icon.png
  custom_integrations/xiaomi_miio_airpurifier/icon@2x.png
  custom_integrations/xiaomi_miio_airpurifier/logo.png
  custom_integrations/xiaomi_miio_airpurifier/logo@2x.png
  custom_integrations/xiaomi_miio_cooker/icon.png
  custom_integrations/xiaomi_miio_cooker/icon@2x.png
  custom_integrations/xiaomi_miio_cooker/logo.png
  custom_integrations/xiaomi_miio_cooker/logo@2x.png
  custom_integrations/xiaomi_miio_fan/icon.png
  custom_integrations/xiaomi_miio_fan/icon@2x.png
  custom_integrations/xiaomi_miio_fan/logo.png
  custom_integrations/xiaomi_miio_fan/logo@2x.png
  custom_integrations/xiaomi_miio_philipslight/icon.png
  custom_integrations/xiaomi_miio_philipslight/icon@2x.png
  custom_integrations/xiaomi_miio_philipslight/logo.png
  custom_integrations/xiaomi_miio_philipslight/logo@2x.png
  custom_integrations/xiaomi_miio_plug/icon.png
  custom_integrations/xiaomi_miio_plug/icon@2x.png
  custom_integrations/xiaomi_miio_plug/logo.png
  custom_integrations/xiaomi_miio_plug/logo@2x.png
  custom_integrations/xiaomi_miio_raw/icon.png
  custom_integrations/xiaomi_miio_raw/icon@2x.png
  custom_integrations/xiaomi_miio_raw/logo.png
  custom_integrations/xiaomi_miio_raw/logo@2x.png
  custom_integrations/xiaomi_miot_raw/icon.png
  custom_integrations/xiaomi_miot_raw/icon@2x.png
  custom_integrations/xiaomi_miot_raw/logo.png
  custom_integrations/xiaomi_miot_raw/logo@2x.png
  custom_integrations/xiaomi_viomi/icon.png
  custom_integrations/xiaomi_viomi/icon@2x.png
  custom_integrations/xiaomi_viomi/logo.png
  custom_integrations/xiaomi_viomi/logo@2x.png
Labels: cla-signed

#2767 Add usb symlink
  core_integrations/usb
Labels: cla-signed

#2758 Add images for garmin_connect
  custom_integrations/garmin_connect/icon.png
  custom_integrations/garmin_connect/icon@2x.png
  custom_integrations/garmin_connect/logo.png
  custom_integrations/garmin_connect/logo@2x.png
Labels: cla-signed

#2760 Added icons for custom component somneo
  custom_integrations/somneo/icon.png
  custom_integrations/somneo/icon@2x.png
  custom_integrations/somneo/logo.png
  custom_integrations/somneo/logo@2x.png
Labels: cla-signed, in-progress

#2770 Add images for duke_energy_gateway custom integration
  custom_integrations/duke_energy_gateway/icon.png
  custom_integrations/duke_energy_gateway/icon@2x.png
  custom_integrations/duke_energy_gateway/logo.png
  custom_integrations/duke_energy_gateway/logo@2x.png
Labels: cla-signed

#2771 Add icons, logos for uHoo integration
  custom_integrations/uhoo/dark_logo.png
  custom_integrations/uhoo/dark_logo@2x.png
  custom_integrations/uhoo/icon.png
  custom_integrations/uhoo/icon@2x.png
  custom_integrations/uhoo/logo.png
  custom_integrations/uhoo/logo@2x.png
Labels: cla-signed

#2769 WebHook Service Custom Integration
  custom_integrations/webhook_service/icon.png
Labels: cla-signed, in-progress

#2772 Add icon and logo files for Mixergy
  custom_integrations/mixergy/icon.png
  custom_integrations/mixergy/icon@2x.png
  custom_integrations/mixergy/logo.png
  custom_integrations/mixergy/logo@2x.png
Labels: cla-signed

#2732 Add images for IoTaWatt
  core_integrations/iotawatt/icon.png
  core_integrations/iotawatt/icon@2x.png
  core_integrations/iotawatt/logo.png
  core_integrations/iotawatt/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2782 Added MyEnergi logo and icon
  custom_integrations/myenergi/dark_logo.png
  custom_integrations/myenergi/dark_logo@2x.png
  custom_integrations/myenergi/icon.png
  custom_integrations/myenergi/icon@2x.png
  custom_integrations/myenergi/logo.png
  custom_integrations/myenergi/logo@2x.png
Labels: cla-signed
