Repository home-assistant/brands, pull requests merged in 2021-09, with the labels that each got.

#2777 add openei icons
  custom_integrations/openei/icon.png
  custom_integrations/openei/icon@2x.png
Labels: cla-signed, in-progress

#2783 Adding CleverSpa Icons and Logos
  custom_integrations/cleverspa/dark_icon.png
  custom_integrations/cleverspa/dark_icon@2x.png
  custom_integrations/cleverspa/dark_logo.png
  custom_integrations/cleverspa/dark_logo@2x.png
  custom_integrations/cleverspa/icon.png
  custom_integrations/cleverspa/icon@2x.png
  custom_integrations/cleverspa/logo.png
  custom_integrations/cleverspa/logo@2x.png
Labels: cla-signed

#2786 Add images for rdw
  custom_integrations/rdw/icon.png
  custom_integrations/rdw/icon@2x.png
Labels: cla-signed

#2784 add Windcentrale brand logo and icon
  custom_integrations/windcentrale/icon.png
  custom_integrations/windcentrale/icon@2x.png
  custom_integrations/windcentrale/logo.png
  custom_integrations/windcentrale/logo@2x.png
Labels: cla-signed

#2785 Add images for arris_dcx960
  custom_integrations/arris_dcx960/icon.png
  custom_integrations/arris_dcx960/logo.png
  custom_integrations/arris_dcx960/logo@2x.png
Labels: cla-signed

#2787 Add images for kamstrup_403
  custom_integrations/kamstrup_403/icon.png
  custom_integrations/kamstrup_403/icon@2x.png
  custom_integrations/kamstrup_403/logo.png
  custom_integrations/kamstrup_403/logo@2x.png
Labels: cla-signed

#2802 Add o365
  custom_integrations/o365/icon.png
  custom_integrations/o365/icon@2x.png
Labels: cla-signed

#2801 Custom integration here weather
  custom_integrations/here_weather/icon.png
  custom_integrations/here_weather/icon@2x.png
Labels: cla-signed

#2796 Add icon and logo images for ecowater_softener custom component
  custom_integrations/ecowater_softener/icon.png
  custom_integrations/ecowater_softener/icon@2x.png
  custom_integrations/ecowater_softener/logo.png
  custom_integrations/ecowater_softener/logo@2x.png
Labels: cla-signed

#2799 Logo and icon for Repsol
  custom_integrations/repsolluzygas/icon.png
  custom_integrations/repsolluzygas/logo.png
Labels: cla-signed

#2792 Added duepi_evo pellet stoves
  custom_integrations/duepi_evo/icon.png
  custom_integrations/duepi_evo/logo.png
Labels: cla-signed

#2795 add battery_consumption
  custom_integrations/battery_consumption/icon.png
  custom_integrations/battery_consumption/icon@2x.png
Labels: cla-signed

#2812 Add icon for battery_sim custom component
  custom_integrations/battery_sim/icon.png
  custom_integrations/battery_sim/icon@2x.png
Labels: cla-signed

#2803 Remove Trackr integration (API removed)
  core_integrations/trackr/icon.png
  core_integrations/trackr/logo.png
Labels: cla-signed

#2814 Add image for Meteoalarm core integration
  core_integrations/meteoalarm/logo.png
  core_integrations/meteoalarm/logo@2x.png
Labels: cla-signed

#2395 Add icons for Whirlpool integration
  core_integrations/whirlpool/icon.png
  core_integrations/whirlpool/icon@2x.png
  core_integrations/whirlpool/logo.png
  core_integrations/whirlpool/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2815 Add WattTime branding (core integration)
  core_integrations/watttime/icon.png
  core_integrations/watttime/logo.png
  core_integrations/watttime/logo@2x.png
Labels: cla-signed, parent-merged, has-parent, has-codeowner

#2818 Add icon for bodymiscale custom integration
  custom_integrations/bodymiscale/logo.png
  custom_integrations/bodymiscale/logo@2x.png
Labels: cla-signed, in-progress

#2834 ADD: mqtt_discoverystream
  custom_integrations/mqtt_discoverystream/icon.png
  custom_integrations/mqtt_discoverystream/icon@2x.png
  custom_integrations/mqtt_discoverystream/logo.png
  custom_integrations/mqtt_discoverystream/logo@2x.png
Labels: cla-signed

#2780 add wort_des_tages
  custom_integrations/wort_des_tages/icon.png
  custom_integrations/wort_des_tages/icon@2x.png
  custom_integrations/wort_des_tages/logo.png
  custom_integrations/wort_des_tages/logo@2x.png
Labels: cla-signed

#2838 Airthings
  core_integrations/airthings/icon.png
  core_integrations/airthings/icon@2x.png
  core_integrations/airthings/logo.png
  core_integrations/airthings/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2822 Add icons and logos for Cash App
  custom_integrations/cashapp/icon.png
  custom_integrations/cashapp/icon@2x.png
  custom_integrations/cashapp/logo.png
  custom_integrations/cashapp/logo@2x.png
Labels: cla-signed

#2804 Add icons and logos for Duolingo
  custom_integrations/duolingo/icon.png
  custom_integrations/duolingo/icon@2x.png
  custom_integrations/duolingo/logo.png
  custom_integrations/duolingo/logo@2x.png
Labels: cla-signed

#2827 Icon.png for SmarterCoffee custom integration
  custom_integrations/smartercoffee/icon.png
Labels: cla-signed

#2824 Adds new custom integration [pik_intercom]
  custom_integrations/pik_intercom/icon.png
  custom_integrations/pik_intercom/icon@2x.png
Labels: cla-signed

#2829 Added icons for custom integration openwbmqtt
  custom_integrations/openwbmqtt/icon.png
  custom_integrations/openwbmqtt/icon@2x.png
Labels: cla-signed

#2844 solcast integration
  custom_integrations/solcast_solar/icon.png
  custom_integrations/solcast_solar/logo.png
Labels: cla-signed

#2819 Add icons for Luxor (FXLuminaire)
  custom_integrations/luxor/icon.png
  custom_integrations/luxor/icon@2x.png
Labels: cla-signed

#2806 Add icon for g4s_alarm custom component
  custom_integrations/g4s_alarm/icon.png
  custom_integrations/g4s_alarm/icon@2x.png
  custom_integrations/g4s_alarm/logo.png
  custom_integrations/g4s_alarm/logo@2x.png
Labels: cla-signed

#2830 Add icon for homeeasy local custom component
  custom_integrations/homeeasy_local/icon.png
  custom_integrations/homeeasy_local/icon@2x.png
Labels: cla-signed

#2825 Adds new custom integration [pik_comfort]
  custom_integrations/pik_comfort/icon.png
  custom_integrations/pik_comfort/icon@2x.png
  custom_integrations/pik_comfort/logo.png
  custom_integrations/pik_comfort/logo@2x.png
Labels: cla-signed, in-progress

#2849 high res icon
  custom_integrations/solcast_solar/icon.png
  custom_integrations/solcast_solar/icon@2x.png
Labels: cla-signed

#2847 Add Hik-Connect
  custom_integrations/hikconnect/icon.png
  custom_integrations/hikconnect/icon@2x.png
  custom_integrations/hikconnect/logo.png
  custom_integrations/hikconnect/logo@2x.png
Labels: cla-signed, in-progress

#2850 Adding icons for omnik inverter integration
  custom_integrations/omnik_inverter/icon.png
  custom_integrations/omnik_inverter/icon@2x.png
  custom_integrations/omnik_inverter/logo.png
  custom_integrations/omnik_inverter/logo@2x.png
Labels: cla-signed, in-progress

#2851 Add icons for home-assistant-tapo-p100 integration
  custom_integrations/tapo/icon.png
  custom_integrations/tapo/logo.png
Labels: cla-signed

#2852 add icons for dwd_pollenflug
  custom_integrations/dwd_pollenflug/icon.png
  custom_integrations/dwd_pollenflug/logo.png
Labels: cla-signed

#2853 Added tv4_play brand
  custom_integrations/tv4_play/icon.png
  custom_integrations/tv4_play/icon@2x.png
Labels: cla-signed, in-progress
