Repository home-assistant/brands, pull requests merged in 2021-12, with the labels that each got.

#2951 Add Tailscale
  core_integrations/tailscale/dark_icon.png
  core_integrations/tailscale/dark_icon@2x.png
  core_integrations/tailscale/dark_logo.png
  core_integrations/tailscale/dark_logo@2x.png
  core_integrations/tailscale/icon.png
  core_integrations/tailscale/icon@2x.png
  core_integrations/tailscale/logo.png
  core_integrations/tailscale/logo@2x.png
Labels: cla-signed, has-parent

#2985 Add icons for config_editor custom component
  custom_integrations/config_editor/icon.png
  custom_integrations/config_editor/icon@2x.png
Labels: cla-signed, in-progress

#2986 add brand icons for bpost
  custom_integrations/bpost/icon.png
  custom_integrations/bpost/icon@2x.png
Labels: cla-signed

#2987 Add Dwains Dashboard icon & logo
  custom_integrations/dwains_dashboard/dark_logo.png
  custom_integrations/dwains_dashboard/dark_logo@2x.png
  custom_integrations/dwains_dashboard/icon.png
  custom_integrations/dwains_dashboard/icon@2x.png
  custom_integrations/dwains_dashboard/logo.png
  custom_integrations/dwains_dashboard/logo@2x.png
Labels: cla-signed

#2842 Added brand NINA
  core_integrations/nina/icon.png
  core_integrations/nina/logo.png
Labels: cla-signed, awaits-parent, has-parent

#2988 Add icon for tolo integration
  core_integrations/tolo/icon.png
Labels: cla-signed

#2941 Added Elmax logo and icon
  core_integrations/elmax/icon.png
  core_integrations/elmax/icon@2x.png
  core_integrations/elmax/logo.png
  core_integrations/elmax/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2991 Remove loopenergy
  core_integrations/loopenergy/icon.png
  core_integrations/loopenergy/icon@2x.png
  core_integrations/loopenergy/logo.png
  core_integrations/loopenergy/logo@2x.png
Labels: cla-signed

#2990 add hyperhdr images
  custom_integrations/hyperhdr/icon.png
  custom_integrations/hyperhdr/logo.png
Labels: cla-signed

#2992 Adds icon for thermiagenesis
  custom_integrations/thermiagenesis/icon.png
  custom_integrations/thermiagenesis/icon@2x.png
Labels: cla-signed

#2995 add icon
  custom_integrations/dusunzigbee/icon.png
  custom_integrations/dusunzigbee/icon@2x.png
Labels: cla-signed

#2821 Add Aseko Pool Live core integration
  core_integrations/aseko_pool_live/dark_logo.png
  core_integrations/aseko_pool_live/dark_logo@2x.png
  core_integrations/aseko_pool_live/icon.png
  core_integrations/aseko_pool_live/logo.png
  core_integrations/aseko_pool_live/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2994 Add icon for Davis Weatherlink
  weatherlink/icon.png
  weatherlink/icon@2x.png
Labels: cla-signed

#3000 Dark Images for unifiprotect
  custom_integrations/unifiprotect/dark_icon.png
  custom_integrations/unifiprotect/dark_icon@2x.png
  custom_integrations/unifiprotect/dark_logo.png
  custom_integrations/unifiprotect/dark_logo@2x.png
Labels: cla-signed

#2920 Add evil genius labs icon
  core_integrations/evil_genius_labs/icon.png
Labels: cla-signed, awaits-parent, has-parent, hacktoberfest-accepted

#2996 Move files to correct place
  custom_integrations/weatherlink/icon.png
  custom_integrations/weatherlink/icon@2x.png
Labels: cla-signed

#3001 Add Thermal Comfort logo and icon
  custom_integrations/thermal_comfort/icon.png
  custom_integrations/thermal_comfort/icon@2x.png
  custom_integrations/thermal_comfort/logo.png
  custom_integrations/thermal_comfort/logo@2x.png
Labels: cla-signed

#3004 Update icons for /integrations/androidtv/
  core_integrations/androidtv/dark_logo.png
  core_integrations/androidtv/dark_logo@2x.png
  core_integrations/androidtv/icon.png
  core_integrations/androidtv/icon@2x.png
  core_integrations/androidtv/logo.png
  core_integrations/androidtv/logo@2x.png
Labels: cla-signed

#3006 add icons for nfandroidtv
  core_integrations/nfandroidtv/icon.png
  core_integrations/nfandroidtv/icon@2x.png
Labels: cla-signed

#3007 update icons for home-connect
  core_integrations/home_connect/icon.png
  core_integrations/home_connect/icon@2x.png
Labels: cla-signed

#3012 Add cloud music logo and icon
  custom_integrations/ha_cloud_music/icon.png
  custom_integrations/ha_cloud_music/icon@2x.png
  custom_integrations/ha_cloud_music/logo.png
  custom_integrations/ha_cloud_music/logo@2x.png
Labels: cla-signed

#3011 feat: add Branding Icon for ha_kia_hyundai
  custom_integrations/ha_kia_hyundai/icon.png
  custom_integrations/ha_kia_hyundai/icon@2x.png
Labels: cla-signed, cla-error

#3010 Add icon and logo for TuneBlade custom integration
  custom_integrations/tuneblade/icon.png
Labels: cla-signed

#3013 Add microbot_push icon and logo
  custom_integrations/microbot_push/icon.png
  custom_integrations/microbot_push/logo.png
Labels: cla-signed

#2973 Add Open-Meteo integration
  core_integrations/open_meteo/icon.png
Labels: cla-signed, parent-merged, has-parent

#3015 add file explorer icon
  custom_integrations/ha_file_explorer/icon.png
  custom_integrations/ha_file_explorer/icon@2x.png
Labels: cla-signed

#3016 Add icons and logos for Midea dehumidifer lan custom integration
  custom_integrations/midea_dehumidifier_lan/icon.png
  custom_integrations/midea_dehumidifier_lan/icon@2x.png
  custom_integrations/midea_dehumidifier_lan/logo.png
  custom_integrations/midea_dehumidifier_lan/logo@2x.png
Labels: cla-signed

#3017 Move tahoma integration from `core_integrations` to `custom_integrations`
  custom_integrations/tahoma/icon.png
  custom_integrations/tahoma/icon@2x.png
  custom_integrations/tahoma/logo.png
  custom_integrations/tahoma/logo@2x.png
Labels: cla-signed

#3030 Made icons transparent
  core_integrations/withings/icon.png
  core_integrations/withings/icon@2x.png
Labels: cla-signed

#3028 Add icons for custom integration tplink_deco (copied from core integr…
  custom_integrations/tplink_deco/icon.png
  custom_integrations/tplink_deco/icon@2x.png
  custom_integrations/tplink_deco/logo.png
  custom_integrations/tplink_deco/logo@2x.png
Labels: cla-signed

#3027 Create keyatome
  custom_integrations/keyatome/icon.png
  custom_integrations/keyatome/icon@2x.png
  custom_integrations/keyatome/logo.png
  custom_integrations/keyatome/logo@2x.png
Labels: cla-signed

#3020 Submitting NYC 311 logo.
  custom_integrations/nyc311/icon.png
  custom_integrations/nyc311/icon@2x.png
Labels: cla-signed

#2478 Add Overkiz brand for new core integration
  core_integrations/overkiz/icon.png
  core_integrations/overkiz/icon@2x.png
  core_integrations/overkiz/logo.png
  core_integrations/overkiz/logo@2x.png
Labels: cla-signed, parent-merged, awaits-parent, has-parent

#3026 Added icons for Thermia custom component
  custom_integrations/thermia/icon.png
  custom_integrations/thermia/icon@2x.png
Labels: cla-signed

#3025 rename peltec integration to centrometal_boiler
  custom_integrations/centrometal_boiler/icon.png
  custom_integrations/centrometal_boiler/icon@2x.png
  custom_integrations/centrometal_boiler/logo.png
  custom_integrations/centrometal_boiler/logo@2x.png
Labels: cla-signed

#3033 Add brand for Toyota (North America)
  custom_integrations/toyota_na/icon.png
  custom_integrations/toyota_na/icon@2x.png
Labels: cla-signed

#3019 Adding icons for new unifiprotect integration
  core_integrations/unifiprotect/dark_icon.png
  core_integrations/unifiprotect/dark_icon@2x.png
  core_integrations/unifiprotect/dark_logo.png
  core_integrations/unifiprotect/dark_logo@2x.png
  core_integrations/unifiprotect/icon.png
  core_integrations/unifiprotect/icon@2x.png
  core_integrations/unifiprotect/logo.png
  core_integrations/unifiprotect/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent
