Repository home-assistant/brands, pull requests merged in 2021-07, with the labels that each got.

#2663 Add logos for OSRM
  custom_integrations/osrm_travel_time/icon.png
  custom_integrations/osrm_travel_time/icon@2x.png
  custom_integrations/osrm_travel_time/logo.png
  custom_integrations/osrm_travel_time/logo@2x.png
Labels: cla-signed

#2664 Add Icon and Logo for Rinnai Integration
  custom_integrations/rinnai/icon.png
  custom_integrations/rinnai/icon@2x.png
  custom_integrations/rinnai/logo.png
  custom_integrations/rinnai/logo@2x.png
Labels: cla-signed

#2669 Add custom integration brand from Netgear WAX
  custom_integrations/netgear_wax/icon.png
  custom_integrations/netgear_wax/icon@2x.png
  custom_integrations/netgear_wax/logo.png
  custom_integrations/netgear_wax/logo@2x.png
Labels: cla-signed

#2642 Add Libratone Zipp integration
  custom_integrations/libratone_zipp/icon.png
  custom_integrations/libratone_zipp/icon@2x.png
  custom_integrations/libratone_zipp/logo.png
  custom_integrations/libratone_zipp/logo@2x.png
Labels: cla-signed

#2671 add icons for ocpp
  custom_integrations/ocpp/icon.png
  custom_integrations/ocpp/icon@2x.png
Labels: cla-signed

#2674 Added icons for cover_time_based_synced
  custom_integrations/cover_time_based_synced/icon.png
  custom_integrations/cover_time_based_synced/icon@2x.png
Labels: cla-signed

#2364 Add siren to brands by symlinking to homeassistant logos
  core_integrations/siren
Labels: awaits-parent, cla-signed, has-parent

#2677 New Logo and Icon - Virage Dashboard
  custom_integrations/virage_dashboard/icon.png
  custom_integrations/virage_dashboard/icon@2x.png
  custom_integrations/virage_dashboard/logo.png
  custom_integrations/virage_dashboard/logo@2x.png
Labels: cla-signed

#2680 Add nvenergy custom integration
  custom_integrations/nvenergy/icon.png
  custom_integrations/nvenergy/icon@2x.png
  custom_integrations/nvenergy/logo.png
  custom_integrations/nvenergy/logo@2x.png
Labels: cla-signed

#2683 Added files for Lay-Z-Spa
  custom_integrations/lay_z_spa/icon.png
  custom_integrations/lay_z_spa/icon@2x.png
  custom_integrations/lay_z_spa/logo.png
  custom_integrations/lay_z_spa/logo@2x.png
Labels: cla-signed

#2682 Add brand images for Trakt TV
  custom_integrations/trakt_tv/icon.png
  custom_integrations/trakt_tv/icon@2x.png
  custom_integrations/trakt_tv/logo.png
  custom_integrations/trakt_tv/logo@2x.png
Labels: cla-signed

#2676 Add assets for xiaomi_viomi integration
  custom_integrations/xiaomi_viomi/icon.png
  custom_integrations/xiaomi_viomi/icon@2x.png
  custom_integrations/xiaomi_viomi/logo.png
  custom_integrations/xiaomi_viomi/logo@2x.png
Labels: cla-signed

#2687 Adding Denon to Custom Integrations
  custom_integrations/denonavr3806/icon.png
  custom_integrations/denonavr3806/icon@2x.png
  custom_integrations/denonavr3806/logo.png
  custom_integrations/denonavr3806/logo@2x.png
Labels: cla-signed

#2681 Add brand images for Nordigen
  custom_integrations/nordigen/icon.png
  custom_integrations/nordigen/icon@2x.png
  custom_integrations/nordigen/logo.png
  custom_integrations/nordigen/logo@2x.png
Labels: cla-signed

#2690 Remove defunct Weather Underground integration
  core_integrations/wunderground/icon.png
  core_integrations/wunderground/icon@2x.png
  core_integrations/wunderground/logo.png
  core_integrations/wunderground/logo@2x.png
Labels: cla-signed, cleanup, has-parent, parent-merged

#2691 Renaming amber_electric => amberelectric to match new plugin name
  custom_integrations/amberelectric/icon.png
  custom_integrations/amberelectric/icon@2x.png
  custom_integrations/amberelectric/logo.png
  custom_integrations/amberelectric/logo@2x.png
Labels: cla-signed

#2688 Add argoclima brand
  custom_integrations/argoclima/icon.png
  custom_integrations/argoclima/logo.png
  custom_integrations/argoclima/logo@2x.png
Labels: cla-signed

#2679 Add new Apple AirPlay Integration
  custom_integrations/apple_airplayer/icon.png
  custom_integrations/apple_airplayer/icon@2x.png
  custom_integrations/apple_airplayer/logo.png
  custom_integrations/apple_airplayer/logo@2x.png
Labels: cla-signed

#2619 add logos and icons for tuya v2 integration
  custom_integrations/tuya_v2/icon.png
  custom_integrations/tuya_v2/icon@2x.png
  custom_integrations/tuya_v2/logo.png
  custom_integrations/tuya_v2/logo@2x.png
Labels: cla-signed

#2695 Add New Peacefair Energy Integration
  custom_integrations/peacefair_energy/icon.png
  custom_integrations/peacefair_energy/icon@2x.png
  custom_integrations/peacefair_energy/logo.png
  custom_integrations/peacefair_energy/logo@2x.png
Labels: cla-signed

#2699 Add whistle(custom integration) icon and logo
  custom_integrations/whistle/icon.png
  custom_integrations/whistle/icon@2x.png
  custom_integrations/whistle/logo.png
  custom_integrations/whistle/logo@2x.png
Labels: cla-signed

#2617 Added icon for custom integration apsystems_ecur
  custom_integrations/apsystems_ecur/icon.png
Labels: cla-signed, in-progress

#2702 add missing icon for the meteo-swiss core integration
  core_integrations/meteo-swiss/icon.png
  core_integrations/meteo-swiss/icon@2x.png
Labels: cla-signed

#2703 Revert "add missing icon for the meteo-swiss core integration (#2702)"
  core_integrations/meteo-swiss/icon.png
  core_integrations/meteo-swiss/icon@2x.png
Labels: cla-signed

#2704 add missing icon for the meteo-swiss custom integration
  custom_integrations/meteo-swiss/icon.png
  custom_integrations/meteo-swiss/icon@2x.png
Labels: cla-signed

#1726 Add generic_hygrostat integration
  core_integrations/generic_hygrostat/icon.png
  core_integrations/generic_hygrostat/icon@2x.png
Labels: awaits-parent, has-parent

#2607 Move Adax to core integration
  core_integrations/adax/icon.png
  core_integrations/adax/icon@2x.png
  core_integrations/adax/logo.png
  core_integrations/adax/logo@2x.png
Labels: cla-signed

#2692 Add xmrpool_stat icon.
  custom_integrations/xmrpool_stat/icon.png
  custom_integrations/xmrpool_stat/icon@2x.png
Labels: cla-signed

#2261 flipr images addition
  core_integrations/flipr/icon.png
  core_integrations/flipr/icon@2x.png
  core_integrations/flipr/logo.png
Labels: awaits-parent, cla-signed, has-parent

#2707 Adds wasteplan_trv brand.
  custom_integrations/wasteplan_trv/icon.png
  custom_integrations/wasteplan_trv/icon@2x.png
  custom_integrations/wasteplan_trv/logo.png
Labels: cla-signed

#1822 Logo and Icon for new Automate integration
  core_integrations/automate/icon.png
  core_integrations/automate/logo.png
  core_integrations/automate/logo@2x.png
Labels: awaits-parent, has-parent

#2708 Adds AL-KO brand.
  custom_integrations/alko/icon.png
  custom_integrations/alko/icon@2x.png
Labels: cla-signed

#2709 Remove automate custom integration, replaced by core
  custom_integrations/automate/icon.png
  custom_integrations/automate/logo.png
  custom_integrations/automate/logo@2x.png
Labels: cla-signed

#2711 Add HiMama
  custom_integrations/hi_mama/icon.png
  custom_integrations/hi_mama/icon@2x.png
Labels: cla-signed

#2713 Xmrig logo
  custom_integrations/xmrig/icon.png
  custom_integrations/xmrig/icon@2x.png
Labels: cla-signed

#2715 Add icons for Neerslag App
  custom_integrations/neerslag/icon.png
  custom_integrations/neerslag/icon@2x.png
Labels: cla-signed

#2716 Added icons for creasoldombus custom component
  custom_integrations/creasoldombus/icon.png
  custom_integrations/creasoldombus/icon@2x.png
Labels: cla-signed, in-progress

#2543 Adds Prosegur
  core_integrations/prosegur/icon.png
  core_integrations/prosegur/icon@2x.png
  core_integrations/prosegur/logo.png
  core_integrations/prosegur/logo@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2717 Remove Garmin Connect integration
  core_integrations/garmin_connect/icon.png
  core_integrations/garmin_connect/icon@2x.png
  core_integrations/garmin_connect/logo.png
  core_integrations/garmin_connect/logo@2x.png
Labels: cla-signed, cleanup

#2719 Add New Duravit Toilet Integration
  custom_integrations/duravit_toilet/icon.png
  custom_integrations/duravit_toilet/icon@2x.png
  custom_integrations/duravit_toilet/logo.png
  custom_integrations/duravit_toilet/logo@2x.png
Labels: cla-signed
