Repository home-assistant/brands, pull requests merged in 2021-10, with the labels that each got.

#2855 Add Linux Battery core integration
  core_integrations/linux_battery/icon.png
  core_integrations/linux_battery/icon@2x.png
  core_integrations/linux_battery/logo.png
  core_integrations/linux_battery/logo@2x.png
Labels: cla-signed, in-progress

#2854 Replace Environment Canada logo
  core_integrations/environment_canada/dark_logo.png
  core_integrations/environment_canada/logo.png
Labels: cla-signed, in-progress

#2858 Add tailwind_iq3 custom integration
  custom_integrations/tailwind_iq3/icon.png
  custom_integrations/tailwind_iq3/icon@2x.png
  custom_integrations/tailwind_iq3/logo.png
  custom_integrations/tailwind_iq3/logo@2x.png
Labels: cla-signed

#2857 add nfl logo
  custom_integrations/nfl/icon.png
  custom_integrations/nfl/icon@2x.png
Labels: cla-signed

#2861 Add BlueAir brand to custom_integrations
  custom_integrations/blueair/icon.png
  custom_integrations/blueair/icon@2x.png
  custom_integrations/blueair/logo.png
  custom_integrations/blueair/logo@2x.png
Labels: cla-signed

#2859 Delete custom integration fritzbox_tools images
  custom_integrations/fritzbox_tools/icon.png
  custom_integrations/fritzbox_tools/icon@2x.png
Labels: cla-signed

#2843 Add brand Reaper DAW
  custom_integrations/reaper/icon.png
  custom_integrations/reaper/icon@2x.png
Labels: cla-signed

#2862 Create symlink for emulated_kasa
  core_integrations/emulated_kasa
Labels: cla-signed

#2860 Remove Essent
  core_integrations/essent/icon.png
  core_integrations/essent/icon@2x.png
  core_integrations/essent/logo.png
  core_integrations/essent/logo@2x.png
Labels: cla-signed, has-parent

#2864 Add Bluesound icons and logos
  core_integrations/bluesound/icon.png
  core_integrations/bluesound/icon@2x.png
  core_integrations/bluesound/logo.png
  core_integrations/bluesound/logo@2x.png
Labels: cla-signed

#2865 Add EverLights icons and logos
  core_integrations/everlights/icon.png
  core_integrations/everlights/icon@2x.png
  core_integrations/everlights/logo.png
  core_integrations/everlights/logo@2x.png
Labels: cla-signed

#2868 Add Intergas Incomfort icons and logos
  core_integrations/incomfort/icon.png
  core_integrations/incomfort/icon@2x.png
  core_integrations/incomfort/logo.png
  core_integrations/incomfort/logo@2x.png
Labels: cla-signed

#2867 Add Graphite icons and logos
  core_integrations/graphite/icon.png
  core_integrations/graphite/icon@2x.png
  core_integrations/graphite/logo.png
  core_integrations/graphite/logo@2x.png
Labels: cla-signed

#2919 pfsense custom integration
  custom_integrations/pfsense/icon.png
  custom_integrations/pfsense/icon@2x.png
  custom_integrations/pfsense/logo.png
  custom_integrations/pfsense/logo@2x.png
Labels: cla-signed

#2921 Add icons and logos for Kef Connector
  custom_integrations/kef_connector/icon.png
  custom_integrations/kef_connector/icon@2x.png
  custom_integrations/kef_connector/logo.png
  custom_integrations/kef_connector/logo@2x.png
Labels: cla-signed, in-progress

#2890 Add branding for Ridwell
  core_integrations/ridwell/icon.png
  core_integrations/ridwell/logo.png
Labels: cla-signed, parent-merged, has-parent

#2922 Add brand Tauron Outages
  custom_integrations/tauron-outages/icon.png
  custom_integrations/tauron-outages/icon@2x.png
  custom_integrations/tauron-outages/logo.png
  custom_integrations/tauron-outages/logo@2x.png
Labels: cla-signed
