Repository home-assistant/brands, pull requests merged in 2021-01, with the labels that each got.

#2131 Remove deprecated PTVSD integration
  core_integrations/ptvsd/icon.png
  core_integrations/ptvsd/icon@2x.png
Labels: awaits-parent, has-parent

#2129 Adds Ondilo icons
  core_integrations/ondilo_ico/icon.png
  core_integrations/ondilo_ico/icon@2x.png
Labels: has-parent

#2133 Add icons for Palazzetti custom integration
  custom_integrations/palazzetti/icon.png
  custom_integrations/palazzetti/icon@2x.png
  custom_integrations/palazzetti/logo.png
  custom_integrations/palazzetti/logo@2x.png
Labels: in-progress

#2144 Add an icon for WorldTidesInfoCustom
  custom_integrations/worldtidesinfocustom/icon.png
  custom_integrations/worldtidesinfocustom/icon@2x.png
  custom_integrations/worldtidesinfocustom/logo.png
  custom_integrations/worldtidesinfocustom/logo@2x.png
Labels: in-progress

#2151 Add zwave_js integration
  core_integrations/zwave_js
Labels: awaits-parent, has-parent

#2156 Create symlink for dhcp
  core_integrations/dhcp
Labels: has-parent

#2132 Add icons for Elasticsearch
  custom_integrations/elasticsearch/icon.png
  custom_integrations/elasticsearch/icon@2x.png
  custom_integrations/elasticsearch/logo.png
  custom_integrations/elasticsearch/logo@2x.png
Labels: in-progress

#2159 Add icons and logos for vivint integration
  custom_integrations/vivint/icon.png
  custom_integrations/vivint/icon@2x.png
  custom_integrations/vivint/logo.png
  custom_integrations/vivint/logo@2x.png
Labels: cla-signed

#2163 🍱 Add eBUSD icon and logo
  core_integrations/ebusd/icon.png
  core_integrations/ebusd/icon@2x.png
  core_integrations/ebusd/logo.png
  core_integrations/ebusd/logo@2x.png
Labels: cla-signed

#2176 brands for kodi-media-sensors added
  custom_integrations/kodi_media_sensors/icon.png
  custom_integrations/kodi_media_sensors/icon@2x.png
  custom_integrations/kodi_media_sensors/logo.png
  custom_integrations/kodi_media_sensors/logo@2x.png
Labels: cla-signed

#2175 🍱 Update QNAP icon and logo
  core_integrations/qnap/icon.png
  core_integrations/qnap/icon@2x.png
  core_integrations/qnap/logo.png
  core_integrations/qnap/logo@2x.png
Labels: cla-signed

#2174 🍱 Add QVR Pro icon
  core_integrations/qvr_pro/icon.png
Labels: cla-signed

#2173 🍱 Add RaspyRFM icon and logo
  core_integrations/raspyrfm/icon.png
  core_integrations/raspyrfm/logo.png
Labels: cla-signed

#2170 🍱 Update Russound Rio icon and logo
  core_integrations/russound_rio/icon.png
  core_integrations/russound_rio/icon@2x.png
  core_integrations/russound_rio/logo.png
  core_integrations/russound_rio/logo@2x.png
Labels: cla-signed

#2172 🍱 Update Russound RNET icon and logo
  core_integrations/russound_rnet/icon.png
  core_integrations/russound_rnet/icon@2x.png
  core_integrations/russound_rnet/logo.png
  core_integrations/russound_rnet/logo@2x.png
Labels: cla-signed

#2168 🍱 Add Serial Particulate Matter icon
  core_integrations/serial_pm/icon.png
Labels: cla-signed

#2167 🍱 Add SkyBeacon icon
  core_integrations/skybeacon/icon.png
Labels: cla-signed

#2177 Replaced gree logos and icons to include transparency.
  core_integrations/gree/icon.png
  core_integrations/gree/icon@2x.png
  core_integrations/gree/logo.png
  core_integrations/gree/logo@2x.png
Labels: cla-signed

#2169 🍱 Add SCSGate icon
  core_integrations/scsgate/icon.png
  core_integrations/scsgate/icon@2x.png
  core_integrations/scsgate/logo.png
  core_integrations/scsgate/logo@2x.png
Labels: cla-signed, in-progress

#2179 🍱 Update Prowl icon and add logo
  core_integrations/prowl/icon.png
  core_integrations/prowl/icon@2x.png
  core_integrations/prowl/logo.png
Labels: cla-signed

#2171 🍱 Add RFLiNK icon
  core_integrations/rflink/icon.png
  core_integrations/rflink/icon@2x.png
  core_integrations/rflink/logo.png
  core_integrations/rflink/logo@2x.png
Labels: cla-signed, in-progress

#2180 🍱 Add PJLink icon and logo
  core_integrations/pjlink/icon.png
  core_integrations/pjlink/icon@2x.png
  core_integrations/pjlink/logo.png
  core_integrations/pjlink/logo@2x.png
Labels: cla-signed

#2182 add Ical
  custom_integrations/ical/icon.png
  custom_integrations/ical/icon@2x.png
Labels: cla-signed

#2118 Added Danfoss Ally icons
  custom_integrations/danfoss_ally/icon.png
  custom_integrations/danfoss_ally/icon@2x.png
Labels: in-progress

#2193 Added icon and logo for ads
  core_integrations/ads/icon.png
  core_integrations/ads/icon@2x.png
  core_integrations/ads/logo.png
  core_integrations/ads/logo@2x.png
Labels: cla-signed

#2192 Replaced coolmaster logo for light background
  core_integrations/coolmaster/logo.png
  core_integrations/coolmaster/logo@2x.png
Labels: cla-signed

#2191 Corrected symlink for luci (OpenWRT)
  core_integrations/luci
Labels: cla-signed

#2190 Replaced dsmr icon and logo
  core_integrations/dsmr/icon.png
  core_integrations/dsmr/icon@2x.png
  core_integrations/dsmr/logo.png
  core_integrations/dsmr/logo@2x.png
Labels: cla-signed

#2189 Replaced somfy_mylink icon and logo with more fitting ones
  core_integrations/somfy_mylink/icon.png
  core_integrations/somfy_mylink/icon@2x.png
  core_integrations/somfy_mylink/logo.png
  core_integrations/somfy_mylink/logo@2x.png
Labels: cla-signed

#2188 Replaced icon and logo for somfy with better quality ones
  core_integrations/somfy/icon.png
  core_integrations/somfy/icon@2x.png
  core_integrations/somfy/logo.png
  core_integrations/somfy/logo@2x.png
Labels: cla-signed

#2187 Added logo and icons for nuimo_controller
  core_integrations/nuimo_controller/icon.png
  core_integrations/nuimo_controller/icon@2x.png
  core_integrations/nuimo_controller/logo.png
Labels: cla-signed

#2186 Updated bmw_connected_drive icons and added logos.
  core_integrations/bmw_connected_drive/icon.png
  core_integrations/bmw_connected_drive/icon@2x.png
  core_integrations/bmw_connected_drive/logo.png
  core_integrations/bmw_connected_drive/logo@2x.png
Labels: cla-signed

#2202 Add viomi logo
  custom_integrations/viomise/icon.png
  custom_integrations/viomise/icon@2x.png
  custom_integrations/viomise/logo.png
  custom_integrations/viomise/logo@2x.png
Labels: cla-signed

#2203 Add ecodevices integration
  custom_integrations/ecodevices/icon.png
  custom_integrations/ecodevices/icon@2x.png
  custom_integrations/ecodevices/logo.png
Labels: cla-signed, in-progress

#2198 Added snmp icon and logo
  core_integrations/snmp/icon.png
Labels: cla-signed

#2197 Added sochain icon and logo
  core_integrations/sochain/icon.png
  core_integrations/sochain/icon@2x.png
  core_integrations/sochain/logo.png
Labels: cla-signed

#2196 Replaced alarmdecoder icon and logo to support light bg
  core_integrations/alarmdecoder/icon.png
  core_integrations/alarmdecoder/icon@2x.png
  core_integrations/alarmdecoder/logo.png
  core_integrations/alarmdecoder/logo@2x.png
Labels: cla-signed

#2195 Replaced aladdin_connect icon and logo to support light bg
  core_integrations/aladdin_connect/icon.png
  core_integrations/aladdin_connect/icon@2x.png
  core_integrations/aladdin_connect/logo.png
  core_integrations/aladdin_connect/logo@2x.png
Labels: cla-signed

#2206 Add icons and logos for balboa integration
  custom_integrations/balboa/icon.png
  custom_integrations/balboa/icon@2x.png
  custom_integrations/balboa/logo.png
  custom_integrations/balboa/logo@2x.png
Labels: cla-signed

#2208 Added icon and logo for bosch_shc custom integration
  custom_integrations/bosch_shc/icon.png
  custom_integrations/bosch_shc/icon@2x.png
  custom_integrations/bosch_shc/logo.png
  custom_integrations/bosch_shc/logo@2x.png
Labels: cla-signed, in-progress

#2210 Add higher quality icons and logos for litterrobot
  custom_integrations/litterrobot/icon.png
  custom_integrations/litterrobot/icon@2x.png
  custom_integrations/litterrobot/logo.png
  custom_integrations/litterrobot/logo@2x.png
Labels: cla-signed

#2023 Add brands for huisbaasje
  core_integrations/huisbaasje/icon.png
  core_integrations/huisbaasje/logo.png
Labels: awaits-parent, has-parent

#2212 Add babybuddy
  custom_integrations/babybuddy/icon.png
  custom_integrations/babybuddy/icon@2x.png
Labels: cla-signed

#2215 Add xiaomi_miot_raw
  custom_integrations/xiaomi_miot_raw/icon.png
  custom_integrations/xiaomi_miot_raw/icon@2x.png
  custom_integrations/xiaomi_miot_raw/logo.png
  custom_integrations/xiaomi_miot_raw/logo@2x.png
Labels: cla-signed

#2214 Added higher quality/corrected images for balboa and vivint
  custom_integrations/balboa/icon.png
  custom_integrations/balboa/icon@2x.png
  custom_integrations/balboa/logo.png
  custom_integrations/balboa/logo@2x.png
  custom_integrations/vivint/icon.png
  custom_integrations/vivint/icon@2x.png
  custom_integrations/vivint/logo.png
  custom_integrations/vivint/logo@2x.png
Labels: cla-signed

#2217 Added AWS Codepipeline icon and logo
  custom_integrations/aws_codepipeline/icon.png
  custom_integrations/aws_codepipeline/icon@2x.png
  custom_integrations/aws_codepipeline/logo.png
  custom_integrations/aws_codepipeline/logo@2x.png
Labels: cla-signed

#2220 Icons and logos of custom integration for teufel_raumfeld
  custom_integrations/teufel_raumfeld/icon.png
  custom_integrations/teufel_raumfeld/icon@2x.png
  custom_integrations/teufel_raumfeld/logo.png
  custom_integrations/teufel_raumfeld/logo@2x.png
Labels: cla-needed

#2223 Add icons for salus custom integration
  custom_integrations/salus/icon.png
  custom_integrations/salus/icon@2x.png
  custom_integrations/salus/logo.png
  custom_integrations/salus/logo@2x.png
Labels: cla-signed
