Repository home-assistant/brands, pull requests merged in 2021-04, with the labels that each got.

#2356 Add Coway icon and logo
  custom_integrations/coway/icon.png
  custom_integrations/coway/icon@2x.png
  custom_integrations/coway/logo.png
  custom_integrations/coway/logo@2x.png
Labels: cla-signed, in-progress

#2380 Add images for PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
  custom_integrations/xiaomi_cloud_map_extractor/icon.png
  custom_integrations/xiaomi_cloud_map_extractor/icon@2x.png
  custom_integrations/xiaomi_cloud_map_extractor/logo.png
  custom_integrations/xiaomi_cloud_map_extractor/logo@2x.png
Labels: cla-signed

#2381 Remove Geizhals integration (ADR-0004)
  core_integrations/geizhals/icon.png
  core_integrations/geizhals/icon@2x.png
  core_integrations/geizhals/logo.png
  core_integrations/geizhals/logo@2x.png
Labels: cla-signed, has-parent

#2370 Brand for Ariston boilers
  custom_integrations/aquaariston/icon.png
  custom_integrations/aquaariston/icon@2x.png
  custom_integrations/aquaariston/logo.png
  custom_integrations/aquaariston/logo@2x.png
  custom_integrations/ariston/icon.png
  custom_integrations/ariston/icon@2x.png
  custom_integrations/ariston/logo.png
  custom_integrations/ariston/logo@2x.png
Labels: cla-signed

#2369 Add brand images for Dahua VTO
  custom_integrations/dahua_vto/icon.png
  custom_integrations/dahua_vto/icon@2x.png
  custom_integrations/dahua_vto/logo.png
  custom_integrations/dahua_vto/logo@2x.png
Labels: cla-signed

#2383 Remove Social Blade integration (ADR-0004)
  core_integrations/socialblade/icon.png
  core_integrations/socialblade/icon@2x.png
  core_integrations/socialblade/logo.png
  core_integrations/socialblade/logo@2x.png
Labels: cla-signed, cleanup, has-parent

#2365 Add emonitor icons
  core_integrations/emonitor/icon.png
  core_integrations/emonitor/icon@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2382 Adding images for openweathermap_all
  custom_integrations/openweathermap_all/icon.png
  custom_integrations/openweathermap_all/icon@2x.png
  custom_integrations/openweathermap_all/logo.png
  custom_integrations/openweathermap_all/logo@2x.png
Labels: cla-signed, in-progress

#2387 Add icons and logo for Netia Player custom integration
  custom_integrations/netia_player/icon.png
  custom_integrations/netia_player/icon@2x.png
  custom_integrations/netia_player/logo.png
  custom_integrations/netia_player/logo@2x.png
Labels: cla-signed

#2388 Added logo & icon for `moscow_pgu` integration
  custom_integrations/moscow_pgu/icon.png
  custom_integrations/moscow_pgu/icon@2x.png
  custom_integrations/moscow_pgu/logo.png
  custom_integrations/moscow_pgu/logo@2x.png
Labels: cla-signed

#2393 Add hebcal icons
  custom_integrations/hebcal/icon.png
  custom_integrations/hebcal/icon@2x.png
Labels: cla-signed, in-progress

#2399 add Luxtronik integration
  custom_integrations/luxtronik/icon.png
  custom_integrations/luxtronik/icon@2x.png
  custom_integrations/luxtronik/logo.png
Labels: cla-signed, in-progress

#2394 Add icons for goecharger integration
  custom_integrations/goecharger/icon.png
  custom_integrations/goecharger/icon@2x.png
  custom_integrations/goecharger/logo.png
  custom_integrations/goecharger/logo@2x.png
Labels: cla-signed

#2396 Add icons for Loxone integration
  custom_integrations/loxone/icon.png
  custom_integrations/loxone/icon@2x.png
  custom_integrations/loxone/logo.png
Labels: cla-signed

#2357 Add motionEye icon
  custom_integrations/motioneye/icon.png
Labels: cla-signed

#2401 Cadsters patch acv icons
  custom_integrations/acv/icon.png
  custom_integrations/acv/icon@2x.png
Labels: cla-signed

#2404 Make ASUSWRT images transparent
  core_integrations/asuswrt/icon.png
  core_integrations/asuswrt/icon@2x.png
  core_integrations/asuswrt/logo.png
  core_integrations/asuswrt/logo@2x.png
Labels: cla-signed

#2406 Add imaprotect images
  custom_integrations/imaprotect/icon.png
  custom_integrations/imaprotect/logo.png
Labels: cla-signed

#2392 Add icons for NameDay integration
  custom_integrations/abalin_nameday/icon.png
  custom_integrations/abalin_nameday/icon@2x.png
Labels: cla-signed

#2410 Icons and logos for ukho_tides
  custom_integrations/ukho_tides/icon.png
  custom_integrations/ukho_tides/logo.png
Labels: cla-signed

#2411 Fix Abode images
  core_integrations/abode/icon.png
  core_integrations/abode/icon@2x.png
  core_integrations/abode/logo.png
  core_integrations/abode/logo@2x.png
Labels: cla-signed

#2424 Added files for Wavin Sentio
  custom_integrations/wavinsentio/icon.png
  custom_integrations/wavinsentio/icon@2x.png
Labels: cla-signed

#2420 Denoise clickatell images
  core_integrations/clickatell/icon.png
  core_integrations/clickatell/icon@2x.png
  core_integrations/clickatell/logo.png
  core_integrations/clickatell/logo@2x.png
Labels: cla-signed

#2416 Update logo for xiaomi_miot_raw
  custom_integrations/xiaomi_miot_raw/logo.png
  custom_integrations/xiaomi_miot_raw/logo@2x.png
Labels: cla-signed

#2421 Denoise climacell images
  core_integrations/climacell/icon.png
  core_integrations/climacell/icon@2x.png
  core_integrations/climacell/logo.png
  core_integrations/climacell/logo@2x.png
Labels: cla-signed

#2418 Make buienradar images transparent
  core_integrations/buienradar/icon.png
  core_integrations/buienradar/icon@2x.png
  core_integrations/buienradar/logo.png
  core_integrations/buienradar/logo@2x.png
Labels: cla-signed

#2422 Make comed logo transparent
  core_integrations/comed_hourly_pricing/logo.png
  core_integrations/comed_hourly_pricing/logo@2x.png
Labels: cla-signed

#2417 Fix white borders around bsblan images
  core_integrations/bsblan/icon.png
  core_integrations/bsblan/icon@2x.png
  core_integrations/bsblan/logo.png
  core_integrations/bsblan/logo@2x.png
Labels: cla-signed

#2419 Make circuit images transparent
  core_integrations/circuit/icon.png
  core_integrations/circuit/icon@2x.png
  core_integrations/circuit/logo.png
  core_integrations/circuit/logo@2x.png
Labels: cla-signed

#2414 Make appletv logo sharper
  core_integrations/apple_tv/logo.png
  core_integrations/apple_tv/logo@2x.png
Labels: cla-signed

#2429 Add icons and logo for NBP custom integration
  custom_integrations/nbp/icon.png
  custom_integrations/nbp/icon@2x.png
  custom_integrations/nbp/logo.png
  custom_integrations/nbp/logo@2x.png
Labels: cla-signed

#2430 add icons for wiffi component
  core_integrations/wiffi/icon.png
  core_integrations/wiffi/icon@2x.png
Labels: cla-signed

#2405 Add images for PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus
  custom_integrations/tauron_amiplus/icon.png
  custom_integrations/tauron_amiplus/icon@2x.png
Labels: cla-signed

#2352 Add pr_custom_component icons
  custom_integrations/pr_custom_component/icon.png
  custom_integrations/pr_custom_component/icon@2x.png
Labels: cla-signed, in-progress

#2432 Add icons for temperature_feels_like custom component
  custom_integrations/temperature_feels_like/icon.png
  custom_integrations/temperature_feels_like/icon@2x.png
Labels: cla-signed

#2433 Add logo and icon for kweather integration
  custom_integrations/kweather/icon.png
  custom_integrations/kweather/logo.png
Labels: cla-signed, in-progress

#2434 cez_outages
  custom_integrations/cez_outages/icon.png
  custom_integrations/cez_outages/icon@2x.png
  custom_integrations/cez_outages/logo.png
Labels: cla-signed

#2436 Add icons for Remote Syslog integration.
  custom_integrations/remote_syslog/icon.png
  custom_integrations/remote_syslog/icon@2x.png
Labels: cla-signed

#2438 Add dialogflow logo
  core_integrations/dialogflow/logo.png
  core_integrations/dialogflow/logo@2x.png
Labels: cla-signed

#2439 Make transparent discord images
  core_integrations/discord/icon.png
  core_integrations/discord/icon@2x.png
  core_integrations/discord/logo.png
  core_integrations/discord/logo@2x.png
Labels: cla-signed

#2437 Remove white borders around danfoss logo
  core_integrations/danfoss_air/logo.png
  core_integrations/danfoss_air/logo@2x.png
Labels: cla-signed

#2441 Remove borders around dublin_bus_transport logo
  core_integrations/dublin_bus_transport/icon.png
  core_integrations/dublin_bus_transport/icon@2x.png
  core_integrations/dublin_bus_transport/logo.png
  core_integrations/dublin_bus_transport/logo@2x.png
Labels: cla-signed

#2442 Make dynalite logo transparent
  core_integrations/dynalite/logo.png
  core_integrations/dynalite/logo@2x.png
Labels: cla-signed

#2440 Make doorbird images sharper
  core_integrations/doorbird/icon.png
  core_integrations/doorbird/icon@2x.png
  core_integrations/doorbird/logo.png
  core_integrations/doorbird/logo@2x.png
Labels: cla-signed

#2443 Add Purrsong icon and logo
  custom_integrations/purrsong/icon.png
  custom_integrations/purrsong/icon@2x.png
  custom_integrations/purrsong/logo.png
  custom_integrations/purrsong/logo@2x.png
Labels: cla-signed

#2446 Fix econet images
  core_integrations/econet/icon.png
  core_integrations/econet/logo.png
Labels: cla-signed

#2447 Make eightsleep logo sharper
  core_integrations/eight_sleep/logo.png
  core_integrations/eight_sleep/logo@2x.png
Labels: cla-signed

#2445 Remove white borders on ebusd images
  core_integrations/ebusd/icon.png
  core_integrations/ebusd/icon@2x.png
  core_integrations/ebusd/logo.png
  core_integrations/ebusd/logo@2x.png
Labels: cla-signed

#2448 Make ephember icons transparent
  core_integrations/ephember/icon.png
  core_integrations/ephember/icon@2x.png
Labels: cla-signed

#2449 Fix ezviz images
  core_integrations/ezviz/icon.png
  core_integrations/ezviz/icon@2x.png
  core_integrations/ezviz/logo.png
  core_integrations/ezviz/logo@2x.png
Labels: cla-signed

#2039 Move ialarm icon to core_integrations
  core_integrations/ialarm/icon.png
Labels: awaits-parent, cla-signed, has-parent

#2458 Fix frontier_silicon logo
  core_integrations/frontier_silicon/logo.png
Labels: cla-signed

#2460 Make flic images transparent
  core_integrations/flic/icon.png
  core_integrations/flic/logo.png
Labels: cla-signed

#2459 Make fleetgo icon transparent
  core_integrations/fleetgo/icon.png
  core_integrations/fleetgo/icon@2x.png
Labels: cla-signed

#2457 Make fortios images transparent
  core_integrations/fortios/icon.png
  core_integrations/fortios/icon@2x.png
  core_integrations/fortios/logo.png
  core_integrations/fortios/logo@2x.png
Labels: cla-signed

#2456 Replace folder icon
  core_integrations/folder/icon.png
  core_integrations/folder/icon@2x.png
Labels: cla-signed

#2455 Replace file icon
  core_integrations/file/icon.png
  core_integrations/file/icon@2x.png
Labels: cla-signed

#2454 Make fibaro icons transparent
  core_integrations/fibaro/icon.png
  core_integrations/fibaro/icon@2x.png
Labels: cla-signed

#2452 Make familyhub icon higher quality
  core_integrations/familyhub/icon.png
Labels: cla-signed

#2451 Add fail2ban hDPI logo
  core_integrations/fail2ban/logo.png
  core_integrations/fail2ban/logo@2x.png
Labels: cla-signed

#2453 Replace feedreader images
  core_integrations/feedreader/icon.png
  core_integrations/feedreader/icon@2x.png
Labels: cla-signed, in-progress

#2450 Fix facebox logo
  core_integrations/facebox/logo.png
Labels: cla-signed

#2462 Use new fitbit logo
  core_integrations/fitbit/icon.png
  core_integrations/fitbit/icon@2x.png
  core_integrations/fitbit/logo.png
  core_integrations/fitbit/logo@2x.png
Labels: cla-signed

#2461 Make flunearyou images transparent
  core_integrations/flunearyou/icon.png
  core_integrations/flunearyou/icon@2x.png
  core_integrations/flunearyou/logo.png
  core_integrations/flunearyou/logo@2x.png
Labels: cla-signed

#2469 Use better quality gtfs icons
  core_integrations/gtfs/icon.png
  core_integrations/gtfs/icon@2x.png
Labels: cla-signed

#2468 Fix garadget icons
  core_integrations/garadget/icon.png
  core_integrations/garadget/icon@2x.png
Labels: cla-signed

#2467 Remove borders around garmin_connect images
  core_integrations/garmin_connect/icon.png
  core_integrations/garmin_connect/icon@2x.png
  core_integrations/garmin_connect/logo.png
  core_integrations/garmin_connect/logo@2x.png
Labels: cla-signed

#2466 Make gios logo transparent
  core_integrations/gios/logo.png
Labels: cla-signed

#2465 Make github icon transparent
  core_integrations/github/icon.png
  core_integrations/github/icon@2x.png
Labels: cla-signed

#2464 Fix geo_rss_events icons
  core_integrations/geo_rss_events/icon.png
  core_integrations/geo_rss_events/icon@2x.png
Labels: cla-signed

#2474 Make html5 icons sharper
  core_integrations/html5/icon.png
  core_integrations/html5/icon@2x.png
Labels: cla-signed

#2473 Make hdmi-cec images sharper
  core_integrations/hdmi-cec/icon.png
  core_integrations/hdmi-cec/icon@2x.png
  core_integrations/hdmi-cec/logo.png
  core_integrations/hdmi-cec/logo@2x.png
Labels: cla-signed

#2472 Make homematicip icon transparent
  core_integrations/homematicip_cloud/icon.png
  core_integrations/homematicip_cloud/icon@2x.png
  core_integrations/homematicip_cloud/logo.png
  core_integrations/homematicip_cloud/logo@2x.png
Labels: cla-signed

#2476 Add brand images for custom integration weenect
  custom_integrations/weenect/icon.png
  custom_integrations/weenect/icon@2x.png
  custom_integrations/weenect/logo.png
  custom_integrations/weenect/logo@2x.png
Labels: cla-signed

#2480 Add icon for multiscrape integration
  custom_integrations/multiscrape/icon.png
Labels: cla-signed

#2475 Added Somnofy icon. Both icon and logo is the same
  custom_integrations/somnofy/icon.png
  custom_integrations/somnofy/icon@2x.png
Labels: cla-signed

#2471 Fix homematic borders around images
  core_integrations/homematic/icon.png
  core_integrations/homematic/icon@2x.png
  core_integrations/homematic/logo.png
  core_integrations/homematic/logo@2x.png
Labels: cla-signed

#2477 Add openHASP custom-component brand icon
  custom_integrations/openhasp/icon.png
  custom_integrations/openhasp/icon@2x.png
Labels: cla-signed

#2486 Make incomfort icon transparent
  core_integrations/incomfort/icon.png
Labels: cla-signed

#2485 Make iammeter icon transparent
  core_integrations/iammeter/icon.png
  core_integrations/iammeter/icon@2x.png
Labels: cla-signed

#2484 Fix insteon images
  core_integrations/insteon/icon.png
  core_integrations/insteon/icon@2x.png
  core_integrations/insteon/logo.png
  core_integrations/insteon/logo@2x.png
Labels: cla-signed

#2492 Add brands for Dataplicity integration
  custom_integrations/dataplicity/icon.png
  custom_integrations/dataplicity/icon@2x.png
  custom_integrations/dataplicity/logo.png
  custom_integrations/dataplicity/logo@2x.png
Labels: cla-signed

#2491 Add brands for GyverLamp integration
  custom_integrations/gyverlamp/icon.png
  custom_integrations/gyverlamp/icon@2x.png
  custom_integrations/gyverlamp/logo.png
  custom_integrations/gyverlamp/logo@2x.png
Labels: cla-signed

#2490 multimatic custom integration
  custom_integrations/multimatic/icon.png
  custom_integrations/multimatic/icon@2x.png
  custom_integrations/multimatic/logo.png
  custom_integrations/multimatic/logo@2x.png
Labels: cla-signed

#2488 Add brands for WebRTC integration
  custom_integrations/webrtc/icon.png
  custom_integrations/webrtc/icon@2x.png
  custom_integrations/webrtc/logo.png
  custom_integrations/webrtc/logo@2x.png
Labels: cla-signed

#2493 Make iperf3 icons sharper
  core_integrations/iperf3/icon.png
  core_integrations/iperf3/icon@2x.png
  core_integrations/iperf3/logo.png
  core_integrations/iperf3/logo@2x.png
Labels: cla-signed

#2494 Make irish_rail_transport logo transparent
  core_integrations/irish_rail_transport/logo.png
  core_integrations/irish_rail_transport/logo@2x.png
Labels: cla-signed

#2495 Fix white borders around iss images
  core_integrations/iss/icon.png
  core_integrations/iss/icon@2x.png
  core_integrations/iss/logo.png
  core_integrations/iss/logo@2x.png
Labels: cla-signed

#2496 Make influxdb logo sharper
  core_integrations/influxdb/icon.png
  core_integrations/influxdb/icon@2x.png
  core_integrations/influxdb/logo.png
  core_integrations/influxdb/logo@2x.png
Labels: cla-signed

#2489 Add brands for YandexStation integration
  custom_integrations/yandex_station/icon.png
  custom_integrations/yandex_station/icon@2x.png
  custom_integrations/yandex_station/logo.png
  custom_integrations/yandex_station/logo@2x.png
Labels: cla-signed, in-progress

#2499 Add gitlab_ci icon
  core_integrations/gitlab_ci/icon.png
  core_integrations/gitlab_ci/icon@2x.png
  core_integrations/gitlab_ci/logo.png
  core_integrations/gitlab_ci/logo@2x.png
Labels: cla-signed

#2502 Make keyboard icon sharper
  core_integrations/keyboard/icon.png
  core_integrations/keyboard/icon@2x.png
Labels: cla-signed

#2504 Remove white lines on keba icon
  core_integrations/keba/icon.png
  core_integrations/keba/icon@2x.png
Labels: cla-signed

#2483 ADD: OpenRGB
  custom_integrations/openrgb/icon.png
  custom_integrations/openrgb/logo.png
Labels: cla-signed, in-progress

#2498 Add iammeter logo
  core_integrations/iammeter/logo.png
Labels: cla-signed

#2500 Add icon and logo for Flair custom integration
  custom_integrations/flair/icon.png
  custom_integrations/flair/icon@2x.png
  custom_integrations/flair/logo.png
  custom_integrations/flair/logo@2x.png
Labels: cla-signed

#2507 shinobi video custom component
  custom_integrations/shinobi/icon.png
  custom_integrations/shinobi/icon@2x.png
Labels: cla-signed

#2509 ADD: exchangerate-api
  custom_integrations/exchangerate-api/icon.png
  custom_integrations/exchangerate-api/logo.png
Labels: cla-signed

#2510 Use better litterrobot images
  core_integrations/litterrobot/icon.png
  core_integrations/litterrobot/icon@2x.png
  core_integrations/litterrobot/logo.png
  core_integrations/litterrobot/logo@2x.png
Labels: cla-signed

#2321 Add Picnic logo icons
  core_integrations/picnic/icon.png
  core_integrations/picnic/icon@2x.png
Labels: awaits-parent, cla-signed, has-parent, parent-merged

#1820 Add logo and icon for new met_eireann integration
  core_integrations/met_eireann/icon.png
  core_integrations/met_eireann/icon@2x.png
  core_integrations/met_eireann/logo.png
Labels: awaits-parent, has-parent, parent-merged

#2514 Move the motioneye icon from custom to core integration
  core_integrations/motioneye/icon.png
Labels: cla-signed, has-parent

#2518 Make llamalab_automate logo sharper
  core_integrations/llamalab_automate/logo.png
Labels: cla-signed

#2517 Make local_file sharper
  core_integrations/local_file/icon.png
  core_integrations/local_file/icon@2x.png
Labels: cla-signed

#2516 Fix white borders around lutron images
  core_integrations/lutron/icon.png
  core_integrations/lutron/icon@2x.png
  core_integrations/lutron/logo.png
  core_integrations/lutron/logo@2x.png
Labels: cla-signed

#2515 Add EthermineInfo custom icons+logo
  custom_integrations/ethermineinfo/icon.png
  custom_integrations/ethermineinfo/icon@2x.png
  custom_integrations/ethermineinfo/logo.png
  custom_integrations/ethermineinfo/logo@2x.png
Labels: cla-signed

#2521 Make mcp23017 logo fully transparent
  core_integrations/mcp23017/logo.png
  core_integrations/mcp23017/logo@2x.png
Labels: cla-signed

#2520 Make fully transparent meteoclimatic icon
  core_integrations/meteoclimatic/icon.png
  core_integrations/meteoclimatic/icon@2x.png
Labels: cla-signed

#2519 Added Mutesync
  core_integrations/mutesync/icon.png
  core_integrations/mutesync/icon@2x.png
Labels: awaits-parent, cla-signed, has-parent

#2522 add brand images for Redfin custom component
  custom_integrations/redfin/icon.png
  custom_integrations/redfin/icon@2x.png
  custom_integrations/redfin/logo.png
  custom_integrations/redfin/logo@2x.png
Labels: cla-signed

#2523 Added aarlo custom integration.
  custom_integrations/aarlo/icon.png
  custom_integrations/aarlo/icon@2x.png
  custom_integrations/aarlo/logo.png
  custom_integrations/aarlo/logo@2x.png
Labels: cla-signed

#2525 Add icons for OpenSprinkler custom integration
  custom_integrations/opensprinkler/icon.png
  custom_integrations/opensprinkler/icon@2x.png
  custom_integrations/opensprinkler/logo.png
  custom_integrations/opensprinkler/logo@2x.png
Labels: cla-signed

#2524 Improve NWS images
  core_integrations/nws/icon.png
  core_integrations/nws/icon@2x.png
  core_integrations/nws/logo.png
Labels: cla-signed

#2527 Add tesla_custom
  custom_integrations/tesla_custom/icon.png
  custom_integrations/tesla_custom/icon@2x.png
  custom_integrations/tesla_custom/logo.png
  custom_integrations/tesla_custom/logo@2x.png
Labels: cla-signed

#2529 Make n26 logo transparent
  core_integrations/n26/logo.png
  core_integrations/n26/logo@2x.png
Labels: cla-signed
