Repository home-assistant/brands, pull requests merged in 2022-09, with the labels that each got.

#3638 Add BlueMaestro integration
  core_integrations/bluemaestro/icon.png
  core_integrations/bluemaestro/icon@2x.png
Labels: cla-signed, parent-merged

#3629 Add icon for flashforge_adventurer_3
  custom_integrations/flashforge_adventurer_3/icon.png
Labels: cla-signed

#3641 Add iammeter_http icons
  custom_integrations/iammeter_http/icon.png
  custom_integrations/iammeter_http/icon@2x.png
  custom_integrations/iammeter_http/logo.png
Labels: cla-signed

#3639 Added Icons and Logos for Evonic Custom Integration
  custom_integrations/evonic/icon.png
  custom_integrations/evonic/icon@2x.png
  custom_integrations/evonic/logo.png
  custom_integrations/evonic/logo@2x.png
Labels: cla-signed

#2603 Move nobo_hub from custom to core integrations
  core_integrations/nobo_hub/icon.png
  core_integrations/nobo_hub/icon@2x.png
  core_integrations/nobo_hub/logo.png
Labels: cla-signed, awaits-parent, has-parent

#3642 Add tilt_ble icons
  core_integrations/tilt_ble/icon.png
  core_integrations/tilt_ble/icon@2x.png
Labels: cla-signed, parent-merged

#3643 add deutschebahn custom integration icon and logo
  custom_integrations/deutschebahn/icon.png
  custom_integrations/deutschebahn/icon@2x.png
  custom_integrations/deutschebahn/logo.png
  custom_integrations/deutschebahn/logo@2x.png
Labels: cla-signed

#3648 Add dark versions for SMHI
  core_integrations/smhi/dark_icon.png
  core_integrations/smhi/dark_icon@2x.png
  core_integrations/smhi/dark_logo.png
  core_integrations/smhi/dark_logo@2x.png
Labels: cla-signed

#3651 Add Switchbee logo
  core_integrations/switchbee/icon.png
  core_integrations/switchbee/icon@2x.png
  core_integrations/switchbee/logo.png
  core_integrations/switchbee/logo@2x.png
Labels: cla-signed, parent-merged, has-parent

#3652 Add chroma custom integration
  custom_integrations/chroma/icon.png
  custom_integrations/chroma/icon@2x.png
  custom_integrations/chroma/logo.png
  custom_integrations/chroma/logo@2x.png
Labels: cla-signed

#3649 ⚡ Add branding for custom integration EVNEX chargers
  custom_integrations/evnex/dark_icon.png
  custom_integrations/evnex/dark_icon@2x.png
  custom_integrations/evnex/dark_logo.png
  custom_integrations/evnex/dark_logo@2x.png
  custom_integrations/evnex/icon.png
  custom_integrations/evnex/icon@2x.png
  custom_integrations/evnex/logo.png
  custom_integrations/evnex/logo@2x.png
Labels: cla-signed

#3646 Add icon for QR-Code-Generator custom integration
  custom_integrations/qr_generator/icon.png
  custom_integrations/qr_generator/icon@2x.png
Labels: cla-signed

#3657 Remove U.S. Citizenship and Immigration Services (USCIS) integration
  core_integrations/uscis/icon.png
  core_integrations/uscis/icon@2x.png
  core_integrations/uscis/logo.png
  core_integrations/uscis/logo@2x.png
Labels: cla-signed, cleanup

#3653 Logo and icon for Redback Technologies
  custom_integrations/redback/icon.png
  custom_integrations/redback/icon@2x.png
  custom_integrations/redback/logo.png
  custom_integrations/redback/logo@2x.png
Labels: cla-signed

#3640 Add Google Drive icons
  core_integrations/google_drive/icon.png
  core_integrations/google_drive/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3634 Added icons and logos for Dolphin custom integration
  custom_integrations/dolphin/icon.png
  custom_integrations/dolphin/icon@2x.png
  custom_integrations/dolphin/logo.png
  custom_integrations/dolphin/logo@2x.png
Labels: cla-signed

#3635 Add images for custom integration "Aquarea Smart Cloud"
  custom_integrations/aquarea/dark_icon.png
  custom_integrations/aquarea/dark_icon@2x.png
  custom_integrations/aquarea/dark_logo.png
  custom_integrations/aquarea/dark_logo@2x.png
  custom_integrations/aquarea/icon.png
  custom_integrations/aquarea/icon@2x.png
  custom_integrations/aquarea/logo.png
  custom_integrations/aquarea/logo@2x.png
Labels: cla-signed

#3637 Add icon and logo for custom component met_next_6_hours_forecast
  custom_integrations/met_next_6_hours_forecast/icon.png
  custom_integrations/met_next_6_hours_forecast/icon@2x.png
  custom_integrations/met_next_6_hours_forecast/logo.png
  custom_integrations/met_next_6_hours_forecast/logo@2x.png
Labels: cla-signed

#3647 Adds Rointe Heaters icons
  custom_integrations/rointe/icon.png
  custom_integrations/rointe/icon@2x.png
  custom_integrations/rointe/logo.png
  custom_integrations/rointe/logo@2x.png
Labels: cla-signed, in-progress

#3665 Add icon and logo for apcupsd.
  core_integrations/apcupsd/icon.png
  core_integrations/apcupsd/icon@2x.png
  core_integrations/apcupsd/logo.png
  core_integrations/apcupsd/logo@2x.png
Labels: cla-signed

#3668 Add icon for Kostal Plenticore Solar Inverter
  core_integrations/kostal_plenticore/icon.png
  core_integrations/kostal_plenticore/icon@2x.png
Labels: cla-signed

#3661 Add Places Icons
  custom_integrations/places/icon.png
  custom_integrations/places/icon@2x.png
Labels: cla-signed

#3660 icons for facebook_messenger custom integration
  custom_integrations/facebook_messenger/icon.png
  custom_integrations/facebook_messenger/icon@2x.png
Labels: cla-signed

#3519 Add icon for raspberry_pi hardware integration
  core_integrations/raspberry_pi
Labels: cla-signed

#3605 Add images for custom integration MyWaterToronto
  custom_integrations/mywatertoronto/icon.png
  custom_integrations/mywatertoronto/icon@2x.png
  custom_integrations/mywatertoronto/logo.png
  custom_integrations/mywatertoronto/logo@2x.png
Labels: cla-signed

#3631 Add brand for eight_sleep_climate
  custom_integrations/eight_sleep_climate/icon.png
  custom_integrations/eight_sleep_climate/icon@2x.png
  custom_integrations/eight_sleep_climate/logo.png
  custom_integrations/eight_sleep_climate/logo@2x.png
Labels: cla-signed

#3633 Added icons for Atrea custom integration
  custom_integrations/atrea/icon.png
  custom_integrations/atrea/icon@2x.png
  custom_integrations/atrea/logo.png
  custom_integrations/atrea/logo@2x.png
Labels: cla-signed, in-progress

#3159 Add Lidarr icons
  core_integrations/lidarr/icon.png
  core_integrations/lidarr/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3670 Add iBeacon integration
  core_integrations/ibeacon/logo.png
  core_integrations/ibeacon/logo@2x.png
Labels: cla-signed

#3671 Adding icons/logos for new savantaudio-homeassistant HACS component
  custom_integrations/savantaudio/icon.png
  custom_integrations/savantaudio/icon@2x.png
  custom_integrations/savantaudio/logo.png
  custom_integrations/savantaudio/logo@2x.png
Labels: cla-signed

#3667 Icon for a device tracker based on ZTE router
  custom_integrations/zte_tracker/icon.png
Labels: cla-signed, in-progress

#3672 Added images for Nordpool custom integration
  custom_integrations/nordpool/icon.png
  custom_integrations/nordpool/icon@2x.png
  custom_integrations/nordpool/logo.png
  custom_integrations/nordpool/logo@2x.png
Labels: cla-signed

#3662 Remove branding for deprecated Flu Near You integration
  core_integrations/flunearyou/icon.png
  core_integrations/flunearyou/icon@2x.png
  core_integrations/flunearyou/logo.png
  core_integrations/flunearyou/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3585 Add keymitt_ble icons
  core_integrations/keymitt_ble/icon.png
  core_integrations/keymitt_ble/logo.png
Labels: cla-signed, awaits-parent, has-parent, in-progress

#3663 Kegtron icons and logo
  core_integrations/kegtron/icon.png
  core_integrations/kegtron/icon@2x.png
  core_integrations/kegtron/logo.png
  core_integrations/kegtron/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3673 Added cool_open_integration icons, for custom integration for coolmaster
  custom_integrations/cool_open_integration/icon.png
  custom_integrations/cool_open_integration/icon@2x.png
  custom_integrations/cool_open_integration/logo.png
  custom_integrations/cool_open_integration/logo@2x.png
Labels: cla-signed

#3659 Add nibe_heatpump
  core_integrations/nibe_heatpump/icon.png
  core_integrations/nibe_heatpump/icon@2x.png
  core_integrations/nibe_heatpump/logo.png
  core_integrations/nibe_heatpump/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3675 Added icons for teamtracker custom configuration.
  custom_integrations/teamtracker/icon.png
  custom_integrations/teamtracker/icon@2x.png
  custom_integrations/teamtracker/logo.png
  custom_integrations/teamtracker/logo@2x.png
Labels: in-progress

#3686 Add icon for new custom integration mydolphin_plus
  custom_integrations/mydolphin_plus/icon.png
Labels: in-progress

#3689 Add Google Sheets icons
  core_integrations/google_sheets/icon.png
  core_integrations/google_sheets/icon@2x.png
Labels: has-parent

#3691 Add Pixie Plus icon and logo to custom integrations
  custom_integrations/pixie_plus/icon.png
  custom_integrations/pixie_plus/icon@2x.png
  custom_integrations/pixie_plus/logo.png
Labels: in-progress

#3711 Add Third Reality as a brand
  core_brands/third_reality/dark_icon.png
  core_brands/third_reality/dark_icon@2x.png
  core_brands/third_reality/icon.png
  core_brands/third_reality/icon@2x.png
  core_brands/third_reality/logo@2x.png
Labels: parent-merged
