Repository home-assistant/brands, pull requests merged in 2022-12, with the labels that each got.

#3875 Add branding images for Schlage locks
  custom_integrations/schlage/icon.png
  custom_integrations/schlage/icon@2x.png
  custom_integrations/schlage/logo.png
  custom_integrations/schlage/logo@2x.png
Labels: in-progress

#3917 Rename kingspan_connect to kingspan_watchman_sensit
  custom_integrations/kingspan_watchman_sensit/icon.png
  custom_integrations/kingspan_watchman_sensit/logo.png
Labels: in-progress

#3920 Add ab_gateway logos
  custom_integrations/ab_gateway/icon.png
  custom_integrations/ab_gateway/icon@2x.png
  custom_integrations/ab_gateway/logo.png
  custom_integrations/ab_gateway/logo@2x.png
Labels: in-progress

#3750 Add branding for AirVisual Pro
  core_brands/airvisual/icon.png
  core_brands/airvisual/logo.png
  core_brands/airvisual/logo@2x.png
  core_integrations/airvisual
  core_integrations/airvisual_pro
Labels: parent-merged, Hacktoberfest, has-parent, hacktoberfest-accepted

#3857 Add branding for PurpleAir
  core_integrations/purpleair/icon.png
  core_integrations/purpleair/icon@2x.png
Labels: awaits-parent, has-parent

#3927 Add logo for octopus_intelligent
  custom_integrations/octopus_intelligent/icon.png
  custom_integrations/octopus_intelligent/icon@2x.png
Labels: in-progress

#3926 Added panasonic_eolia images
  custom_integrations/panasonic_eolia/icon.png
  custom_integrations/panasonic_eolia/icon@2x.png
  custom_integrations/panasonic_eolia/logo.png
  custom_integrations/panasonic_eolia/logo@2x.png
Labels: in-progress

#3935 Add icon and logo for AsusWrt custom integration
  custom_integrations/asuswrt_custom/dark_logo.png
  custom_integrations/asuswrt_custom/dark_logo@2x.png
  custom_integrations/asuswrt_custom/icon.png
  custom_integrations/asuswrt_custom/icon@2x.png
  custom_integrations/asuswrt_custom/logo.png
  custom_integrations/asuswrt_custom/logo@2x.png
Labels: in-progress

#3930 Add Hypervolt Charger
  custom_integrations/hypervolt_charger/icon.png
  custom_integrations/hypervolt_charger/icon@2x.png
  custom_integrations/hypervolt_charger/logo.png
Labels: in-progress

#3915 Added icons for SAJ eSolar Air based on saj_esolar
  custom_integrations/saj_esolar_air/icon.png
  custom_integrations/saj_esolar_air/icon@2x.png
  custom_integrations/saj_esolar_air/logo.png
  custom_integrations/saj_esolar_air/logo@2x.png
Labels: in-progress

#3947 Remove Deutsche Bahn integration
  core_integrations/deutsche_bahn/icon.png
  core_integrations/deutsche_bahn/icon@2x.png
  core_integrations/deutsche_bahn/logo.png
  core_integrations/deutsche_bahn/logo@2x.png
Labels: parent-merged, cleanup, has-parent

#3956 Add posten
  custom_integrations/posten/icon.png
  custom_integrations/posten/icon@2x.png
  custom_integrations/posten/logo.png
Labels: in-progress

#3965 Add reolink icons
  core_integrations/reolink/icon.png
  core_integrations/reolink/icon@2x.png
  core_integrations/reolink/logo.png
  core_integrations/reolink/logo@2x.png
Labels: parent-merged

#3865 Add logo and icon for the google_assistant_sdk integration
  core_integrations/google_assistant_sdk
Labels: parent-merged, awaits-parent, has-parent

#3961 Copy Casambi logo for bluetooth based integration
  custom_integrations/casambi_bt/icon.png
  custom_integrations/casambi_bt/icon@2x.png
  custom_integrations/casambi_bt/logo.png
  custom_integrations/casambi_bt/logo@2x.png
Labels: in-progress

#3975 Add SFR Box icons
  core_integrations/sfr_box/icon.png
  core_integrations/sfr_box/icon@2x.png
Labels: parent-merged, has-parent

#3983 ESA NASK icon
  custom_integrations/esa_nask/icon.png
  custom_integrations/esa_nask/icon@2x.png
Labels: in-progress
