Repository home-assistant/brands, pull requests merged in 2022-07, with the labels that each got.

#3494 Add NextDNS images
  core_integrations/nextdns/icon.png
  core_integrations/nextdns/icon@2x.png
  core_integrations/nextdns/logo.png
Labels: cla-signed, has-parent

#3504 Add fallback for dark hardware image
  scripts/build.sh
Labels: cla-signed

#3502 Add (my) LINE Notify logo and icon.
  custom_integrations/boy_notify_line/icon.png
  custom_integrations/boy_notify_line/icon@2x.png
  custom_integrations/boy_notify_line/logo.png
  custom_integrations/boy_notify_line/logo@2x.png
Labels: cla-signed, in-progress

#3507 Add dependabot
  .github/dependabot.yml
Labels: cla-signed

#3511 Upload RPI 4 Board as PNG
  hardware/boards/raspberry_pi_4.jpg
  hardware/boards/raspberry_pi_4.png
Labels: cla-signed

#3512 Fix tts MDI icons
  core_integrations/conversation/icon.txt
  core_integrations/tts/icon.txt
Labels: cla-signed

#3514 Add new custom integration scinan_thermostat
  custom_integrations/scinan_thermostat/icon.png
  custom_integrations/scinan_thermostat/icon@2x.png
Labels: cla-signed

#3516 Add bluetooth icon
  core_integrations/bluetooth/icon.txt
Labels: cla-signed

#3517 Add `coct_loadshedding` custom integration images
  custom_integrations/coct_loadshedding/icon.png
  custom_integrations/coct_loadshedding/icon@2x.png
  custom_integrations/coct_loadshedding/logo.png
  custom_integrations/coct_loadshedding/logo@2x.png
Labels: cla-error

#3518 Add missing icons for hardware and application_credentials internal integrations
  core_integrations/application_credentials/icon.txt
  core_integrations/hardware/icon.txt
Labels: cla-signed

#3524 Add powerdns integration
  custom_integrations/pdns/icon.png
  custom_integrations/pdns/icon@2x.png
  custom_integrations/pdns/logo.png
  custom_integrations/pdns/logo@2x.png
Labels: cla-signed

#3523 Add synology virtual machine
  custom_integrations/synology_vmm/dark_logo.png
  custom_integrations/synology_vmm/dark_logo@2x.png
  custom_integrations/synology_vmm/icon.png
  custom_integrations/synology_vmm/icon@2x.png
  custom_integrations/synology_vmm/logo.png
  custom_integrations/synology_vmm/logo@2x.png
Labels: cla-signed

#3526 Add brand files for Art-net protocol
  custom_integrations/artnet_led/icon.png
  custom_integrations/artnet_led/icon@2x.png
Labels: cla-signed

#3501 Add brand files for nad_controller
  custom_integrations/nad_controller/icon.png
  custom_integrations/nad_controller/icon@2x.png
Labels: cla-signed

#3528 Add icons for heweather custom integration
  custom_integrations/heweather/icon.png
  custom_integrations/heweather/icon@2x.png
  custom_integrations/heweather/logo.png
  custom_integrations/heweather/logo@2x.png
Labels: cla-signed

#3530 Add logo files for virginmedia_tv
  custom_integrations/virginmedia_tv/logo.png
  custom_integrations/virginmedia_tv/logo@2x.png
Labels: cla-signed

#3527 Add icons for custom integration `cecotec_conga`
  custom_integrations/cecotec_conga/icon.png
  custom_integrations/cecotec_conga/icon@2x.png
Labels: cla-signed

#3533 Add bull icon and logo
  custom_integrations/bull/icon.png
  custom_integrations/bull/icon@2x.png
  custom_integrations/bull/logo.png
  custom_integrations/bull/logo@2x.png
Labels: cla-signed

#3532 Add alfen icon and logo
  custom_integrations/alfen/icon.png
  custom_integrations/alfen/icon@2x.png
  custom_integrations/alfen/logo.png
  custom_integrations/alfen/logo@2x.png
Labels: cla-signed

#3534 Add two custom integrations icons sets
  custom_integrations/reolink_discovery/icon.png
  custom_integrations/reolink_discovery/icon@2x.png
  custom_integrations/reolink_discovery/logo.png
  custom_integrations/reolink_discovery/logo@2x.png
  custom_integrations/reolink_rest/icon.png
  custom_integrations/reolink_rest/icon@2x.png
  custom_integrations/reolink_rest/logo.png
  custom_integrations/reolink_rest/logo@2x.png
Labels: cla-signed

#3536 Add icon and logo for custom integration appwash
  custom_integrations/appwash/icon.png
  custom_integrations/appwash/icon@2x.png
  custom_integrations/appwash/logo.png
  custom_integrations/appwash/logo@2x.png
Labels: cla-signed

#3535 Add icons for cust integration - sodexo_dla_ciebie
  custom_integrations/sodexo_dla_ciebie/icon.png
  custom_integrations/sodexo_dla_ciebie/icon@2x.png
  custom_integrations/sodexo_dla_ciebie/logo.png
  custom_integrations/sodexo_dla_ciebie/logo@2x.png
Labels: cla-signed, in-progress

#3538 Update Pentair ScreenLogic Integration to add Dark Mode Icon
  core_integrations/screenlogic/dark_icon.png
  core_integrations/screenlogic/dark_icon@2x.png
  core_integrations/screenlogic/dark_logo.png
Labels: cla-signed

#3541 Remove SoChain integration
  core_integrations/sochain/icon.png
  core_integrations/sochain/icon@2x.png
  core_integrations/sochain/logo.png
Labels: cla-signed, cleanup, has-parent

#3542 Remove Google Play Music Desktop Player (GPMDP) integration
  core_integrations/gpmdp/icon.png
  core_integrations/gpmdp/icon@2x.png
  core_integrations/gpmdp/logo.png
Labels: cla-signed

#3544 Rename custom brand alfen to alfen_wallbox
  custom_integrations/alfen_wallbox/icon.png
  custom_integrations/alfen_wallbox/icon@2x.png
  custom_integrations/alfen_wallbox/logo.png
  custom_integrations/alfen_wallbox/logo@2x.png
Labels: cla-signed, in-progress

#3543 Add SensorPush images
  core_integrations/sensorpush/logo.png
  core_integrations/sensorpush/logo@2x.png
Labels: cla-signed, parent-merged, has-parent

#3551 Add icon and logo for custom integration vyos
  custom_integrations/vyos/icon.png
  custom_integrations/vyos/icon@2x.png
  custom_integrations/vyos/logo.png
  custom_integrations/vyos/logo@2x.png
Labels: cla-signed

#3550 Add brand images for intex_spa
  custom_integrations/intex_spa/icon.png
  custom_integrations/intex_spa/icon@2x.png
  custom_integrations/intex_spa/logo.png
  custom_integrations/intex_spa/logo@2x.png
Labels: cla-signed, cla-error

#3549 Add moat integration
  core_integrations/moat/icon.png
  core_integrations/moat/icon@2x.png
Labels: cla-signed, parent-merged

#3548 Add logos for govee_ble
  core_integrations/govee_ble/icon.png
  core_integrations/govee_ble/icon@2x.png
  core_integrations/govee_ble/logo.png
  core_integrations/govee_ble/logo@2x.png
Labels: cla-signed, parent-merged

#3547 Add xiaomi_ble images
  core_integrations/xiaomi_ble
Labels: cla-signed

#3545 Add images for Sutro custom integration
  custom_integrations/sutro/icon.png
  custom_integrations/sutro/icon@2x.png
  custom_integrations/sutro/logo.png
  custom_integrations/sutro/logo@2x.png
Labels: cla-signed

#3546 Add inkbird integration
  core_integrations/inkbird/icon.png
  core_integrations/inkbird/icon@2x.png
Labels: cla-signed, parent-merged

#3505 add new custom integration icons - `andrzejchm/ha_tedee_lock`
  custom_integrations/ha_tedee_lock/logo.png
  custom_integrations/ha_tedee_lock/logo@2x.png
Labels: cla-signed

#3554 Add Apex Brand Images
  custom_integrations/apex/dark_logo.png
  custom_integrations/apex/dark_logo@2x.png
  custom_integrations/apex/icon.png
  custom_integrations/apex/icon@2x.png
  custom_integrations/apex/logo.png
  custom_integrations/apex/logo@2x.png
Labels: cla-signed, in-progress

#3553 robonomics integration icon
  custom_integrations/robonomics/icon.png
Labels: cla-signed

#3555 Remove miflora integration
  core_integrations/miflora
Labels: cla-signed

#3556 Remove Xiaomi Mijia BLE Temperature and Humidity Sensor
  core_integrations/mitemp_bt
Labels: cla-signed, cleanup, has-parent

#3559 change System health icon
  core_integrations/system_health/icon.txt
Labels: cla-signed

#3560 Add homeassistant_alerts icon
  core_integrations/homeassistant_alerts/icon.txt
Labels: cla-signed

#3561 Add Scheider icon/logo for PowerTag Gateway integration
  custom_integrations/powertag_gateway/icon.png
  custom_integrations/powertag_gateway/icon@2x.png
  custom_integrations/powertag_gateway/logo.png
  custom_integrations/powertag_gateway/logo@2x.png
Labels: cla-signed
