Repository home-assistant/brands, pull requests merged in 2022-01, with the labels that each got.

#3045 Add SONOS logo for dark mode
  core_integrations/sonos/dark_logo.png
  core_integrations/sonos/dark_logo@2x.png
Labels: cla-signed

#3042 Added branding for Bobcat
  custom_integrations/bobcatminer/icon.png
  custom_integrations/bobcatminer/icon@2x.png
Labels: cla-signed

#3050 Dell printer
  custom_integrations/dell_printer/icon.png
  custom_integrations/dell_printer/icon@2x.png
Labels: cla-signed

#3040 Add icons for LG Hombot custom component
  custom_integrations/lg_hombot/icon.png
  custom_integrations/lg_hombot/icon@2x.png
  custom_integrations/lg_hombot/logo.png
  custom_integrations/lg_hombot/logo@2x.png
Labels: cla-signed

#3044 Add oncue brand icons
  core_integrations/oncue/icon.png
  core_integrations/oncue/icon@2x.png
Labels: cla-signed, has-parent

#3052 New SONOS icon background color
  core_integrations/sonos/icon.png
  core_integrations/sonos/icon@2x.png
Labels: cla-signed

#3051 Fix SONOS logos
  core_integrations/sonos/dark_logo.png
  core_integrations/sonos/dark_logo@2x.png
  core_integrations/sonos/logo.png
  core_integrations/sonos/logo@2x.png
Labels: cla-signed

#3053 add logos
  custom_integrations/dell_printer/logo.png
  custom_integrations/dell_printer/logo@2x.png
Labels: cla-signed

#3037 Update Icon For Total Energies
  custom_integrations/keyatome/icon.png
  custom_integrations/keyatome/icon@2x.png
  custom_integrations/keyatome/logo.png
  custom_integrations/keyatome/logo@2x.png
Labels: cla-signed

#3038 Loqed custom integration
  custom_integrations/loqed/icon.png
  custom_integrations/loqed/icon@2x.png
  custom_integrations/loqed/logo.png
  custom_integrations/loqed/logo@2x.png
Labels: cla-signed

#3043 Add icons for custom_component: Auto Areas
  custom_integrations/auto_areas/icon.png
  custom_integrations/auto_areas/icon@2x.png
Labels: cla-signed

#3039 Add logo for zha_custom
  custom_integrations/zha_custom/icon.png
  custom_integrations/zha_custom/icon@2x.png
Labels: cla-signed

#3047 Add icons/logos for Dyson local
  custom_integrations/dyson_local/dark_icon.png
  custom_integrations/dyson_local/dark_icon@2x.png
  custom_integrations/dyson_local/dark_logo.png
  custom_integrations/dyson_local/dark_logo@2x.png
  custom_integrations/dyson_local/icon.png
  custom_integrations/dyson_local/icon@2x.png
  custom_integrations/dyson_local/logo.png
  custom_integrations/dyson_local/logo@2x.png
Labels: cla-signed

#3032 Icons prepared for dark mode
  custom_integrations/fireservicerota/dark_icon.png
  custom_integrations/fireservicerota/dark_icon@2x.png
  custom_integrations/fireservicerota/dark_logo.png
  custom_integrations/fireservicerota/dark_logo@2x.png
Labels: cla-signed

#2962 Add brand icons for rtsp_to_webrtc
  core_integrations/rtsp_to_webrtc/icon.png
  core_integrations/rtsp_to_webrtc/icon@2x.png
  core_integrations/rtsp_to_webrtc/logo.png
  core_integrations/rtsp_to_webrtc/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3014 Add input_button
  core_integrations/input_button
Labels: cla-signed, parent-merged

#3055 Dark mode icons and logos for ESPhome
  core_integrations/esphome/dark_icon.png
  core_integrations/esphome/dark_icon@2x.png
  core_integrations/esphome/dark_logo.png
  core_integrations/esphome/dark_logo@2x.png
Labels: cla-signed

#3056 xplora_watch
  custom_integrations/xplora_watch/icon.png
  custom_integrations/xplora_watch/icon@2x.png
  custom_integrations/xplora_watch/logo.png
  custom_integrations/xplora_watch/logo@2x.png
Labels: cla-signed

#3057 Add logos & icon for Homematic(IP) Local
  custom_integrations/hahm/dark_logo.png
  custom_integrations/hahm/dark_logo@2x.png
  custom_integrations/hahm/icon.png
  custom_integrations/hahm/icon@2x.png
  custom_integrations/hahm/logo.png
  custom_integrations/hahm/logo@2x.png
Labels: cla-signed

#3058 Light dark mode icon for neerslag
  custom_integrations/neerslag/dark_icon.png
  custom_integrations/neerslag/dark_icon@2x.png
Labels: cla-signed

#3060 Move fireservicerota files from custom to core_integrations
  core_integrations/fireservicerota/dark_icon.png
  core_integrations/fireservicerota/dark_icon@2x.png
  core_integrations/fireservicerota/dark_logo.png
  core_integrations/fireservicerota/dark_logo@2x.png
  core_integrations/fireservicerota/icon.png
  core_integrations/fireservicerota/icon@2x.png
  core_integrations/fireservicerota/logo.png
  core_integrations/fireservicerota/logo@2x.png
Labels: cla-signed

#3059 These icons are optimised for dark mode
  core_integrations/dsmr/dark_icon.png
  core_integrations/dsmr/dark_icon@2x.png
  core_integrations/dsmr/dark_logo.png
  core_integrations/dsmr/dark_logo@2x.png
Labels: cla-signed

#3029 Made background transparent
  core_integrations/hue/icon.png
  core_integrations/hue/icon@2x.png
Labels: cla-signed, in-progress

#3062 Remove deprecated Arduino integration
  core_integrations/arduino/icon.png
  core_integrations/arduino/icon@2x.png
  core_integrations/arduino/logo.png
  core_integrations/arduino/logo@2x.png
Labels: cla-signed, cleanup, has-parent

#3067 Update Cast icons
  core_integrations/cast/icon.png
  core_integrations/cast/icon@2x.png
Labels: cla-signed

#3066 update IFTTT logo
  core_integrations/ifttt/dark_icon.png
  core_integrations/ifttt/dark_icon@2x.png
  core_integrations/ifttt/dark_logo.png
  core_integrations/ifttt/dark_logo@2x.png
  core_integrations/ifttt/icon.png
  core_integrations/ifttt/icon@2x.png
  core_integrations/ifttt/logo.png
  core_integrations/ifttt/logo@2x.png
Labels: cla-signed

#3065 Update xbox logo
  core_integrations/xbox/icon.png
  core_integrations/xbox/icon@2x.png
  core_integrations/xbox/logo.png
  core_integrations/xbox/logo@2x.png
Labels: cla-signed

#3063 Update Yeelight logo
  core_integrations/yeelight/icon.png
  core_integrations/yeelight/icon@2x.png
  core_integrations/yeelight/logo.png
  core_integrations/yeelight/logo@2x.png
Labels: cla-signed

#3064 Speedtest - add dark logos and icons
  core_integrations/speedtestdotnet/dark_icon.png
  core_integrations/speedtestdotnet/dark_icon@2x.png
  core_integrations/speedtestdotnet/dark_logo.png
  core_integrations/speedtestdotnet/dark_logo@2x.png
Labels: cla-signed

#2914 Move Goodwe from custom to core
  core_integrations/goodwe/icon.png
  core_integrations/goodwe/icon@2x.png
  core_integrations/goodwe/logo.png
  core_integrations/goodwe/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent, hacktoberfest-accepted

#3069 add xcomfort logo and icon
  custom_integrations/xcomfort/icon.png
  custom_integrations/xcomfort/icon@2x.png
  custom_integrations/xcomfort/logo.png
  custom_integrations/xcomfort/logo@2x.png
Labels: cla-signed

#3070 Complete icon set for new integration MI
  custom_integrations/moving_intelligence/dark_logo.png
  custom_integrations/moving_intelligence/dark_logo@2x.png
  custom_integrations/moving_intelligence/icon.png
  custom_integrations/moving_intelligence/icon@2x.png
  custom_integrations/moving_intelligence/logo.png
  custom_integrations/moving_intelligence/logo@2x.png
Labels: cla-signed

#3054 Add steamist integration
  core_integrations/steamist/icon.png
  core_integrations/steamist/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3076 Update Synology brand icons and logos, including dark theme
  core_integrations/synology/dark_logo.png
  core_integrations/synology/dark_logo@2x.png
  core_integrations/synology/icon.png
  core_integrations/synology/icon@2x.png
  core_integrations/synology/logo.png
  core_integrations/synology/logo@2x.png
Labels: cla-signed

#3073 Icons of Heinrich-Hertz-Schule, Hamburg
  custom_integrations/hhs_vertretungsplan/icon.png
  custom_integrations/hhs_vertretungsplan/icon@2x.png
Labels: cla-signed

#3078 Add pid_controller
  custom_integrations/pid_controller/icon.png
  custom_integrations/pid_controller/icon@2x.png
Labels: cla-signed, in-progress

#3034 Move SenseME integration to core
  core_integrations/senseme/icon.png
  core_integrations/senseme/icon@2x.png
  core_integrations/senseme/logo.png
  core_integrations/senseme/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3080 Added icons for Samsung MDC custom integration
  custom_integrations/samsungmdc/icon.png
  custom_integrations/samsungmdc/icon@2x.png
  custom_integrations/samsungmdc/logo.png
  custom_integrations/samsungmdc/logo@2x.png
Labels: cla-signed

#3083 Fix ESPHome dark icons and logos
  core_integrations/esphome/dark_icon.png
  core_integrations/esphome/dark_icon@2x.png
  core_integrations/esphome/dark_logo.png
  core_integrations/esphome/dark_logo@2x.png
Labels: cla-signed

#3082 Add icons and logos for SmartRent custom integration
  custom_integrations/smartrent/icon.png
  custom_integrations/smartrent/icon@2x.png
  custom_integrations/smartrent/logo.png
  custom_integrations/smartrent/logo@2x.png
Labels: cla-signed

#3085 Remove ee_brightbox integration
  core_integrations/ee_brightbox/icon.png
  core_integrations/ee_brightbox/icon@2x.png
  core_integrations/ee_brightbox/logo.png
  core_integrations/ee_brightbox/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2798 Move homewizard_energy brand from 'custom' to 'core'
  core_integrations/homewizard/icon.png
  core_integrations/homewizard/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3088 Add dark mode images to lutron
  core_integrations/lutron/dark_icon.png
  core_integrations/lutron/dark_icon@2x.png
  core_integrations/lutron/dark_logo.png
  core_integrations/lutron/dark_logo@2x.png
Labels: cla-signed

#3071 add icon and logo for kilink custom integration
  custom_integrations/kilink/icon.png
  custom_integrations/kilink/icon@2x.png
Labels: in-progress, cla-error

#3086 Add UI Lovelace Minimalist Custom Integration
  custom_integrations/ui_lovelace_minimalist/icon.png
  custom_integrations/ui_lovelace_minimalist/icon@2x.png
  custom_integrations/ui_lovelace_minimalist/logo.png
  custom_integrations/ui_lovelace_minimalist/logo@2x.png
Labels: cla-signed

#3090 Add NHL logo for Custom Integration
  custom_integrations/nhl/icon.png
  custom_integrations/nhl/icon@2x.png
Labels: cla-signed

#3072 added dark theme variants
  custom_integrations/nuki_ng/dark_icon.png
  custom_integrations/nuki_ng/dark_icon@2x.png
  custom_integrations/nuki_ng/dark_logo.png
  custom_integrations/nuki_ng/dark_logo@2x.png
Labels: cla-signed

#3091 Add icon and logo for Rademacher HomePilot custom integration
  custom_integrations/rademacher/dark_logo.png
  custom_integrations/rademacher/dark_logo@2x.png
  custom_integrations/rademacher/icon.png
  custom_integrations/rademacher/icon@2x.png
  custom_integrations/rademacher/logo.png
  custom_integrations/rademacher/logo@2x.png
Labels: cla-signed

#3079 Add logo for vaddio_conferenceshot custom integration
  custom_integrations/vaddio_conferenceshot/logo.png
Labels: cla-signed

#3096 Add dark variants to github
  core_integrations/github/dark_icon.png
  core_integrations/github/dark_icon@2x.png
  core_integrations/github/dark_logo.png
  core_integrations/github/dark_logo@2x.png
Labels: cla-signed

#3095 holidays custom integration
  custom_integrations/holidays/icon.png
  custom_integrations/holidays/icon@2x.png
Labels: cla-signed

#3094 add nicehash excavator integration icon
  custom_integrations/nicehash_excavator/icon.png
  custom_integrations/nicehash_excavator/icon@2x.png
  custom_integrations/nicehash_excavator/logo.png
  custom_integrations/nicehash_excavator/logo@2x.png
Labels: cla-signed

#3092 Add Yandex Weather icons for custom integration
  custom_integrations/yandex_weather/icon.png
  custom_integrations/yandex_weather/icon@2x.png
  custom_integrations/yandex_weather/logo.png
  custom_integrations/yandex_weather/logo@2x.png
Labels: cla-signed

#3099 Add Daikin Altherma logos and icons
  custom_integrations/daikin_altherma/icon.png
  custom_integrations/daikin_altherma/icon@2x.png
  custom_integrations/daikin_altherma/logo.png
  custom_integrations/daikin_altherma/logo@2x.png
Labels: cla-signed

#3098 Logo's for custom component for we connect id
  custom_integrations/volkswagen_we_connect_id/dark_icon.png
  custom_integrations/volkswagen_we_connect_id/dark_icon@2x.png
  custom_integrations/volkswagen_we_connect_id/dark_logo.png
  custom_integrations/volkswagen_we_connect_id/dark_logo@2x.png
  custom_integrations/volkswagen_we_connect_id/icon.png
  custom_integrations/volkswagen_we_connect_id/icon@2x.png
  custom_integrations/volkswagen_we_connect_id/logo.png
  custom_integrations/volkswagen_we_connect_id/logo@2x.png
Labels: cla-signed

#3100 Add cardiffwaste icons
  custom_integrations/cardiffwaste/icon.png
  custom_integrations/cardiffwaste/icon@2x.png
  custom_integrations/cardiffwaste/logo.png
  custom_integrations/cardiffwaste/logo@2x.png
Labels: cla-signed

#3097 Add icons for 'zha_toolkit' custom component.
  custom_integrations/zha_toolkit/icon.png
  custom_integrations/zha_toolkit/icon@2x.png
Labels: cla-signed

#3102 Adds new icons for Eldes Alarm integration
  custom_integrations/eldes_alarm/icon.png
  custom_integrations/eldes_alarm/icon@2x.png
  custom_integrations/eldes_alarm/logo.png
  custom_integrations/eldes_alarm/logo@2x.png
Labels: cla-signed

#3103 Feat: Add branding for Rental Control
  custom_integrations/rental_control/icon.png
  custom_integrations/rental_control/icon@2x.png
  custom_integrations/rental_control/logo.png
  custom_integrations/rental_control/logo@2x.png
Labels: cla-signed

#3077 Rename ai_thermostat to better_thermostat
  custom_integrations/ai_thermostat/icon.png
  custom_integrations/ai_thermostat/icon@2x.png
  custom_integrations/better_thermostat/icon.png
  custom_integrations/better_thermostat/icon@2x.png
Labels: cla-signed

#3105 Add solarman icons
  custom_integrations/solarman/icon.png
  custom_integrations/solarman/icon@2x.png
Labels: cla-signed

#2953 Add custom component FitX icon and logo
  custom_integrations/fitx/icon.png
  custom_integrations/fitx/icon@2x.png
  custom_integrations/fitx/logo.png
  custom_integrations/fitx/logo@2x.png
Labels: cla-signed

#3106 Ecowitt logo+icon for custom component
  custom_integrations/ecowitt/icon.png
  custom_integrations/ecowitt/logo.png
Labels: cla-signed

#2750 Add core brand for Aussie Broadband
  core_integrations/aussie_broadband/icon.png
  core_integrations/aussie_broadband/icon@2x.png
  core_integrations/aussie_broadband/logo.png
  core_integrations/aussie_broadband/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3074 Add Intellifire Gas Fireplace integration
  core_integrations/intellifire/icon.png
  core_integrations/intellifire/icon@2x.png
Labels: cla-signed

#3108 Updated Apple icon with alpha
  custom_integrations/apple_airplayer/dark_icon.png
  custom_integrations/apple_airplayer/dark_icon@2x.png
  custom_integrations/apple_airplayer/icon.png
  custom_integrations/apple_airplayer/icon@2x.png
Labels: cla-signed

#3111 Added Redmond SkyKettle (custom_components/skykettle)
  custom_integrations/skykettle/icon.png
  custom_integrations/skykettle/icon@2x.png
  custom_integrations/skykettle/logo.png
  custom_integrations/skykettle/logo@2x.png
Labels: cla-signed

#3112 Add icons for domain 'omnik'
  custom_integrations/omnik/icon.png
  custom_integrations/omnik/icon@2x.png
  custom_integrations/omnik/logo.png
  custom_integrations/omnik/logo@2x.png
Labels: cla-signed

#3114 Added icons for flagdays_dk
  custom_integrations/flagdays_dk/icon.png
  custom_integrations/flagdays_dk/icon@2x.png
Labels: cla-signed

#3117 Brewfather custom integration
  custom_integrations/brewfather/icon.png
  custom_integrations/brewfather/icon@2x.png
  custom_integrations/brewfather/logo.png
  custom_integrations/brewfather/logo@2x.png
Labels: cla-signed

#3126 Add icons for Gogs
  custom_integrations/gogs/icon.png
  custom_integrations/gogs/icon@2x.png
Labels: cla-signed

#3118 Added Bemfa (custom_components/bemfa)
  custom_integrations/bemfa/icon.png
  custom_integrations/bemfa/icon@2x.png
Labels: cla-signed, in-progress

#3122 Add icons for Juwel Helialux custom component
  custom_integrations/juwel_helialux/icon.png
  custom_integrations/juwel_helialux/icon@2x.png
  custom_integrations/juwel_helialux/logo.png
  custom_integrations/juwel_helialux/logo@2x.png
Labels: cla-signed

#3127 cisco_imc
  custom_integrations/cisco_imc/icon.png
  custom_integrations/cisco_imc/icon@2x.png
  custom_integrations/cisco_imc/logo.png
  custom_integrations/cisco_imc/logo@2x.png
Labels: cla-signed

#3129 Add Ontario Energy Board integration
  custom_integrations/ontario_energy_board/icon.png
  custom_integrations/ontario_energy_board/icon@2x.png
  custom_integrations/ontario_energy_board/logo.png
  custom_integrations/ontario_energy_board/logo@2x.png
Labels: cla-signed
