Repository home-assistant/brands, pull requests merged in 2022-08, with the labels that each got.

#3564 Add board images for additional raspberry_pi boards
  hardware/boards/raspberry_pi_1.png
  hardware/boards/raspberry_pi_2.png
  hardware/boards/raspberry_pi_3.png
  hardware/boards/raspberry_pi_zero.png
  hardware/boards/raspberry_pi_zero_w.png
Labels: cla-signed

#3565 Add Repairs
  core_integrations/repairs/icon.txt
Labels: cla-signed

#3567 Rename leviton integration domain
  core_integrations/decora
  core_integrations/decora_wifi
  core_integrations/leviton_z_wave/icon.png
  core_integrations/leviton_z_wave/icon@2x.png
  core_integrations/leviton_z_wave/logo.png
  core_integrations/leviton_z_wave/logo@2x.png
Labels: cla-signed

#3569 Add icon and logo for custom integration mobile_alerts
  custom_integrations/mobile_alerts/icon.png
  custom_integrations/mobile_alerts/icon@2x.png
  custom_integrations/mobile_alerts/logo.png
  custom_integrations/mobile_alerts/logo@2x.png
Labels: cla-signed

#3568 Add brand icon for themeparks custom integration
  custom_integrations/themeparks/icon.png
Labels: cla-signed

#3562 Add icon and logo for custom integration nestup_evn
  custom_integrations/nestup_evn/icon.png
  custom_integrations/nestup_evn/icon@2x.png
  custom_integrations/nestup_evn/logo.png
  custom_integrations/nestup_evn/logo@2x.png
Labels: cla-signed, in-progress

#3557 Add new custom integration mhtzn
  custom_integrations/mhtzn/icon.png
  custom_integrations/mhtzn/icon@2x.png
  custom_integrations/mhtzn/logo.png
  custom_integrations/mhtzn/logo@2x.png
Labels: cla-signed

#3572 feat: add Checkly logos
  custom_integrations/checkly/logo.png
  custom_integrations/checkly/logo@2x.png
Labels: cla-signed

#2807 Add Escea fireplace brand
  core_integrations/escea/icon.png
  core_integrations/escea/icon@2x.png
  core_integrations/escea/logo.png
  core_integrations/escea/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3574 Delete custom integration escea
  custom_integrations/escea/icon.png
  custom_integrations/escea/icon@2x.png
  custom_integrations/escea/logo.png
Labels: cla-signed

#3573 Added logos for JustNimbus integration
  core_integrations/justnimbus/icon.png
  core_integrations/justnimbus/icon@2x.png
  core_integrations/justnimbus/logo.png
  core_integrations/justnimbus/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent, in-progress

#3539 Add Enpal
  custom_integrations/enpal/icon.png
  custom_integrations/enpal/logo.png
Labels: cla-signed, in-progress

#3577 Add custom component Seafile
  custom_integrations/seafile/icon.png
  custom_integrations/seafile/icon@2x.png
  custom_integrations/seafile/logo.png
  custom_integrations/seafile/logo@2x.png
Labels: cla-signed

#3570 Add Yale Access Bluetooth Integration
  core_integrations/yalexs_ble/icon.png
  core_integrations/yalexs_ble/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3418 Add LaCrosse View icon and logo
  core_integrations/lacrosse_view/dark_icon.png
  core_integrations/lacrosse_view/dark_logo.png
  core_integrations/lacrosse_view/icon.png
  core_integrations/lacrosse_view/logo.png
Labels: cla-signed, parent-merged, has-parent, in-progress

#3579 Add schedule
  core_integrations/schedule/icon.txt
Labels: cla-signed, has-parent

#3578 New custom_integration daily_schedule icon
  custom_integrations/daily_schedule/icon.png
  custom_integrations/daily_schedule/icon@2x.png
Labels: cla-signed

#3582 Add Qingping integration
  core_integrations/qingping/icon.png
  core_integrations/qingping/icon@2x.png
Labels: cla-signed

#3583 Add August Bluetooth supported brand
  core_integrations/august_ble
Labels: cla-signed

#3575 Add new custom integration hiq
  custom_integrations/hiq/icon.png
  custom_integrations/hiq/icon@2x.png
  custom_integrations/hiq/logo.png
  custom_integrations/hiq/logo@2x.png
Labels: cla-signed, in-progress

#3580 Add Systemair brand
  custom_integrations/systemair/icon.png
  custom_integrations/systemair/icon@2x.png
  custom_integrations/systemair/logo.png
  custom_integrations/systemair/logo@2x.png
Labels: cla-signed

#3588 add logos and icon for hero labs (makers of Sonic)
  custom_integrations/sonic/dark_icon.png
  custom_integrations/sonic/dark_logo.png
  custom_integrations/sonic/dark_logo@2x.png
  custom_integrations/sonic/icon.png
  custom_integrations/sonic/logo.png
  custom_integrations/sonic/logo@2x.png
Labels: cla-signed

#3576 Add SNOOZ custom integration
  custom_integrations/snooz/dark_logo.png
  custom_integrations/snooz/dark_logo@2x.png
  custom_integrations/snooz/icon.png
  custom_integrations/snooz/icon@2x.png
  custom_integrations/snooz/logo.png
  custom_integrations/snooz/logo@2x.png
Labels: cla-signed

#3586 Add Fully Kiosk Browser icon to core integrations
  core_integrations/fully_kiosk/icon.png
Labels: cla-signed, awaits-parent, has-parent

#3590 Add eForsyning icon/logo
  custom_integrations/eforsyning/icon.png
  custom_integrations/eforsyning/logo.png
Labels: cla-signed

#3591 Add Novafos icon/logo
  custom_integrations/novafos/icon.png
  custom_integrations/novafos/logo.png
Labels: cla-signed

#3593 Adding openplantbook icon and logo
  custom_integrations/openplantbook/icon.png
  custom_integrations/openplantbook/logo.png
Labels: cla-signed

#3584 daikin_residential
  custom_integrations/daikin_residential/icon.png
  custom_integrations/daikin_residential/icon@2x.png
  custom_integrations/daikin_residential/logo.png
  custom_integrations/daikin_residential/logo@2x.png
Labels: cla-signed

#3589 New icons for new custom integration Binance Pool
  custom_integrations/binance_pool/icon.png
  custom_integrations/binance_pool/icon@2x.png
Labels: cla-signed

#3594 Adding skisporet icon
  custom_integrations/skisporet/icon.png
  custom_integrations/skisporet/icon@2x.png
Labels: cla-signed

#3595 Add MelCloud custom integration logo
  custom_integrations/melcloud_custom/icon.png
  custom_integrations/melcloud_custom/icon@2x.png
  custom_integrations/melcloud_custom/logo.png
  custom_integrations/melcloud_custom/logo@2x.png
Labels: cla-signed

#3596 Add rrd_recorder logo and icon
  custom_integrations/rrd_recorder/icon.png
  custom_integrations/rrd_recorder/logo.png
Labels: cla-signed

#3598 Icons for new custom component EMCD Pool
  custom_integrations/emcd_pool/icon.png
  custom_integrations/emcd_pool/icon@2x.png
Labels: cla-signed

#3513 Add new custom integration ewelink_aiot
  custom_integrations/ewelink_aiot/icon.png
  custom_integrations/ewelink_aiot/icon@2x.png
  custom_integrations/ewelink_aiot/logo.png
  custom_integrations/ewelink_aiot/logo@2x.png
Labels: cla-signed

#3599 Added tami4 logos to custom integration
  custom_integrations/tami4edge/icon.png
  custom_integrations/tami4edge/icon@2x.png
  custom_integrations/tami4edge/logo.png
  custom_integrations/tami4edge/logo@2x.png
Labels: cla-signed, in-progress

#3601 Add images for custom integration Watts Vision
  custom_integrations/watts_vision/icon.png
  custom_integrations/watts_vision/icon@2x.png
  custom_integrations/watts_vision/logo.png
  custom_integrations/watts_vision/logo@2x.png
Labels: cla-signed

#3602 Added high tech pet logos
  custom_integrations/powerpetdoor/icon.png
  custom_integrations/powerpetdoor/logo.png
Labels: cla-signed

#3603 add WienerNetze Smartmeter integration (wnsm)
  custom_integrations/wnsm/icon.png
  custom_integrations/wnsm/logo.png
Labels: cla-signed

#3606 Add thermopro integration
  core_integrations/thermopro/icon.png
  core_integrations/thermopro/icon@2x.png
Labels: cla-signed

#3610 Add hochwasserportal custom integration
  custom_integrations/hochwasserportal/icon.png
  custom_integrations/hochwasserportal/icon@2x.png
  custom_integrations/hochwasserportal/logo.png
  custom_integrations/hochwasserportal/logo@2x.png
Labels: cla-signed

#3608 Add logos for daikin_residential_altherma
  custom_integrations/daikin_residential_altherma/icon.png
  custom_integrations/daikin_residential_altherma/icon@2x.png
  custom_integrations/daikin_residential_altherma/logo.png
  custom_integrations/daikin_residential_altherma/logo@2x.png
Labels: cla-signed

#3607 Adding MLB Logos
  custom_integrations/mlb/icon.png
  custom_integrations/mlb/icon@2x.png
Labels: cla-signed

#3604 weishaupt_wcm_com icons
  custom_integrations/weishaupt_wcm_com/icon.png
  custom_integrations/weishaupt_wcm_com/icon@2x.png
Labels: cla-signed

#3609 Add thermobeacon integration
  core_integrations/thermobeacon/icon.png
  core_integrations/thermobeacon/icon@2x.png
Labels: cla-signed, parent-merged, awaits-parent, has-parent

#3611 Add BThome icons
  core_integrations/bthome/icon.png
  core_integrations/bthome/icon@2x.png
  core_integrations/bthome/logo.png
  core_integrations/bthome/logo@2x.png
Labels: cla-signed

#3614 Add thermobeacon supported brands
  core_integrations/sensorblue
  core_integrations/thermoplus/icon.png
  core_integrations/thermoplus/icon@2x.png
Labels: cla-signed, parent-merged

#3620 Add LED BLE integration
  core_integrations/led_ble/icon.png
  core_integrations/led_ble/icon@2x.png
Labels: cla-signed, parent-merged

#3619 lelight icons custom integration
  custom_integrations/lelight/icon.png
  custom_integrations/lelight/icon@2x.png
Labels: cla-signed

#3621 add canvas logos
  custom_integrations/canvas/icon.png
  custom_integrations/canvas/icon@2x.png
  custom_integrations/canvas/logo.png
  custom_integrations/canvas/logo@2x.png
Labels: cla-signed

#3623 Add prusalink
  core_integrations/prusalink/dark_icon.png
  core_integrations/prusalink/dark_icon@2x.png
  core_integrations/prusalink/dark_logo.png
  core_integrations/prusalink/dark_logo@2x.png
  core_integrations/prusalink/icon.png
  core_integrations/prusalink/icon@2x.png
  core_integrations/prusalink/logo.png
  core_integrations/prusalink/logo@2x.png
Labels: cla-signed, parent-merged

#3627 Add custom component Tattelecom intercom
  custom_integrations/tattelecom_intercom/icon.png
  custom_integrations/tattelecom_intercom/icon@2x.png
  custom_integrations/tattelecom_intercom/logo.png
  custom_integrations/tattelecom_intercom/logo@2x.png
Labels: cla-signed, in-progress

#3622 add infinitecampus logos
  custom_integrations/infinitecampus/icon.png
  custom_integrations/infinitecampus/icon@2x.png
  custom_integrations/infinitecampus/logo.png
  custom_integrations/infinitecampus/logo@2x.png
Labels: cla-signed

#3625 Add icons and logos for myuplink
  custom_integrations/myuplink/icon.png
  custom_integrations/myuplink/icon@2x.png
  custom_integrations/myuplink/logo.png
  custom_integrations/myuplink/logo@2x.png
Labels: cla-signed

#3626 Add Nutrichef as a supported brand of inkbird
  core_integrations/nutrichef/icon.png
  core_integrations/nutrichef/icon@2x.png
Labels: cla-signed, parent-merged, has-parent

#3624 Add eaton icons and logos in domain "eaton_epdu"
  custom_integrations/eaton_epdu/dark_icon.png
  custom_integrations/eaton_epdu/dark_icon@2x.png
  custom_integrations/eaton_epdu/dark_logo.png
  custom_integrations/eaton_epdu/dark_logo@2x.png
  custom_integrations/eaton_epdu/icon.png
  custom_integrations/eaton_epdu/icon@2x.png
  custom_integrations/eaton_epdu/logo.png
  custom_integrations/eaton_epdu/logo@2x.png
Labels: cla-signed, in-progress

#3356 Add images for new Melnor integration
  core_integrations/melnor/icon.png
  core_integrations/melnor/icon@2x.png
  core_integrations/melnor/logo.png
  core_integrations/melnor/logo@2x.png
Labels: cla-signed, parent-merged, awaits-parent, has-parent

#3628 Add sensorpro integration
  core_integrations/sensorpro/icon.png
  core_integrations/sensorpro/icon@2x.png
Labels: cla-signed, parent-merged

#3630 New BTHome icons
  core_integrations/bthome/icon.png
  core_integrations/bthome/icon@2x.png
  core_integrations/bthome/logo.png
  core_integrations/bthome/logo@2x.png
Labels: cla-signed
