Repository home-assistant/brands, pull requests merged in 2022-04, with the labels that each got.

#3310 Add Selve Logo
  custom_integrations/selve/icon.png
  custom_integrations/selve/logo.png
Labels: cla-signed, in-progress

#3315 Add dark logos and icons for Sonoff custom integration
  custom_integrations/sonoff/dark_icon.png
  custom_integrations/sonoff/dark_icon@2x.png
  custom_integrations/sonoff/dark_logo.png
  custom_integrations/sonoff/dark_logo@2x.png
Labels: cla-signed

#3314 Add dark icons for Local File and File Size integration
  core_integrations/local_file/dark_icon.png
  core_integrations/local_file/dark_icon@2x.png
Labels: cla-signed

#3313 Add dark icons for CPU Speed integration
  core_integrations/cpuspeed/dark_icon.png
  core_integrations/cpuspeed/dark_icon@2x.png
Labels: cla-signed

#3312 Add chargepoint logo
  custom_integrations/chargepoint/icon.png
  custom_integrations/chargepoint/icon@2x.png
  custom_integrations/chargepoint/logo.png
  custom_integrations/chargepoint/logo@2x.png
Labels: cla-signed

#3318 Add brand assets for GivEnergy
  custom_integrations/givenergy_local/icon.png
  custom_integrations/givenergy_local/logo.png
  custom_integrations/givenergy_local/logo@2x.png
Labels: cla-signed

#3316 Philips airpurifier coap
  custom_integrations/philips_airpurifier_coap/icon.png
  custom_integrations/philips_airpurifier_coap/icon@2x.png
  custom_integrations/philips_airpurifier_coap/logo.png
  custom_integrations/philips_airpurifier_coap/logo@2x.png
Labels: cla-signed

#3320 Fix typo in readme cooperate --> corporate
  README.md
Labels: cla-signed

#3321 Adds Electrolux Wellbeing assets
  custom_integrations/wellbeing/icon.png
  custom_integrations/wellbeing/icon@2x.png
  custom_integrations/wellbeing/logo.png
  custom_integrations/wellbeing/logo@2x.png
Labels: cla-signed

#3322 Adds greenely assets
  custom_integrations/greenely/icon.png
  custom_integrations/greenely/icon@2x.png
  custom_integrations/greenely/logo.png
  custom_integrations/greenely/logo@2x.png
Labels: cla-signed

#3327 Add assets for idfm custom integration
  custom_integrations/idfm/icon.png
  custom_integrations/idfm/icon@2x.png
  custom_integrations/idfm/logo.png
  custom_integrations/idfm/logo@2x.png
Labels: cla-signed

#3328 Add ATOMCam(Hacked) icons
  custom_integrations/atomcam_hack/icon.png
  custom_integrations/atomcam_hack/icon@2x.png
  custom_integrations/atomcam_hack/logo.png
  custom_integrations/atomcam_hack/logo@2x.png
Labels: cla-signed

#3325 Add taipower_bimonthly_cost integration icons
  custom_integrations/taipower_bimonthly_cost/icon.png
  custom_integrations/taipower_bimonthly_cost/icon@2x.png
Labels: cla-signed, in-progress

#3331 add hdhomerun icons
  custom_integrations/hdhomerun/icon.png
  custom_integrations/hdhomerun/icon@2x.png
Labels: cla-signed

#3333 added skolmat integration
  custom_integrations/skolmat/icon.png
Labels: cla-signed

#3330 Add Swatch Logo
  custom_integrations/swatch/icon.png
Labels: cla-signed

#3340 Remove digital loggers
  core_integrations/digitalloggers/icon.png
  core_integrations/digitalloggers/icon@2x.png
Labels: cla-signed, cleanup

#3341 Add icons and logos for Lektrico custom integration
  custom_integrations/lektrico_custom/dark_icon.png
  custom_integrations/lektrico_custom/dark_icon@2x.png
  custom_integrations/lektrico_custom/dark_logo.png
  custom_integrations/lektrico_custom/icon.png
  custom_integrations/lektrico_custom/icon@2x.png
  custom_integrations/lektrico_custom/logo.png
  custom_integrations/lektrico_custom/logo@2x.png
Labels: cla-signed

#3342 Add senz core integration icons and logos
  core_integrations/senz/dark_logo.png
  core_integrations/senz/dark_logo@2x.png
  core_integrations/senz/icon.png
  core_integrations/senz/icon@2x.png
  core_integrations/senz/logo.png
  core_integrations/senz/logo@2x.png
  custom_integrations/senz/icon.png
  custom_integrations/senz/icon@2x.png
  custom_integrations/senz/logo.png
  custom_integrations/senz/logo@2x.png
Labels: cla-signed, parent-merged, has-parent

#3344 Adds knx_panel custom integration logo
  custom_integrations/knx_panel/icon.png
  custom_integrations/knx_panel/icon@2x.png
  custom_integrations/knx_panel/logo.png
  custom_integrations/knx_panel/logo@2x.png
Labels: cla-signed

#3345 HA-Services Logo and Icon
  custom_integrations/ha_services/icon.png
  custom_integrations/ha_services/logo.png
Labels: cla-signed, in-progress

#3346 Add Kia Connected Services to custom components
  custom_integrations/kia_connect/icon.png
  custom_integrations/kia_connect/icon@2x.png
Labels: cla-signed

#3338 ecotrend_ista
  custom_integrations/ecotrend_ista/icon.png
  custom_integrations/ecotrend_ista/icon@2x.png
  custom_integrations/ecotrend_ista/logo.png
  custom_integrations/ecotrend_ista/logo@2x.png
Labels: cla-signed, in-progress

#3347 Added dark_icon
  custom_integrations/apsystems_ecur/icon.png
Labels: cla-signed, in-progress

#3329 Add SRG SSR logo which is used in the SRF Weather API description
  custom_integrations/srf_weather/icon.png
  custom_integrations/srf_weather/icon@2x.png
  custom_integrations/srf_weather/logo.png
  custom_integrations/srf_weather/logo@2x.png
Labels: cla-signed, in-progress

#3324 add sst_cloud icons
  custom_integrations/sst_cloud/icon.png
  custom_integrations/sst_cloud/icon@2x.png
Labels: cla-signed, in-progress

#3349 added nasa custom integration logo and icon
  custom_integrations/nasa/icon.png
  custom_integrations/nasa/icon@2x.png
  custom_integrations/nasa/logo.png
  custom_integrations/nasa/logo@2x.png
Labels: cla-signed

#3350 Added logo for ha-pse-grid-stat custom component
  custom_integrations/ha_pse_grid_stat/icon.png
  custom_integrations/ha_pse_grid_stat/icon@2x.png
  custom_integrations/ha_pse_grid_stat/logo.png
Labels: cla-signed

#3354 Add music assistant (mass) icon
  custom_integrations/mass/icon.png
  custom_integrations/mass/icon@2x.png
Labels: cla-signed

#3348 Add Wattpilot integration
  custom_integrations/wattpilot/icon.png
  custom_integrations/wattpilot/icon@2x.png
  custom_integrations/wattpilot/logo.png
  custom_integrations/wattpilot/logo@2x.png
Labels: cla-signed, in-progress

#3357 Add EcoFlow icons
  custom_integrations/ecoflow/dark_logo.png
  custom_integrations/ecoflow/icon.png
  custom_integrations/ecoflow/icon@2x.png
  custom_integrations/ecoflow/logo.png
Labels: cla-signed

#3358 Add asuswrt dark logo
  core_integrations/asuswrt/dark_logo.png
  core_integrations/asuswrt/dark_logo@2x.png
Labels: cla-signed

#3359 added uptime_kuma custom integration logo and icon
  custom_integrations/uptime_kuma/icon.png
  custom_integrations/uptime_kuma/icon@2x.png
Labels: cla-signed

#3360 add oilfox icons
  custom_integrations/oilfox/logo.png
  custom_integrations/oilfox/logo@2x.png
Labels: cla-signed, cla-error

#3362 Change supervisor Icon
  core_integrations/hassio
  core_integrations/hassio/icon.txt
Labels: cla-signed

#3287 Delete custom_integrations/philips_ambilight+hue directory
  custom_integrations/philips_ambilight+hue/icon.png
  custom_integrations/philips_ambilight+hue/icon@2x.png
  custom_integrations/philips_ambilight+hue/logo.png
  custom_integrations/philips_ambilight+hue/logo@2x.png
Labels: cla-signed

#3336 Added Hxon (custom_components/hxon)
  custom_integrations/hxon/icon.png
  custom_integrations/hxon/icon@2x.png
Labels: cla-signed, in-progress

#3363 Ha blueair
  custom_integrations/ha_blueair/icon.png
  custom_integrations/ha_blueair/icon@2x.png
  custom_integrations/ha_blueair/logo.png
  custom_integrations/ha_blueair/logo@2x.png
Labels: cla-signed, in-progress

#2904 Add QNAP QSW integration
  core_integrations/qnap_qsw
Labels: cla-signed, awaits-parent, has-parent, hacktoberfest-accepted

#3364 add kwikset-ha icons
  custom_integrations/kwikset/icon.png
  custom_integrations/kwikset/icon@2x.png
  custom_integrations/kwikset/logo.png
  custom_integrations/kwikset/logo@2x.png
Labels: cla-signed, in-progress

#3355 Add brand for trafikverket_ferry
  core_integrations/trafikverket_ferry/icon.png
  core_integrations/trafikverket_ferry/icon@2x.png
  core_integrations/trafikverket_ferry/logo.png
  core_integrations/trafikverket_ferry/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3365 Add slimproto integration icon
  core_integrations/slimproto/icon.png
  core_integrations/slimproto/icon@2x.png
Labels: cla-signed

#3366 Add asusrouter custom integration
  custom_integrations/asusrouter/dark_logo.png
  custom_integrations/asusrouter/dark_logo@2x.png
  custom_integrations/asusrouter/icon.png
  custom_integrations/asusrouter/icon@2x.png
  custom_integrations/asusrouter/logo.png
  custom_integrations/asusrouter/logo@2x.png
Labels: cla-signed

#3370 add motion blinds supported logos
  core_integrations/3_day_blinds/icon.png
  core_integrations/3_day_blinds/logo.png
  core_integrations/amp_motorization/icon.png
  core_integrations/amp_motorization/icon@2x.png
  core_integrations/bliss_automation/icon.png
  core_integrations/bliss_automation/icon@2x.png
  core_integrations/bloc_blinds/icon.png
  core_integrations/bloc_blinds/icon@2x.png
  core_integrations/bloc_blinds/logo.png
  core_integrations/brel_home/icon.png
  core_integrations/brel_home/icon@2x.png
  core_integrations/dooya/icon.png
  core_integrations/dooya/icon@2x.png
  core_integrations/dooya/logo.png
  core_integrations/gaviota/icon.png
  core_integrations/gaviota/icon@2x.png
  core_integrations/gaviota/logo.png
  core_integrations/hurrican_shutters_wholesale/icon.png
  core_integrations/ismartwindow/icon.png
  core_integrations/ismartwindow/icon@2x.png
  core_integrations/ismartwindow/logo.png
  core_integrations/ismartwindow/logo@2x.png
  core_integrations/martec/icon.png
  core_integrations/martec/icon@2x.png
  core_integrations/raven_rock_mfg/icon.png
  core_integrations/raven_rock_mfg/icon@2x.png
  core_integrations/smart_blinds/icon.png
  core_integrations/smart_blinds/icon@2x.png
  core_integrations/smart_blinds/logo.png
  core_integrations/smart_blinds/logo@2x.png
  core_integrations/smart_home/icon.png
  core_integrations/smart_home/icon@2x.png
  core_integrations/uprise_smart_shades/icon.png
  core_integrations/uprise_smart_shades/icon@2x.png
Labels: cla-signed

#3367 add marantz brands
  core_integrations/marantz/icon.png
  core_integrations/marantz/icon@2x.png
  core_integrations/marantz/logo.png
Labels: cla-signed

#3280 Add Aldes integration
  custom_integrations/aldes/icon.png
  custom_integrations/aldes/icon@2x.png
  custom_integrations/aldes/logo.png
  custom_integrations/aldes/logo@2x.png
Labels: cla-signed

#3373 Added Electra Smart logos to custom integration
  custom_integrations/electrasmart/icon.png
  custom_integrations/electrasmart/icon@2x.png
  custom_integrations/electrasmart/logo.png
  custom_integrations/electrasmart/logo@2x.png
Labels: cla-signed, in-progress

#3375 Remove Arlo integration
  core_integrations/arlo/icon.png
  core_integrations/arlo/icon@2x.png
  core_integrations/arlo/logo.png
  core_integrations/arlo/logo@2x.png
Labels: cla-signed
