Repository home-assistant/brands, pull requests merged in 2022-10, with the labels that each got.

#3730 add aqara_bridge icon
  custom_integrations/aqara_bridge/icon.png
  custom_integrations/aqara_bridge/icon@2x.png
  custom_integrations/aqara_bridge/logo.png
  custom_integrations/aqara_bridge/logo@2x.png
Labels: in-progress

#3734 Switch to rsvg-convert for mdi generation
  scripts/build.sh
  scripts/mdi.css
Labels: Hacktoberfest

#3743 Add more brands
  core_brands/inovelli/icon.png
  core_brands/inovelli/icon@2x.png
  core_brands/inovelli/logo.png
  core_brands/inovelli/logo@2x.png
  core_brands/jasco/icon.png
  core_brands/jasco/icon@2x.png
  core_brands/jasco/logo.png
  core_brands/u_tec/icon.png
  core_brands/u_tec/icon@2x.png
  core_brands/zooz/icon.png
  core_brands/zooz/icon@2x.png
Labels: Hacktoberfest

#3741 Add Bubendorff brand
  core_integrations/bubendorff/icon.png
  core_integrations/bubendorff/logo.png
  core_integrations/bubendorff/logo@2x.png
Labels: Hacktoberfest

#3740 Add legrand brand
  core_integrations/legrand
Labels: Hacktoberfest

#3739 Add bticino and smarther brand
  core_integrations/bticino/icon.png
  core_integrations/bticino/icon@2x.png
  core_integrations/bticino/logo.png
  core_integrations/bticino/logo@2x.png
  core_integrations/smarther
Labels: Hacktoberfest

#3742 Add Bswitch brand
  core_integrations/bswitch/icon.png
  core_integrations/bswitch/icon@2x.png
  core_integrations/bswitch/logo.png
  core_integrations/bswitch/logo@2x.png
Labels: Hacktoberfest

#3735 🎨 Add brand image for rte_ecowatt integration
  custom_integrations/rte_ecowatt/icon.png
  custom_integrations/rte_ecowatt/icon@2x.png
  custom_integrations/rte_ecowatt/logo.png
  custom_integrations/rte_ecowatt/logo@2x.png
Labels: Hacktoberfest

#3737 add Camect icons
  custom_integrations/camect/dark_icon.png
  custom_integrations/camect/icon.png
Labels: Hacktoberfest

#3748 Add branding for sandman_doppler
  custom_integrations/sandman_doppler/dark_logo.png
  custom_integrations/sandman_doppler/dark_logo@2x.png
  custom_integrations/sandman_doppler/icon.png
  custom_integrations/sandman_doppler/icon@2x.png
  custom_integrations/sandman_doppler/logo.png
  custom_integrations/sandman_doppler/logo@2x.png
Labels: Hacktoberfest

#3749 Add dark logos for vizio
  core_integrations/vizio/dark_logo.png
  core_integrations/vizio/dark_logo@2x.png
Labels: Hacktoberfest

#3746 Add Simply Automated brand icon and logo.
  core_brands/simply_automated/icon.png
  core_brands/simply_automated/icon@2x.png
  core_brands/simply_automated/logo.png
  core_brands/simply_automated/logo@2x.png
Labels: Hacktoberfest

#3747 Add PCS Lighting brand icon and logo.
  core_brands/pcs_lighting/icon.png
  core_brands/pcs_lighting/logo.png
Labels: Hacktoberfest

#3745 add oilfox icon
  custom_integrations/oilfox/icon.png
  custom_integrations/oilfox/icon@2x.png
  custom_integrations/oilfox/logo.png
  custom_integrations/oilfox/logo@2x.png
Labels: Hacktoberfest, in-progress

#3760 Add brand image for Google Assistant Relay
  custom_integrations/google_assistant_relay/icon.png
  custom_integrations/google_assistant_relay/icon@2x.png
  custom_integrations/google_assistant_relay/logo.png
  custom_integrations/google_assistant_relay/logo@2x.png
Labels: Hacktoberfest

#3761 Add custom integration epson_projector_link Brand
  custom_integrations/epson_projector_link/icon.png
  custom_integrations/epson_projector_link/icon@2x.png
  custom_integrations/epson_projector_link/logo.png
  custom_integrations/epson_projector_link/logo@2x.png
Labels: Hacktoberfest

#3744 Add icons for webuntis integration
  custom_integrations/webuntis/icon.png
  custom_integrations/webuntis/icon@2x.png
Labels: Hacktoberfest

#3731 add w1000-energy-monitor icons
  custom_integrations/w1000-energy-monitor/icon.png
  custom_integrations/w1000-energy-monitor/icon@2x.png
  custom_integrations/w1000-energy-monitor/logo.png
  custom_integrations/w1000-energy-monitor/logo@2x.png
Labels: Hacktoberfest, in-progress

#3732 logos for the eufy robovac
  custom_integrations/robovac/icon.png
  custom_integrations/robovac/icon@2x.png
  custom_integrations/robovac/logo.png
  custom_integrations/robovac/logo@2x.png
Labels: Hacktoberfest

#3757 Add branding for WaterNSW WaterInsights
  custom_integrations/waterinsights/icon.png
  custom_integrations/waterinsights/icon@2x.png
  custom_integrations/waterinsights/logo.png
  custom_integrations/waterinsights/logo@2x.png
Labels: Hacktoberfest

#3669 Move snooz to core integrations
  core_integrations/snooz/dark_logo.png
  core_integrations/snooz/dark_logo@2x.png
  core_integrations/snooz/icon.png
  core_integrations/snooz/icon@2x.png
  core_integrations/snooz/logo.png
  core_integrations/snooz/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3766 Add matter icon and logo
  core_integrations/matter/icon.png
  core_integrations/matter/icon@2x.png
  core_integrations/matter/logo.png
  core_integrations/matter/logo@2x.png
Labels: Hacktoberfest

#3767 Add devolo brand icon
  core_brands/devolo/dark_icon.png
  core_brands/devolo/dark_icon@2x.png
  core_brands/devolo/icon.png
  core_brands/devolo/icon@2x.png
Labels: Hacktoberfest

#3769 Powerbrain
  custom_integrations/powerbrain/icon.png
  custom_integrations/powerbrain/icon@2x.png
  custom_integrations/powerbrain/logo.png
  custom_integrations/powerbrain/logo@2x.png
Labels: Hacktoberfest

#3768 Add Nanogreen integration icons and logos
  custom_integrations/nanogreen/icon.png
  custom_integrations/nanogreen/icon@2x.png
  custom_integrations/nanogreen/logo.png
  custom_integrations/nanogreen/logo@2x.png
Labels: Hacktoberfest

#3764 Add plejd to custom integrations
  custom_integrations/plejd/icon.png
  custom_integrations/plejd/icon@2x.png
Labels: Hacktoberfest

#3770 Add Heiwa brand icons
  core_integrations/heiwa/icon.png
  core_integrations/heiwa/icon@2x.png
  core_integrations/heiwa/logo.png
  core_integrations/heiwa/logo@2x.png
Labels: Hacktoberfest

#3775 Add icon for file_upload internal component
  core_integrations/file_upload/icon.txt
Labels: Hacktoberfest

#3763 formulaone_api icons
  custom_integrations/formulaone_api/icon.png
  custom_integrations/formulaone_api/icon@2x.png
  custom_integrations/formulaone_api/logo.png
Labels: Hacktoberfest, in-progress

#3772 Move ecowitt to core_integrations
  core_integrations/ecowitt/icon.png
  core_integrations/ecowitt/logo.png
Labels: Hacktoberfest

#3774 Add eafm images
  core_integrations/eafm/icon.png
  core_integrations/eafm/icon@2x.png
  core_integrations/eafm/logo.png
  core_integrations/eafm/logo@2x.png
Labels: Hacktoberfest

#3773 Icon for sensorpush
  core_integrations/sensorpush/icon.png
  core_integrations/sensorpush/icon@2x.png
Labels: Hacktoberfest

#3782 Replace broken indego symlink
  custom_integrations/indego
  custom_integrations/indego/icon.png
  custom_integrations/indego/icon@2x.png
  custom_integrations/indego/logo.png
  custom_integrations/indego/logo@2x.png
Labels: Hacktoberfest

#3778 Symlink familyhub to samsung
  core_integrations/familyhub
  core_integrations/familyhub/icon.png
  core_integrations/familyhub/samsungtv
Labels: Hacktoberfest

#3780 Symlink blackbird to monoprice
  core_integrations/blackbird
  core_integrations/blackbird/icon.png
  core_integrations/blackbird/icon@2x.png
Labels: Hacktoberfest

#3783 Delete broken zigbee symlink
  core_integrations/zigbee
Labels: Hacktoberfest

#3801 Add hardkernel logos
  core_integrations/hardkernel/icon.png
  core_integrations/hardkernel/logo.png
  core_integrations/hardkernel/logo@2x.png
Labels: Hacktoberfest

#3799 Add icon version of smart_meter_texas logo
  core_integrations/smart_meter_texas/icon.png
  core_integrations/smart_meter_texas/icon@2x.png
Labels: Hacktoberfest

#3790 Remove random icon.txt file in core_integrations folder
  core_integrations/icon.txt
Labels: Hacktoberfest

#3800 Add mdi icon for intent core integration
  core_integrations/intent/icon.txt
Labels: Hacktoberfest

#3796 Add icon for zodiac integration
  core_integrations/zodiac/icon.txt
Labels: Hacktoberfest

#3797 Add icon for locative
  core_integrations/locative/icon.png
  core_integrations/locative/icon@2x.png
Labels: Hacktoberfest

#3798 Add mdi icon for color_extractor core integration
  core_integrations/color_extractor/icon.txt
Labels: Hacktoberfest

#3795 Add logo and icon for arris_tg2492lg
  core_integrations/arris_tg2492lg/dark_icon.png
  core_integrations/arris_tg2492lg/dark_icon@2x.png
  core_integrations/arris_tg2492lg/dark_logo.png
  core_integrations/arris_tg2492lg/dark_logo@2x.png
  core_integrations/arris_tg2492lg/icon.png
  core_integrations/arris_tg2492lg/icon@2x.png
  core_integrations/arris_tg2492lg/logo.png
  core_integrations/arris_tg2492lg/logo@2x.png
Labels: Hacktoberfest

#3781 Fix broken bosch_sch symlinks
  core_integrations/bosch_shc/logo.png
  core_integrations/bosch_shc/logo@2x.png
Labels: Hacktoberfest

#3779 Symlink imap_email_content to smtp
  core_integrations/imap_email_content
  core_integrations/imap_email_content/icon.png
Labels: Hacktoberfest

#3788 Added MyNeato domain
  custom_integrations/myneato/icon.png
  custom_integrations/myneato/icon@2x.png
  custom_integrations/myneato/logo.png
  custom_integrations/myneato/logo@2x.png
Labels: Hacktoberfest

#3806 Add overwolfstatus branding
  custom_integrations/overwolfstatus/icon.png
  custom_integrations/overwolfstatus/icon@2x.png
  custom_integrations/overwolfstatus/logo.png
  custom_integrations/overwolfstatus/logo@2x.png
Labels: Hacktoberfest

#3805 Add dark icon and logo for Yamaha (YNCA) and Yamaha
  core_integrations/yamaha/dark_icon.png
  core_integrations/yamaha/dark_icon@2x.png
  core_integrations/yamaha/dark_logo.png
  core_integrations/yamaha/dark_logo@2x.png
  custom_integrations/yamaha_ynca/dark_icon.png
  custom_integrations/yamaha_ynca/dark_icon@2x.png
  custom_integrations/yamaha_ynca/dark_logo.png
  custom_integrations/yamaha_ynca/dark_logo@2x.png
Labels: Hacktoberfest

#3804 Add dark icon and logo for Logitech
  core_brands/logitech/dark_icon.png
  core_brands/logitech/dark_icon@2x.png
  core_brands/logitech/dark_logo.png
  core_brands/logitech/dark_logo@2x.png
Labels: Hacktoberfest

#3787 Add ultraloq
  core_integrations/ultraloq/icon.png
  core_integrations/ultraloq/icon@2x.png
  core_integrations/ultraloq/logo.png
  core_integrations/ultraloq/logo@2x.png
Labels: Hacktoberfest

#3808 feat: Added icons for paperspace custom integration
  custom_integrations/paperspace/icon.png
  custom_integrations/paperspace/icon@2x.png
Labels: Hacktoberfest

#3813 Add WhatsPie Images
  custom_integrations/whatspie/icon.png
  custom_integrations/whatspie/icon@2x.png
  custom_integrations/whatspie/logo.png
  custom_integrations/whatspie/logo@2x.png
Labels: Hacktoberfest

#3784 Added OralB images
  core_integrations/oralb/icon.png
  core_integrations/oralb/icon@2x.png
  core_integrations/oralb/logo.png
  core_integrations/oralb/logo@2x.png
Labels: awaits-parent, has-parent

#3814 Add ikea brand and symfonisk virtual integration
  core_brands/ikea/icon.png
  core_brands/ikea/icon@2x.png
  core_brands/ikea/logo.png
  core_brands/ikea/logo@2x.png
  core_integrations/symfonisk
  core_integrations/tradfri
Labels: Hacktoberfest

#3809 Add custom integration zyxel_poe brand
  custom_integrations/zyxel_poe/icon.png
  custom_integrations/zyxel_poe/icon@2x.png
  custom_integrations/zyxel_poe/logo.png
  custom_integrations/zyxel_poe/logo@2x.png
Labels: Hacktoberfest

#3810 Added Geo Home icons for Geo Home Smart Meters
  custom_integrations/geo_home/icon.png
  custom_integrations/geo_home/logo.png
Labels: Hacktoberfest

#3802 Adding Forsyning icons
  custom_integrations/forsyning/icon.png
  custom_integrations/forsyning/icon@2x.png
Labels: Hacktoberfest, in-progress

#3816 Add lghorizon icons
  custom_integrations/lghorizon/icon.png
  custom_integrations/lghorizon/icon@2x.png
Labels: Hacktoberfest

#3815 Add fusion_solar integration
  custom_integrations/fusion_solar/icon.png
  custom_integrations/fusion_solar/icon@2x.png
Labels: Hacktoberfest

#3811 Add Aranet images
  core_integrations/aranet/dark_logo.png
  core_integrations/aranet/dark_logo@2x.png
  core_integrations/aranet/icon.png
  core_integrations/aranet/icon@2x.png
  core_integrations/aranet/logo.png
  core_integrations/aranet/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent, hacktoberfest-accepted

#3822 add dark icons xplora_watch
  custom_integrations/xplora_watch/dark_icon.png
  custom_integrations/xplora_watch/dark_icon@2x.png
  custom_integrations/xplora_watch/dark_logo.png
  custom_integrations/xplora_watch/dark_logo@2x.png
Labels: Hacktoberfest, hacktoberfest-accepted
