Repository home-assistant/brands, pull requests merged in 2022-05, with the labels that each got.

#3378 Revert "Adds knx_panel custom integration logo"
  custom_integrations/knx_panel/icon.png
  custom_integrations/knx_panel/icon@2x.png
  custom_integrations/knx_panel/logo.png
  custom_integrations/knx_panel/logo@2x.png
Labels: cla-signed

#3376 added my integration artificial_sunlight
  custom_integrations/artificial_sunlight/icon.png
  custom_integrations/artificial_sunlight/icon@2x.png
Labels: cla-signed

#3379 feat: add super_soco_custom integration images
  custom_integrations/super_soco_custom/dark_icon.png
  custom_integrations/super_soco_custom/dark_icon@2x.png
  custom_integrations/super_soco_custom/dark_logo.png
  custom_integrations/super_soco_custom/dark_logo@2x.png
  custom_integrations/super_soco_custom/icon.png
  custom_integrations/super_soco_custom/icon@2x.png
  custom_integrations/super_soco_custom/logo.png
  custom_integrations/super_soco_custom/logo@2x.png
Labels: cla-signed

#3380 Add Nilan Images to Custom Integrations
  custom_integrations/nilan/icon.png
  custom_integrations/nilan/icon@2x.png
  custom_integrations/nilan/logo.png
  custom_integrations/nilan/logo@2x.png
Labels: cla-signed

#3374 Add icons for the Microsoft Graph Api
  custom_integrations/microsoft_graph/icon.png
  custom_integrations/microsoft_graph/icon@2x.png
  custom_integrations/microsoft_graph/logo.png
  custom_integrations/microsoft_graph/logo@2x.png
Labels: cla-signed, in-progress, cla-error

#3381 add peaqev to brands
  custom_integrations/peaqev/icon.png
  custom_integrations/peaqev/icon@2x.png
Labels: cla-error

#3386 Add load shedding icon for custom integration
  custom_integrations/load_shedding/icon.png
Labels: cla-signed

#3387 Add dark_ icons and logos for ps4 core integration
  core_integrations/ps4/dark_icon.png
  core_integrations/ps4/dark_icon@2x.png
  core_integrations/ps4/dark_logo.png
  core_integrations/ps4/dark_logo@2x.png
Labels: cla-signed

#3394 Add Ukraine Alert: Air-raid sirens in Ukraine integration
  core_integrations/ukraine_alarm/icon.png
  core_integrations/ukraine_alarm/icon@2x.png
Labels: cla-signed

#2809 Add images for ws66i core integration
  core_integrations/ws66i/icon.png
  core_integrations/ws66i/logo.png
Labels: cla-signed, awaits-parent, has-parent

#3383 Add steam_online dark logo and icon
  core_integrations/steam_online/dark_icon.png
  core_integrations/steam_online/dark_icon@2x.png
  core_integrations/steam_online/dark_logo.png
  core_integrations/steam_online/dark_logo@2x.png
  core_integrations/steam_online/icon.png
  core_integrations/steam_online/icon@2x.png
  core_integrations/steam_online/logo.png
  core_integrations/steam_online/logo@2x.png
Labels: cla-signed

#3390 Add dark_ icons and logos for denon core integration
  core_integrations/denon/dark_icon.png
  core_integrations/denon/dark_icon@2x.png
  core_integrations/denon/dark_logo.png
  core_integrations/denon/dark_logo@2x.png
Labels: cla-signed

#3389 Add dark_ icons and logos for deconz core integration
  core_integrations/deconz/dark_icon.png
  core_integrations/deconz/dark_icon@2x.png
  core_integrations/deconz/dark_logo.png
  core_integrations/deconz/dark_logo@2x.png
Labels: cla-signed

#3388 Add dark_ icons and logos for influxdb core integration
  core_integrations/influxdb/dark_icon.png
  core_integrations/influxdb/dark_icon@2x.png
  core_integrations/influxdb/dark_logo.png
  core_integrations/influxdb/dark_logo@2x.png
Labels: cla-signed

#3397 Add voiceassistant branding
  custom_integrations/voiceassistant/icon.png
  custom_integrations/voiceassistant/icon@2x.png
  custom_integrations/voiceassistant/logo.png
  custom_integrations/voiceassistant/logo@2x.png
Labels: cla-signed

#3398 Add icons for 2minersInfo custom integration
  custom_integrations/2minersinfo/icon.png
  custom_integrations/2minersinfo/icon@2x.png
  custom_integrations/2minersinfo/logo.png
  custom_integrations/2minersinfo/logo@2x.png
Labels: cla-signed

#3352 Add lacrosseview
  custom_integrations/lacrosseview/icon.png
  custom_integrations/lacrosseview/logo.png
Labels: cla-signed, in-progress

#3401 Changes Bayesian sensor icon
  core_integrations/bayesian/icon.png
  core_integrations/bayesian/icon.txt
  core_integrations/bayesian/icon@2x.png
Labels: cla-signed

#3407 Add dark_ versions for file core integration
  core_integrations/file/dark_icon.png
  core_integrations/file/dark_icon@2x.png
Labels: cla-signed

#3406 Add dark_ versions for tile core integration
  core_integrations/tile/dark_icon.png
  core_integrations/tile/dark_icon@2x.png
  core_integrations/tile/dark_logo.png
  core_integrations/tile/dark_logo@2x.png
Labels: cla-signed

#3405 Add dark_ versions for braviatv core integration
  core_integrations/braviatv/dark_icon.png
  core_integrations/braviatv/dark_icon@2x.png
  core_integrations/braviatv/dark_logo.png
  core_integrations/braviatv/dark_logo@2x.png
Labels: cla-signed

#3403 Add dark_ versions for upnp core integration
  core_integrations/upnp/dark_icon.png
  core_integrations/upnp/dark_icon@2x.png
  core_integrations/upnp/dark_logo.png
  core_integrations/upnp/dark_logo@2x.png
Labels: cla-signed

#3404 Add dark_ versions for lifx core integration
  core_integrations/lifx/dark_icon.png
  core_integrations/lifx/dark_icon@2x.png
  core_integrations/lifx/dark_logo.png
  core_integrations/lifx/dark_logo@2x.png
Labels: cla-signed

#3402 custom component uhomeuponor
  custom_integrations/uhomeuponor/icon.png
  custom_integrations/uhomeuponor/icon@2x.png
  custom_integrations/uhomeuponor/logo.png
  custom_integrations/uhomeuponor/logo@2x.png
Labels: cla-signed

#3408 Add custom component ledfx
  custom_integrations/ledfx/icon.png
  custom_integrations/ledfx/icon@2x.png
  custom_integrations/ledfx/logo.png
  custom_integrations/ledfx/logo@2x.png
Labels: cla-signed

#2555 Add geocaching images for new core implementation
  core_integrations/geocaching/icon.png
  core_integrations/geocaching/icon@2x.png
  core_integrations/geocaching/logo.png
  core_integrations/geocaching/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3409 Add custom integration tekmar_482
  custom_integrations/tekmar_482/icon.png
  custom_integrations/tekmar_482/icon@2x.png
  custom_integrations/tekmar_482/logo.png
  custom_integrations/tekmar_482/logo@2x.png
Labels: cla-signed

#3410 Add IPCamLive icon and logo
  custom_integrations/ipcamlive/dark_logo.png
  custom_integrations/ipcamlive/dark_logo@2x.png
  custom_integrations/ipcamlive/icon.png
  custom_integrations/ipcamlive/icon@2x.png
  custom_integrations/ipcamlive/logo.png
  custom_integrations/ipcamlive/logo@2x.png
Labels: cla-signed

#3412 Add dark_ version for snmp core integration
  core_integrations/snmp/dark_icon.png
Labels: cla-signed

#3413 Add dark_ versions for caldav core integration
  core_integrations/caldav/dark_icon.png
  core_integrations/caldav/dark_icon@2x.png
Labels: cla-signed

#3414 Remove deprecated Raspberry Pi GPIO integration
  core_integrations/rpi_gpio
Labels: cla-signed, has-parent

#3132 Add icons for Raspberry Pi GPIO Integration as custom component
  custom_integrations/rpi_gpio/icon.png
  custom_integrations/rpi_gpio/icon@2x.png
  custom_integrations/rpi_gpio/logo.png
  custom_integrations/rpi_gpio/logo@2x.png
Labels: cla-signed

#3392 Add icon and logos for baf integration
  core_integrations/baf/icon.png
  core_integrations/baf/icon@2x.png
  core_integrations/baf/logo.png
  core_integrations/baf/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3419 Add Vaillant vSMART brand
  custom_integrations/vaillant_vsmart/icon.png
  custom_integrations/vaillant_vsmart/icon@2x.png
  custom_integrations/vaillant_vsmart/logo.png
  custom_integrations/vaillant_vsmart/logo@2x.png
Labels: cla-signed

#3417 Add images for Plum Sp. z o. o. brand.
  custom_integrations/plum_ecomax/icon.png
  custom_integrations/plum_ecomax/icon@2x.png
  custom_integrations/plum_ecomax/logo.png
  custom_integrations/plum_ecomax/logo@2x.png
Labels: cla-signed

#3415 Add custom integration solaredge_modbus_multi
  custom_integrations/solaredge_modbus_multi/icon.png
  custom_integrations/solaredge_modbus_multi/icon@2x.png
  custom_integrations/solaredge_modbus_multi/logo.png
  custom_integrations/solaredge_modbus_multi/logo@2x.png
Labels: cla-signed

#3416 Add images for Innova brand (custom integration)
  custom_integrations/innova/icon.png
  custom_integrations/innova/icon@2x.png
  custom_integrations/innova/logo.png
  custom_integrations/innova/logo@2x.png
Labels: cla-signed

#3372 Added SwitchBee logo to custom integration
  custom_integrations/switchbee/icon.png
  custom_integrations/switchbee/icon@2x.png
  custom_integrations/switchbee/logo.png
  custom_integrations/switchbee/logo@2x.png
Labels: cla-signed

#3400 Add yolink integration icons
  core_integrations/yolink/icon.png
  core_integrations/yolink/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3115 Add images for new core integration (laundrify)
  core_integrations/laundrify/dark_icon.png
  core_integrations/laundrify/dark_icon@2x.png
  core_integrations/laundrify/dark_logo.png
  core_integrations/laundrify/dark_logo@2x.png
  core_integrations/laundrify/icon.png
  core_integrations/laundrify/icon@2x.png
  core_integrations/laundrify/logo.png
  core_integrations/laundrify/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3421 Add Escea Images
  custom_integrations/escea/icon.png
  custom_integrations/escea/icon@2x.png
  custom_integrations/escea/logo.png
Labels: cla-signed

#3422 Add Nordnet
  custom_integrations/nordnet/icon.png
  custom_integrations/nordnet/icon@2x.png
  custom_integrations/nordnet/logo.png
  custom_integrations/nordnet/logo@2x.png
Labels: cla-signed

#3353 Add iAlarmXR integration icon
  core_integrations/ialarm_xr/icon.png
  core_integrations/ialarm_xr/icon@2x.png
  core_integrations/ialarm_xr/logo.png
  core_integrations/ialarm_xr/logo@2x.png
Labels: cla-signed, parent-merged, awaits-parent, has-parent, in-progress

#3424 Add Prix carburant custom integration
  custom_integrations/prix_carburant/icon.png
Labels: cla-signed

#3426 Add Yamaha YNCA custom integration
  custom_integrations/yamaha_ynca/icon.png
  custom_integrations/yamaha_ynca/icon@2x.png
  custom_integrations/yamaha_ynca/logo.png
  custom_integrations/yamaha_ynca/logo@2x.png
Labels: cla-signed

#3425 Add sma_webbox custom brand (https://github.com/jpcornil-git/HA-sma)
  custom_integrations/sma_webbox/icon.png
  custom_integrations/sma_webbox/icon@2x.png
  custom_integrations/sma_webbox/logo.png
  custom_integrations/sma_webbox/logo@2x.png
Labels: cla-signed

#3427 Add icons for Home Assistant 1-Wire via sysbus
  custom_integrations/onewire_sysbus/icon.png
  custom_integrations/onewire_sysbus/icon@2x.png
  custom_integrations/onewire_sysbus/logo.png
  custom_integrations/onewire_sysbus/logo@2x.png
Labels: cla-signed

#3428 Add bestway brand images
  custom_integrations/bestway/icon.png
  custom_integrations/bestway/icon@2x.png
  custom_integrations/bestway/logo.png
Labels: cla-signed

#3423 pawkakol/worlds-air-quality-index brand added
  custom_integrations/worlds_air_quality_index/icon.png
  custom_integrations/worlds_air_quality_index/icon@2x.png
  custom_integrations/worlds_air_quality_index/logo.png
  custom_integrations/worlds_air_quality_index/logo@2x.png
Labels: cla-signed, in-progress

#3431 Add wienerlinien integration images
  custom_integrations/wienerlinien/icon.png
  custom_integrations/wienerlinien/logo.png
Labels: cla-signed

#3430 Add gazpar icon (GrDF meter)
  custom_integrations/gazpar/icon.png
Labels: cla-signed, in-progress

#3433 Add iammeter_modbus
  custom_integrations/iammeter_modbus/icon.png
  custom_integrations/iammeter_modbus/icon@2x.png
  custom_integrations/iammeter_modbus/logo.png
Labels: cla-signed, in-progress

#3429 Add plex_recently_added icon
  custom_integrations/plex_recently_added/icon.png
  custom_integrations/plex_recently_added/icon@2x.png
Labels: cla-signed, in-progress

#3435 Home Assistant Blue Hardware Board
  hardware/boards/odroid_n2.png
Labels: cla-signed
