Repository home-assistant/brands, pull requests merged in 2022-02, with the labels that each got.

#3131 Added Tenda logos
  custom_integrations/tenda_tracker/icon.png
  custom_integrations/tenda_tracker/icon@2x.png
  custom_integrations/tenda_tracker/logo.png
  custom_integrations/tenda_tracker/logo@2x.png
Labels: cla-signed

#3123 add hasslife ico and logo
  custom_integrations/hasslife/icon.png
  custom_integrations/hasslife/icon@2x.png
Labels: cla-signed

#3135 Add systemd icons (http://brand.systemd.io/) for sdnotify integration.
  custom_integrations/sdnotify/icon.png
  custom_integrations/sdnotify/logo.png
Labels: cla-signed

#3137 Add wiz
  core_integrations/wiz/icon.png
  core_integrations/wiz/logo.png
Labels: cla-signed

#3138 Remove deprecated GNTP integration
  core_integrations/gntp/icon.png
Labels: cla-signed

#3140 Add dark variants
  custom_integrations/simpleicons/dark_icon.png
  custom_integrations/simpleicons/dark_icon@2x.png
Labels: cla-signed

#3143 Update Honeywell and Total Connect images
  core_integrations/honeywell/icon.png
  core_integrations/honeywell/icon@2x.png
  core_integrations/honeywell/logo.png
  core_integrations/honeywell/logo@2x.png
  core_integrations/totalconnect
  core_integrations/totalconnect/icon.png
  core_integrations/totalconnect/icon@2x.png
  core_integrations/totalconnect/logo.png
  core_integrations/totalconnect/logo@2x.png
Labels: cla-signed

#3144 Properly scale Lyric Logo
  core_integrations/lyric/logo.png
Labels: cla-signed

#3142 Fix ONKYO icons and logo to be brand compliant
  core_integrations/onkyo/dark_icon.png
  core_integrations/onkyo/dark_icon@2x.png
  core_integrations/onkyo/dark_logo.png
  core_integrations/onkyo/dark_logo@2x.png
  core_integrations/onkyo/icon.png
  core_integrations/onkyo/icon@2x.png
  core_integrations/onkyo/logo.png
  core_integrations/onkyo/logo@2x.png
Labels: cla-signed

#3147 Add Nanoleaf dark logos
  core_integrations/nanoleaf/dark_logo.png
  core_integrations/nanoleaf/dark_logo@2x.png
Labels: cla-signed

#3146 Add icon for dual smart thermostat
  custom_integrations/dual_smart_thermostat/icon.png
  custom_integrations/dual_smart_thermostat/icon@2x.png
Labels: cla-signed

#2759 Initial implementation of EnaSolar Integration
  custom_integrations/enasolar/icon.png
  custom_integrations/enasolar/icon@2x.png
  custom_integrations/enasolar/logo.png
  custom_integrations/enasolar/logo@2x.png
Labels: cla-signed

#3145 add icons for a new custom integration watchman
  custom_integrations/watchman/icon.png
  custom_integrations/watchman/icon@2x.png
Labels: cla-signed, in-progress

#3133 Add Z-Wave.Me logos
  core_integrations/zwave_me/icon.png
  core_integrations/zwave_me/icon@2x.png
  core_integrations/zwave_me/logo.png
  core_integrations/zwave_me/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3116 Fivem
  core_integrations/fivem/icon.png
  core_integrations/fivem/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3149 Add logo and icon for custom integration mjpeg-timelapse
  custom_integrations/mjpeg_timelapse/icon.png
  custom_integrations/mjpeg_timelapse/icon@2x.png
  custom_integrations/mjpeg_timelapse/logo.png
  custom_integrations/mjpeg_timelapse/logo@2x.png
Labels: cla-signed

#2757 Add brand images for Moehlenhoff Alpha2 integration
  core_integrations/moehlenhoff_alpha2/dark_logo.png
  core_integrations/moehlenhoff_alpha2/dark_logo@2x.png
  core_integrations/moehlenhoff_alpha2/icon.png
  core_integrations/moehlenhoff_alpha2/icon@2x.png
  core_integrations/moehlenhoff_alpha2/logo.png
  core_integrations/moehlenhoff_alpha2/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3160 Add tts and media_source icons
  core_integrations/media_source
  core_integrations/media_source/icon.png
  core_integrations/media_source/icon@2x.png
  core_integrations/tts
  core_integrations/tts/icon.png
  core_integrations/tts/icon@2x.png
Labels: cla-signed

#3134 feat: HACS Sunpower integration
  custom_integrations/sunpower/dark_logo.png
  custom_integrations/sunpower/dark_logo@2x.png
  custom_integrations/sunpower/logo.png
  custom_integrations/sunpower/logo@2x.png
Labels: cla-signed, in-progress

#3163 Added Pod Point
  custom_integrations/pod_point/dark_icon.png
  custom_integrations/pod_point/dark_icon@2x.png
  custom_integrations/pod_point/dark_logo.png
  custom_integrations/pod_point/dark_logo@2x.png
  custom_integrations/pod_point/icon.png
  custom_integrations/pod_point/icon@2x.png
  custom_integrations/pod_point/logo.png
  custom_integrations/pod_point/logo@2x.png
Labels: cla-signed

#3162 Added Swemail
  custom_integrations/swemail/icon.png
  custom_integrations/swemail/icon@2x.png
Labels: cla-signed, in-progress

#3165 Adding images for the custom integration with the OIOT site
  custom_integrations/oiot/icon.png
  custom_integrations/oiot/icon@2x.png
  custom_integrations/oiot/logo.png
  custom_integrations/oiot/logo@2x.png
Labels: cla-signed

#3125 Add nest protect logos
  custom_integrations/nest_protect/icon.png
  custom_integrations/nest_protect/icon@2x.png
  custom_integrations/nest_protect/logo.png
  custom_integrations/nest_protect/logo@2x.png
Labels: cla-signed, in-progress

#3166 Adding icons for pure energie integration
  core_integrations/pure_energie/icon.png
  core_integrations/pure_energie/icon@2x.png
  core_integrations/pure_energie/logo.png
  core_integrations/pure_energie/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3167 Added brand images for `gs_alarm` custom integration
  custom_integrations/gs_alarm/icon.png
  custom_integrations/gs_alarm/logo.png
Labels: cla-signed, in-progress

#3168 Add Radio Browser integration
  core_integrations/radio_browser/icon.png
  core_integrations/radio_browser/icon@2x.png
Labels: cla-signed, parent-merged, has-parent

#3156 Add OpenNEM
  custom_integrations/opennem/icon.png
  custom_integrations/opennem/icon@2x.png
Labels: cla-signed

#3154 Added 4heat
  custom_integrations/4heat/icon.png
  custom_integrations/4heat/icon@2x.png
Labels: cla-signed

#3153 Add brand images for custom component london_tfl
  custom_integrations/london_tfl/icon.png
  custom_integrations/london_tfl/icon@2x.png
  custom_integrations/london_tfl/logo.png
  custom_integrations/london_tfl/logo@2x.png
Labels: cla-signed

#3158 Add dlna_dms, duplicated from dlna_dmr
  core_integrations/dlna_dms/icon.png
  core_integrations/dlna_dms/icon@2x.png
  core_integrations/dlna_dms/logo.png
  core_integrations/dlna_dms/logo@2x.png
Labels: cla-signed, has-parent

#3151 Added dabblerdk_powermeterreader
  custom_integrations/dabblerdk_powermeterreader/icon.png
  custom_integrations/dabblerdk_powermeterreader/icon@2x.png
Labels: cla-signed

#3141 add dark variants
  custom_integrations/hhs_vertretungsplan/dark_icon.png
  custom_integrations/hhs_vertretungsplan/dark_icon@2x.png
Labels: cla-signed

#3164 Add goecharger_mqtt
  custom_integrations/goecharger_mqtt/icon.png
  custom_integrations/goecharger_mqtt/icon@2x.png
  custom_integrations/goecharger_mqtt/logo.png
  custom_integrations/goecharger_mqtt/logo@2x.png
Labels: cla-signed

#3176 Add abfallplus icons and logos
  custom_integrations/abfallplus/icon.png
  custom_integrations/abfallplus/icon@2x.png
  custom_integrations/abfallplus/logo.png
  custom_integrations/abfallplus/logo@2x.png
Labels: cla-signed

#3177 Add DRK Blutspende icons and logos
  custom_integrations/drkblutspende/icon.png
  custom_integrations/drkblutspende/icon@2x.png
  custom_integrations/drkblutspende/logo.png
  custom_integrations/drkblutspende/logo@2x.png
Labels: cla-signed

#3155 Added mypv
  custom_integrations/mypv/icon.png
  custom_integrations/mypv/logo.png
  custom_integrations/mypv/logo@2x.png
Labels: cla-signed, in-progress

#3178 Add Dacia icons and logos
  core_integrations/dacia/icon.png
  core_integrations/dacia/icon@2x.png
  core_integrations/dacia/logo.png
  core_integrations/dacia/logo@2x.png
Labels: cla-signed

#3179 Add icon for Fire Protection HU
  custom_integrations/fire_protection_hu/icon.png
Labels: cla-signed, in-progress

#3181 Remove deprecated APNS integration
  core_integrations/apns
Labels: cla-signed, has-parent

#3190 Remove deprecated Time of Flight integration
  core_integrations/tof
Labels: cla-signed, cleanup, has-parent

#3182 Remove deprecated BeagleBone Black GPIO integration
  core_integrations/bbb_gpio/icon.png
  core_integrations/bbb_gpio/icon@2x.png
  core_integrations/bbb_gpio/logo.png
  core_integrations/bbb_gpio/logo@2x.png
Labels: cla-signed, cleanup, has-parent

#3183 Remove deprecated BH1750 integration
  core_integrations/bh1750/logo.png
Labels: cla-signed, cleanup, has-parent

#3189 Remove deprecated Blinkt! integration
  core_integrations/blinkt
Labels: cla-signed, cleanup, has-parent

#3192 Remove deprecated Orange Pi GPIO integration
  core_integrations/orangepi_gpio/icon.png
  core_integrations/orangepi_gpio/icon@2x.png
  core_integrations/orangepi_gpio/logo.png
  core_integrations/orangepi_gpio/logo@2x.png
Labels: cla-signed, cleanup, has-parent

#3194 Remove deprecated MH-Z19 CO2 Sensor integration
  core_integrations/mhz19/logo.png
Labels: cla-signed, cleanup

#3193 Remove deprecated Bosch BME280 Environmental Sensor integration
  core_integrations/bme280
Labels: cla-signed, cleanup

#3191 Remove deprecated Sensirion SHT31 integration
  core_integrations/sht31/icon.png
  core_integrations/sht31/icon@2x.png
  core_integrations/sht31/logo.png
  core_integrations/sht31/logo@2x.png
Labels: cla-signed, cleanup, has-parent

#3180 Add solax_modbus icons
  custom_integrations/solax_modbus/icon.png
  custom_integrations/solax_modbus/icon@2x.png
  custom_integrations/solax_modbus/logo.png
  custom_integrations/solax_modbus/logo@2x.png
Labels: cla-signed, in-progress

#3199 ADD: Jellyfin dark
  core_integrations/jellyfin/dark_logo.png
  core_integrations/jellyfin/dark_logo@2x.png
Labels: cla-signed

#3212 Add PGNiG images
  custom_integrations/pgnig_gas_sensor/icon.png
  custom_integrations/pgnig_gas_sensor/icon@2x.png
Labels: cla-signed

#3213 add icons for ha_hatch integration
  custom_integrations/ha_hatch/icon.png
  custom_integrations/ha_hatch/icon@2x.png
Labels: cla-signed

#3201 ADD: pocketcast dark
  core_integrations/pocketcasts/dark_logo.png
  core_integrations/pocketcasts/dark_logo@2x.png
Labels: cla-signed

#3211 Add iDiamant by Netatmo custom integration images
  custom_integrations/idiamant/icon.png
  custom_integrations/idiamant/icon@2x.png
  custom_integrations/idiamant/logo.png
  custom_integrations/idiamant/logo@2x.png
Labels: cla-signed, in-progress

#3202 Remove deprecated Bosch BME680 Environmental Sensor integration
  core_integrations/bme680
Labels: cla-signed, parent-merged, cleanup, has-parent

#3198 Remove deprecated Piglow integration
  core_integrations/piglow/icon.png
  core_integrations/piglow/icon@2x.png
  core_integrations/piglow/logo.png
  core_integrations/piglow/logo@2x.png
Labels: cla-signed, parent-merged, cleanup, has-parent

#3195 Remove deprecated pigpio Daemon PWM LED integration
  core_integrations/rpi_gpio_pwm
Labels: cla-signed, parent-merged, cleanup, has-parent

#3208 Remove deprecated MCP23017 I/O Expander integration
  core_integrations/mcp23017/icon.png
  core_integrations/mcp23017/icon@2x.png
  core_integrations/mcp23017/logo.png
  core_integrations/mcp23017/logo@2x.png
Labels: cla-signed, cleanup, has-parent

#3204 Remove deprecated Enviro pHAT integration
  core_integrations/envirophat/logo.png
Labels: cla-signed, cleanup, has-parent

#3206 Add Life Time Fitness
  custom_integrations/lifetime_fitness/icon.png
  custom_integrations/lifetime_fitness/icon@2x.png
  custom_integrations/lifetime_fitness/logo.png
  custom_integrations/lifetime_fitness/logo@2x.png
Labels: cla-signed

#3139 Tasmota: add dark variants
  core_integrations/tasmota/dark_icon.png
  core_integrations/tasmota/dark_icon@2x.png
  core_integrations/tasmota/dark_logo.png
  core_integrations/tasmota/dark_logo@2x.png
Labels: cla-signed

#3148 add logo and icon for Zimi custom component
  custom_integrations/zimi/icon.png
  custom_integrations/zimi/icon@2x.png
  custom_integrations/zimi/logo.png
  custom_integrations/zimi/logo@2x.png
Labels: cla-signed
