Repository home-assistant/brands, pull requests merged in 2022-03, with the labels that each got.

#3217 Restore mcp23017 brand in custom_integrations (removed from core_inte…
  custom_integrations/mcp23017/icon.png
  custom_integrations/mcp23017/icon@2x.png
  custom_integrations/mcp23017/logo.png
  custom_integrations/mcp23017/logo@2x.png
Labels: cla-signed

#3216 Update Polly icons
  core_integrations/amazon_polly/icon.png
  core_integrations/amazon_polly/icon@2x.png
Labels: cla-signed

#3157 Add backup icon
  core_integrations/backup/icon.png
Labels: cla-signed, awaits-parent, has-parent

#3220 Initial upload xbee logos+icons
  core_integrations/xbee/icon.png
  core_integrations/xbee/icon@2x.png
  core_integrations/xbee/logo.png
  core_integrations/xbee/logo@2x.png
Labels: cla-signed

#3215 Remove deprecated Raspihats integration
  core_integrations/raspihats/icon.png
  core_integrations/raspihats/icon@2x.png
  core_integrations/raspihats/logo.png
  core_integrations/raspihats/logo@2x.png
Labels: cla-signed, parent-merged, cleanup, has-parent

#3221 Upload Logos+Icons Firmata (cleaned up/redrawn from firmata.org)
  core_integrations/firmata/icon.png
  core_integrations/firmata/icon@2x.png
  core_integrations/firmata/logo.png
  core_integrations/firmata/logo@2x.png
Labels: cla-signed

#3224 Initial upload Kankun Logo/Icon
  core_integrations/kankun/icon.png
Labels: cla-signed

#3226 ADD: mopidy
  custom_integrations/mopidy/icon.png
  custom_integrations/mopidy/icon@2x.png
Labels: cla-signed

#3227 Add icons for the update integration
  core_integrations/update/icon.png
  core_integrations/update/icon@2x.png
Labels: cla-signed

#3214 Adding the images for the custom Delonghi Primadonna integration
  custom_integrations/delonghi_primadonna/icon.png
  custom_integrations/delonghi_primadonna/icon@2x.png
  custom_integrations/delonghi_primadonna/logo.png
  custom_integrations/delonghi_primadonna/logo@2x.png
Labels: cla-signed, in-progress

#3238 Added electrolux_status images
  custom_integrations/electrolux_status/icon.png
  custom_integrations/electrolux_status/icon@2x.png
  custom_integrations/electrolux_status/logo.png
  custom_integrations/electrolux_status/logo@2x.png
Labels: cla-signed

#3237 ADD: Rhasspy
  custom_integrations/rhasspy/dark_logo.png
  custom_integrations/rhasspy/dark_logo@2x.png
  custom_integrations/rhasspy/icon.png
  custom_integrations/rhasspy/icon@2x.png
  custom_integrations/rhasspy/logo.png
  custom_integrations/rhasspy/logo@2x.png
Labels: cla-signed

#3236 rename bodymiscale logo to icon
  custom_integrations/bodymiscale/icon.png
  custom_integrations/bodymiscale/icon@2x.png
Labels: cla-signed

#3231 Add icon and logo for Sbanken
  custom_integrations/sbanken/icon.png
  custom_integrations/sbanken/icon@2x.png
  custom_integrations/sbanken/logo.png
  custom_integrations/sbanken/logo@2x.png
Labels: cla-signed

#3230 Add only icon images for kontomierz integration
  custom_integrations/kontomierz_sensor/icon.png
  custom_integrations/kontomierz_sensor/icon@2x.png
Labels: cla-signed

#3239 Add rainforest emu-2
  custom_integrations/rainforest_emu_2/icon.png
  custom_integrations/rainforest_emu_2/icon@2x.png
  custom_integrations/rainforest_emu_2/logo.png
  custom_integrations/rainforest_emu_2/logo@2x.png
Labels: cla-signed

#3234 Add Kaleidescape images
  core_integrations/kaleidescape/dark_icon.png
  core_integrations/kaleidescape/dark_logo.png
  core_integrations/kaleidescape/icon.png
  core_integrations/kaleidescape/logo.png
Labels: cla-signed, awaits-parent, has-parent

#3249 Add Greenwave Reality images
  core_integrations/greenwave/icon.png
  core_integrations/greenwave/icon@2x.png
  core_integrations/greenwave/logo.png
  core_integrations/greenwave/logo@2x.png
Labels: cla-signed

#3248 Add LIRC Images
  core_integrations/lirc/icon.png
  core_integrations/lirc/icon@2x.png
  core_integrations/lirc/logo.png
  core_integrations/lirc/logo@2x.png
Labels: cla-signed

#3240 safety_signing
  custom_integrations/safety_signing/icon.png
  custom_integrations/safety_signing/icon@2x.png
  custom_integrations/safety_signing/logo.png
  custom_integrations/safety_signing/logo@2x.png
Labels: cla-signed, in-progress

#3243 Add icon for radioactivity_hu
  custom_integrations/radioactivity_hu/icon.png
Labels: cla-signed

#3247 Add Neuro Energy Images
  core_integrations/neurio_energy/icon.png
  core_integrations/neurio_energy/icon@2x.png
  core_integrations/neurio_energy/logo.png
  core_integrations/neurio_energy/logo@2x.png
Labels: cla-signed

#3232 Add Airzone icons
  core_integrations/airzone/dark_icon.png
  core_integrations/airzone/dark_icon@2x.png
  core_integrations/airzone/dark_logo.png
  core_integrations/airzone/dark_logo@2x.png
  core_integrations/airzone/icon.png
  core_integrations/airzone/icon@2x.png
  core_integrations/airzone/logo.png
  core_integrations/airzone/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3203 Remove deprecated PCAL9535A I/O Expander integration
  core_integrations/pcal9535a/logo.png
Labels: cla-signed, parent-merged, cleanup, has-parent

#3210 Remove deprecated PiFace Digital I/O (PFIO) integration
  core_integrations/rpi_pfio
Labels: cla-signed, parent-merged

#3271 Add icon and logo for custom component metnowcast
  custom_integrations/metnowcast/icon.png
  custom_integrations/metnowcast/icon@2x.png
  custom_integrations/metnowcast/logo.png
  custom_integrations/metnowcast/logo@2x.png
Labels: cla-signed

#3272 Add icon and logo for custom component rinnaitouch
  custom_integrations/rinnaitouch/icon.png
  custom_integrations/rinnaitouch/icon@2x.png
  custom_integrations/rinnaitouch/logo.png
  custom_integrations/rinnaitouch/logo@2x.png
Labels: cla-signed, in-progress

#3270 airzonecloud: move to custom_integrations
  custom_integrations/airzonecloud/dark_icon.png
  custom_integrations/airzonecloud/dark_icon@2x.png
  custom_integrations/airzonecloud/dark_logo.png
  custom_integrations/airzonecloud/dark_logo@2x.png
  custom_integrations/airzonecloud/icon.png
  custom_integrations/airzonecloud/icon@2x.png
  custom_integrations/airzonecloud/logo.png
  custom_integrations/airzonecloud/logo@2x.png
Labels: cla-signed

#3196 Remove deprecated Media Player Classic Home Cinema (MPC-HC) integration
  core_integrations/mpchc/icon.png
  core_integrations/mpchc/icon@2x.png
Labels: cla-signed, cleanup

#3251 Add aREST images
  core_integrations/arest/icon.png
  core_integrations/arest/icon@2x.png
Labels: cla-signed, in-progress

#3268 Moved hdmi-cec to hdmi_cec
  core_integrations/hdmi_cec/icon.png
  core_integrations/hdmi_cec/icon@2x.png
  core_integrations/hdmi_cec/logo.png
  core_integrations/hdmi_cec/logo@2x.png
Labels: cla-signed, in-progress

#3250 Add Facebox images
  core_integrations/facebox/icon.png
  core_integrations/facebox/icon@2x.png
  core_integrations/facebox/logo.png
  core_integrations/facebox/logo@2x.png
Labels: cla-signed, in-progress

#3253 Add Brunt images
  core_integrations/brunt/icon.png
  core_integrations/brunt/icon@2x.png
  core_integrations/brunt/logo.png
  core_integrations/brunt/logo@2x.png
Labels: cla-signed, in-progress

#3255 Add Concord232 Images
  core_integrations/concord232/icon.png
  core_integrations/concord232/icon@2x.png
  core_integrations/concord232/logo.png
  core_integrations/concord232/logo@2x.png
Labels: cla-signed, in-progress

#3256 Add Doods images
  core_integrations/doods/icon.png
  core_integrations/doods/icon@2x.png
Labels: cla-signed, in-progress

#3258 Add eq3btsmart images
  core_integrations/eq3btsmart/icon.png
  core_integrations/eq3btsmart/icon@2x.png
  core_integrations/eq3btsmart/logo.png
  core_integrations/eq3btsmart/logo@2x.png
Labels: cla-signed, in-progress

#3259 Add FinTS Images
  core_integrations/fints/icon.png
  core_integrations/fints/icon@2x.png
  core_integrations/fints/logo.png
  core_integrations/fints/logo@2x.png
Labels: cla-signed, in-progress

#3261 Add Horizon Images
  core_integrations/horizon/icon.png
  core_integrations/horizon/icon@2x.png
Labels: cla-signed, in-progress

#3262 Add iGlo images
  core_integrations/iglo/icon.png
  core_integrations/iglo/icon@2x.png
Labels: cla-signed, in-progress

#3264 Add modem_callerid images
  core_integrations/modem_callerid/icon.png
  core_integrations/modem_callerid/icon@2x.png
  core_integrations/modem_callerid/logo.png
  core_integrations/modem_callerid/logo@2x.png
Labels: cla-signed, in-progress

#3265 Add Obihai images
  core_integrations/obihai/icon.png
  core_integrations/obihai/icon@2x.png
  core_integrations/obihai/logo.png
  core_integrations/obihai/logo@2x.png
Labels: cla-signed, in-progress

#3266 Add oem images
  core_integrations/oem/icon.png
  core_integrations/oem/icon@2x.png
  core_integrations/oem/logo.png
  core_integrations/oem/logo@2x.png
Labels: cla-signed, in-progress

#3257 Add Enigma2 images
  core_integrations/enigma2/icon.png
  core_integrations/enigma2/icon@2x.png
  core_integrations/enigma2/logo.png
  core_integrations/enigma2/logo@2x.png
Labels: cla-signed, in-progress

#3269 Remove deprecated OpenZWave integration
  core_integrations/ozw
Labels: cla-signed, parent-merged, awaits-parent, cleanup, has-parent

#3209 Remove deprecated Raspberry Pi RF integration
  core_integrations/rpi_rf
Labels: parent-merged, cleanup, has-parent

#3207 Remove deprecated Bosch BMP280 Environmental Sensor integration
  core_integrations/bmp280/icon.png
  core_integrations/bmp280/icon@2x.png
  core_integrations/bmp280/logo.png
  core_integrations/bmp280/logo@2x.png
Labels: cla-signed, parent-merged, cleanup, has-parent

#3175 Add icons for Raspberry Pi RF Integration as custom component
  custom_integrations/rpi_rf/icon.png
  custom_integrations/rpi_rf/icon@2x.png
  custom_integrations/rpi_rf/logo.png
  custom_integrations/rpi_rf/logo@2x.png
Labels: cla-signed

#3275 Add mythicbeastsdns images
  core_integrations/mythicbeastsdns/icon.png
  core_integrations/mythicbeastsdns/icon@2x.png
  core_integrations/mythicbeastsdns/logo.png
  core_integrations/mythicbeastsdns/logo@2x.png
Labels: cla-signed

#3276 Add lw12wifi images
  core_integrations/lw12wifi/icon.png
  core_integrations/lw12wifi/icon@2x.png
  core_integrations/lw12wifi/logo.png
  core_integrations/lw12wifi/logo@2x.png
Labels: cla-signed

#3277 Add greeneye_monitor images
  core_integrations/greeneye_monitor/icon.png
  core_integrations/greeneye_monitor/icon@2x.png
  core_integrations/greeneye_monitor/logo.png
  core_integrations/greeneye_monitor/logo@2x.png
Labels: cla-signed

#3279 Add arwn link to rfxtrx
  core_integrations/arwn
Labels: cla-signed

#3281 add domain for mila
  custom_integrations/mila/icon.png
  custom_integrations/mila/logo.png
Labels: cla-signed, cla-error

#3282 Add domain for Correios
  custom_integrations/correios/icon.png
  custom_integrations/correios/logo.png
Labels: cla-signed

#3284 Symlink derivative to homeassistant
  core_integrations/derivative
Labels: cla-signed

#3285 Add Landroid Cloud brand icons
  custom_integrations/landroid_cloud/icon.png
  custom_integrations/landroid_cloud/icon@2x.png
Labels: cla-signed

#3197 Remove deprecated (old) Z-Wave integration
  core_integrations/zwave_js
  core_integrations/zwave_js/icon.png
  core_integrations/zwave_js/icon@2x.png
  core_integrations/zwave_js/logo.png
  core_integrations/zwave_js/logo@2x.png
Labels: cla-signed, parent-merged

#2742 Add branding for tomorrow.io by symlinking to climacell
  core_integrations/tomorrowio
Labels: cla-signed, awaits-parent, has-parent

#3289 Remove SmartHab brand assets
  core_integrations/smarthab/icon.png
  core_integrations/smarthab/icon@2x.png
  core_integrations/smarthab/logo.png
  core_integrations/smarthab/logo@2x.png
Labels: cla-signed

#3288 Add Anycubic Icon/Logo
  custom_integrations/anycubic_wifi/icon.png
  custom_integrations/anycubic_wifi/icon@2x.png
  custom_integrations/anycubic_wifi/logo.png
  custom_integrations/anycubic_wifi/logo@2x.png
Labels: cla-signed

#3273 Sjofartsverket viva
  custom_integrations/sjofartsverket_viva/icon.png
Labels: cla-signed, in-progress

#3292 Add geo_location symlink
  core_integrations/geo_location
Labels: cla-signed

#3294 Add Islamic prayer times images
  core_integrations/islamic_prayer_times/icon.png
  core_integrations/islamic_prayer_times/icon@2x.png
Labels: cla-signed

#3295 Add LimitlessLED images
  core_integrations/limitlessled/icon.png
  core_integrations/limitlessled/icon@2x.png
Labels: cla-signed

#3296 Add Asterisk Icon/Logo
  custom_integrations/asterisk/icon.png
  custom_integrations/asterisk/logo.png
Labels: cla-signed

#3290 Add cpuspeed icons
  core_integrations/cpuspeed/icon.png
  core_integrations/cpuspeed/icon@2x.png
Labels: cla-signed, in-progress

#3291 Add hddtemp images
  core_integrations/hddtemp/icon.png
  core_integrations/hddtemp/icon@2x.png
Labels: cla-signed, in-progress

#3293 Add derivative images
  core_integrations/derivative
  core_integrations/derivative/icon.png
  core_integrations/derivative/icon@2x.png
Labels: cla-signed, in-progress

#3297 Docs: Add info cache release in major versions
  README.md
Labels: cla-signed

#3298 Add Browser Mod Icons
  custom_integrations/browser_mod/dark_icon.png
  custom_integrations/browser_mod/dark_icon@2x.png
  custom_integrations/browser_mod/icon.png
  custom_integrations/browser_mod/icon@2x.png
Labels: cla-signed

#3299 Add Drivvo Icon/Logo
  custom_integrations/drivvo/dark_logo.png
  custom_integrations/drivvo/icon.png
  custom_integrations/drivvo/icon@2x.png
  custom_integrations/drivvo/logo.png
Labels: cla-signed

#3300 Add custom component miwifi
  custom_integrations/miwifi/icon.png
  custom_integrations/miwifi/icon@2x.png
  custom_integrations/miwifi/logo.png
  custom_integrations/miwifi/logo@2x.png
Labels: cla-signed

#3283 Symlink switch_as_x to switch
  core_integrations/switch_as_x
Labels: cla-signed, parent-merged, has-parent

#3301 Added energidataservice icons
  custom_integrations/energidataservice/icon.png
  custom_integrations/energidataservice/icon@2x.png
Labels: cla-signed

#3036 Add brand for Wevolor controller for Levolor blinds
  custom_integrations/wevolor/icon.png
  custom_integrations/wevolor/icon@2x.png
  custom_integrations/wevolor/logo.png
  custom_integrations/wevolor/logo@2x.png
Labels: cla-signed

#3124 Adding PECO logo and icon
  core_integrations/peco/icon.png
  core_integrations/peco/logo.png
Labels: cla-signed, parent-merged, awaits-parent, has-parent

#3304 Move hahm to homematicip_local
  custom_integrations/homematicip_local/dark_logo.png
  custom_integrations/homematicip_local/dark_logo@2x.png
  custom_integrations/homematicip_local/icon.png
  custom_integrations/homematicip_local/icon@2x.png
  custom_integrations/homematicip_local/logo.png
  custom_integrations/homematicip_local/logo@2x.png
Labels: cla-signed

#3303 Add FPL Icons and logos
  custom_integrations/fpl/icon.png
  custom_integrations/fpl/icon@2x.png
  custom_integrations/fpl/logo.png
  custom_integrations/fpl/logo@2x.png
Labels: cla-signed, in-progress

#3306 Add icons/logos to Track
  custom_integrations/trakt/icon.png
  custom_integrations/trakt/icon@2x.png
  custom_integrations/trakt/logo.png
  custom_integrations/trakt/logo@2x.png
Labels: cla-signed

#3307 Added icons for ics_calendar
  custom_integrations/ics_calendar/icon.png
  custom_integrations/ics_calendar/icon@2x.png
Labels: cla-signed

#2501 Move vulcan icons to core integrations
  core_integrations/vulcan/icon.png
  core_integrations/vulcan/icon@2x.png
  core_integrations/vulcan/logo.png
  core_integrations/vulcan/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3184 Move cozytouch from custom integrations to core integrations
  core_integrations/cozytouch/icon.png
  core_integrations/cozytouch/icon@2x.png
  core_integrations/cozytouch/logo.png
  core_integrations/cozytouch/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3185 Add Hi Kumo icons
  core_integrations/hi_kumo/icon.png
  core_integrations/hi_kumo/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3186 Add Rexel Energyeasy Connect icons
  core_integrations/rexel/icon.png
  core_integrations/rexel/icon@2x.png
Labels: cla-signed

#3187 Add Nexity Eugenie icons
  core_integrations/nexity/icon.png
  core_integrations/nexity/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3311 Remove deprecated Updater integration
  core_integrations/updater/icon.png
  core_integrations/updater/icon@2x.png
Labels: cla-signed, cleanup, has-parent
