Repository home-assistant/brands, pull requests merged in 2022-06, with the labels that each got.

#3438 Add Haier brand for custom integration
  custom_integrations/haier/icon.png
  custom_integrations/haier/icon@2x.png
  custom_integrations/haier/logo.png
  custom_integrations/haier/logo@2x.png
Labels: cla-signed, cla-error

#3444 Deleting iAlarmXR logos
  core_integrations/ialarm_xr/icon.png
  core_integrations/ialarm_xr/icon@2x.png
  core_integrations/ialarm_xr/logo.png
  core_integrations/ialarm_xr/logo@2x.png
Labels: cla-signed

#3441 Add custom integration cololight images
  custom_integrations/cololight/icon.png
  custom_integrations/cololight/logo.png
Labels: cla-signed

#3442 New brand files for Sensibo
  core_integrations/sensibo/icon.png
  core_integrations/sensibo/icon@2x.png
  core_integrations/sensibo/logo.png
  core_integrations/sensibo/logo@2x.png
Labels: cla-signed

#3445 custom integration elkbledom
  custom_integrations/elkbledom/icon.png
  custom_integrations/elkbledom/icon@2x.png
  custom_integrations/elkbledom/logo.png
  custom_integrations/elkbledom/logo@2x.png
Labels: cla-signed

#3446 Add Frank Energie icon and logo
  custom_integrations/frank_energie/icon.png
  custom_integrations/frank_energie/logo.png
  custom_integrations/frank_energie/logo@2x.png
Labels: cla-signed

#3447 adds Rivian for custom integration
  custom_integrations/rivian/icon.png
  custom_integrations/rivian/logo.png
Labels: cla-signed

#3450 add Saures integration
  custom_integrations/sauresha/icon.png
  custom_integrations/sauresha/icon@2x.png
  custom_integrations/sauresha/logo.png
  custom_integrations/sauresha/logo@2x.png
Labels: cla-signed

#3449 Add brand files for the custom integration `ezviz_plug`
  custom_integrations/ezviz_plug/icon.png
  custom_integrations/ezviz_plug/icon@2x.png
  custom_integrations/ezviz_plug/logo.png
  custom_integrations/ezviz_plug/logo@2x.png
Labels: cla-signed

#3452 Add brand files for custom integration `edge_tts`
  custom_integrations/edge_tts/icon.png
  custom_integrations/edge_tts/icon@2x.png
  custom_integrations/edge_tts/logo.png
  custom_integrations/edge_tts/logo@2x.png
Labels: cla-signed, in-progress

#3455 Added Morningstar sensor icons and logos
  custom_integrations/morningstar/icon.png
  custom_integrations/morningstar/icon@2x.png
  custom_integrations/morningstar/logo.png
  custom_integrations/morningstar/logo@2x.png
Labels: cla-signed

#3456 Update icon for yandex_smart_home custom integration
  custom_integrations/yandex_smart_home/icon.png
  custom_integrations/yandex_smart_home/icon@2x.png
Labels: cla-signed, in-progress

#3436 Add BVG (Berlin public transport) custom integration brand images
  custom_integrations/bvg_berlin_public_transport/icon.png
  custom_integrations/bvg_berlin_public_transport/icon@2x.png
  custom_integrations/bvg_berlin_public_transport/logo.png
  custom_integrations/bvg_berlin_public_transport/logo@2x.png
Labels: cla-signed

#3462 add senertec images
  custom_integrations/senertec/icon.png
  custom_integrations/senertec/logo.png
Labels: cla-signed

#3458 add aerogarden icons
  custom_integrations/aerogarden/icon.png
Labels: cla-signed, in-progress

#3466 add linksys_velop images
  custom_integrations/linksys_velop/dark_icon.png
  custom_integrations/linksys_velop/dark_icon@2x.png
  custom_integrations/linksys_velop/dark_logo.png
  custom_integrations/linksys_velop/dark_logo@2x.png
  custom_integrations/linksys_velop/icon.png
  custom_integrations/linksys_velop/icon@2x.png
  custom_integrations/linksys_velop/logo.png
  custom_integrations/linksys_velop/logo@2x.png
Labels: cla-signed

#3463 add solarfocus custom integration
  custom_integrations/solarfocus/icon.png
  custom_integrations/solarfocus/icon@2x.png
  custom_integrations/solarfocus/logo.png
  custom_integrations/solarfocus/logo@2x.png
Labels: cla-signed

#3470 Add logo for PowUnity BikeTrax custom integration
  custom_integrations/biketrax/icon.png
  custom_integrations/biketrax/icon@2x.png
Labels: cla-signed

#3474 Add dark images for cololight custom integration
  custom_integrations/cololight/dark_icon.png
  custom_integrations/cololight/dark_logo.png
Labels: cla-signed

#3473 feat: Added icons for first_bus custom integration
  custom_integrations/first_bus/icon.png
  custom_integrations/first_bus/icon@2x.png
Labels: cla-signed

#3464 Add custom integration divera
  custom_integrations/divera/icon.png
  custom_integrations/divera/icon@2x.png
  custom_integrations/divera/logo.png
  custom_integrations/divera/logo@2x.png
Labels: cla-signed

#3467 Update odroid_n2.png name
  hardware/boards/hardkernel_odroid-n2.png
Labels: cla-signed

#3469 add brand for custom integration estudna
  custom_integrations/estudna/icon.png
  custom_integrations/estudna/logo.png
  custom_integrations/estudna/logo@2x.png
Labels: cla-signed

#3471 add foodsharing custom integration icon
  custom_integrations/foodsharing/icon.png
Labels: cla-signed

#3468 add virginmedia_tv images
  custom_integrations/virginmedia_tv/icon.png
  custom_integrations/virginmedia_tv/icon@2x.png
Labels: cla-signed, in-progress

#3460 Add Luxaflex images
  core_integrations/luxaflex/icon.png
  core_integrations/luxaflex/icon@2x.png
  core_integrations/luxaflex/logo.png
  core_integrations/luxaflex/logo@2x.png
Labels: cla-signed, in-progress

#3472 feat: Added icons for octopus_energy custom integration
  custom_integrations/octopus_energy/icon.png
  custom_integrations/octopus_energy/icon@2x.png
Labels: cla-signed

#3479 Hunter Douglas icon update
  core_integrations/hunterdouglas_powerview/icon.png
  core_integrations/hunterdouglas_powerview/icon@2x.png
Labels: cla-signed

#3480 add icons for blebox_shutterbox_tilt custom_integration
  custom_integrations/blebox_shutterbox_tilt/logo.png
  custom_integrations/blebox_shutterbox_tilt/logo@2x.png
Labels: cla-signed

#3483 Add HA Yellow Image
  hardware/boards/homeassistant_yellow.png
Labels: cla-signed

#3482 Add precoscombustiveis logo and icons
  custom_integrations/precoscombustiveis/icon.png
  custom_integrations/precoscombustiveis/icon@2x.png
  custom_integrations/precoscombustiveis/logo.png
  custom_integrations/precoscombustiveis/logo@2x.png
Labels: cla-signed

#3485 Add Mealie icon
  custom_integrations/mealie/icon.png
Labels: cla-needed

#3481 Add Dremel 3D Idea Builder Printer logo and icon
  custom_integrations/dremel_3d_printer/icon.png
  custom_integrations/dremel_3d_printer/icon@2x.png
  custom_integrations/dremel_3d_printer/logo.png
  custom_integrations/dremel_3d_printer/logo@2x.png
Labels: cla-signed

#3465 Add GCE rfplayer
  custom_integrations/rfplayer/icon.png
  custom_integrations/rfplayer/icon@2x.png
  custom_integrations/rfplayer/logo.png
Labels: cla-signed

#3486 Add back digital loggers brand
  core_integrations/digitalloggers/icon.png
  core_integrations/digitalloggers/icon@2x.png
Labels: cla-signed, parent-merged, has-parent

#3490 Add ipify
  custom_integrations/ipify/dark_icon.png
  custom_integrations/ipify/icon.png
Labels: cla-signed

#3491 prepare for adding integration ecopower_dynamic_grid_prices
  custom_integrations/ecopower_dynamic_grid_prices/icon.png
  custom_integrations/ecopower_dynamic_grid_prices/icon@2x.png
  custom_integrations/ecopower_dynamic_grid_prices/logo.png
  custom_integrations/ecopower_dynamic_grid_prices/logo@2x.png
Labels: cla-signed

#3487 Update dremel_3d_printer logo and icon
  custom_integrations/dremel_3d_printer/icon.png
  custom_integrations/dremel_3d_printer/icon@2x.png
  custom_integrations/dremel_3d_printer/logo.png
  custom_integrations/dremel_3d_printer/logo@2x.png
Labels: cla-signed

#3497 Update Blue image to be square
  hardware/boards/hardkernel_odroid-n2.png
Labels: cla-signed

#3496 Add Coverflex logo and icon
  custom_integrations/coverflex/icon.png
  custom_integrations/coverflex/icon@2x.png
  custom_integrations/coverflex/logo.png
  custom_integrations/coverflex/logo@2x.png
Labels: cla-signed, in-progress

#3499 add brand files for seven
  custom_integrations/seven/icon.png
  custom_integrations/seven/logo.png
Labels: cla-signed
