Repository home-assistant/brands, pull requests merged in 2022-11, with the labels that each got.

#3823 Add hra_recycling integration
  custom_integrations/hra_recycling/icon.png
  custom_integrations/hra_recycling/icon@2x.png
Labels: Hacktoberfest, hacktoberfest-accepted

#3819 Add images for viva custom integration
  custom_integrations/viva/icon.png
  custom_integrations/viva/icon@2x.png
  custom_integrations/viva/logo.png
  custom_integrations/viva/logo@2x.png
Labels: Hacktoberfest, hacktoberfest-accepted

#3600 Add logos for the LIVISI integration
  custom_integrations/livisi/dark_logo.png
  custom_integrations/livisi/dark_logo@2x.png
  custom_integrations/livisi/icon.png
  custom_integrations/livisi/icon@2x.png
  custom_integrations/livisi/logo.png
  custom_integrations/livisi/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3818 Add diematic_3_c230_eco for custom integration of a Dedietrich boiler
  custom_integrations/diematic_3_c230_eco/icon.png
  custom_integrations/diematic_3_c230_eco/icon@2x.png
  custom_integrations/diematic_3_c230_eco/logo.png
  custom_integrations/diematic_3_c230_eco/logo@2x.png
Labels: Hacktoberfest, in-progress, hacktoberfest-accepted

#3794 Add UbiWizz icons
  core_integrations/ubiwizz/icon.png
  core_integrations/ubiwizz/icon@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent, hacktoberfest-accepted

#3793 Add Simu Livein2 icons
  core_integrations/simu/icon.png
  core_integrations/simu/icon@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent, hacktoberfest-accepted

#3792 Add Hexaom icon files
  core_integrations/hexaom/icon.png
  core_integrations/hexaom/icon@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent, hacktoberfest-accepted

#3791 Add Brandt Smart Control brand
  core_integrations/brandt/icon.png
  core_integrations/brandt/icon@2x.png
  core_integrations/brandt/logo.png
  core_integrations/brandt/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent, hacktoberfest-accepted

#3597 Graphics for a new integration for air-Q devices (air quality sensors)
  core_integrations/airq/dark_logo.png
  core_integrations/airq/dark_logo@2x.png
  core_integrations/airq/icon.png
  core_integrations/airq/icon@2x.png
  core_integrations/airq/logo.png
  core_integrations/airq/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3827 Add icons for RuuviTag BLE
  core_integrations/ruuvitag_ble/dark_icon.png
  core_integrations/ruuvitag_ble/dark_icon@2x.png
  core_integrations/ruuvitag_ble/dark_logo.png
  core_integrations/ruuvitag_ble/dark_logo@2x.png
  core_integrations/ruuvitag_ble/icon.png
  core_integrations/ruuvitag_ble/icon@2x.png
  core_integrations/ruuvitag_ble/logo.png
  core_integrations/ruuvitag_ble/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent

#3835 Add icon for new custom integration revogi
  custom_integrations/revogi/icon.png
Labels: in-progress

#3846 Add icons for esxi_stats custom integration
  custom_integrations/esxi_stats/icon.png
  custom_integrations/esxi_stats/icon@2x.png
Labels: in-progress

#3854 Added Shopping list with grocy icons
  custom_integrations/shopping_list_with_grocy/icon.png
  custom_integrations/shopping_list_with_grocy/icon@2x.png
  custom_integrations/shopping_list_with_grocy/logo.png
  custom_integrations/shopping_list_with_grocy/logo@2x.png
Labels: in-progress

#3855 Add icons for china_southern_power_grid_stat custom integration
  custom_integrations/china_southern_power_grid_stat/icon.png
  custom_integrations/china_southern_power_grid_stat/icon@2x.png
Labels: in-progress

#3868 Add sensirion_ble branding
  core_integrations/sensirion_ble/icon.png
  core_integrations/sensirion_ble/icon@2x.png
  core_integrations/sensirion_ble/logo.png
  core_integrations/sensirion_ble/logo@2x.png
Labels: parent-merged

#3377 Add brand elro
  custom_integrations/elro_connects/icon.png
  custom_integrations/elro_connects/icon@2x.png
  custom_integrations/elro_connects/logo.png
  custom_integrations/elro_connects/logo@2x.png
Labels: cla-signed

#3866 Add icons and logo for lennoxS30 custom integration
  custom_integrations/lennoxs30/icon.png
  custom_integrations/lennoxs30/icon@2x.png
  custom_integrations/lennoxs30/logo.png
  custom_integrations/lennoxs30/logo@2x.png
Labels: in-progress

#3826 Add yamaha brand icons
  core_brands/yamaha/dark_icon.png
  core_brands/yamaha/dark_icon@2x.png
  core_brands/yamaha/dark_logo.png
  core_brands/yamaha/dark_logo@2x.png
  core_brands/yamaha/icon.png
  core_brands/yamaha/icon@2x.png
  core_brands/yamaha/logo.png
  core_brands/yamaha/logo@2x.png
Labels: parent-merged, Hacktoberfest

#3825 Update musiccast product icons
  core_integrations/yamaha_musiccast/dark_logo.png
  core_integrations/yamaha_musiccast/dark_logo@2x.png
  core_integrations/yamaha_musiccast/icon.png
  core_integrations/yamaha_musiccast/icon@2x.png
  core_integrations/yamaha_musiccast/logo.png
  core_integrations/yamaha_musiccast/logo@2x.png
Labels: Hacktoberfest, in-progress, hacktoberfest-accepted

#3874 Add victron brand images
  custom_integrations/victron/icon.png
  custom_integrations/victron/icon@2x.png
  custom_integrations/victron/logo.png
  custom_integrations/victron/logo@2x.png
Labels: in-progress

#3871 Added heliotherm heat pump as custom_integration logos in ha_heliotherm domain folder
  custom_integrations/ha_heliotherm/icon.png
  custom_integrations/ha_heliotherm/icon@2x.png
  custom_integrations/ha_heliotherm/logo.png
  custom_integrations/ha_heliotherm/logo@2x.png
Labels: in-progress

#3655 Add HomeWhiz logo
  custom_integrations/homewhiz/dark_icon.png
  custom_integrations/homewhiz/dark_icon@2x.png
  custom_integrations/homewhiz/dark_logo.png
  custom_integrations/homewhiz/dark_logo@2x.png
  custom_integrations/homewhiz/icon.png
  custom_integrations/homewhiz/icon@2x.png
  custom_integrations/homewhiz/logo.png
  custom_integrations/homewhiz/logo@2x.png
Labels: cla-signed, in-progress

#3864 Add `text` platform brand
  core_integrations/text/icon.txt
Labels: awaits-parent, has-parent

#3876 Updated Microsoft Teams logo & icon
  core_integrations/msteams/icon.png
  core_integrations/msteams/icon@2x.png
  core_integrations/msteams/logo.png
  core_integrations/msteams/logo@2x.png
Labels: in-progress

#3751 Add local calendar core integration brand icon
  core_integrations/local_calendar/icon.txt
Labels: awaits-parent, Hacktoberfest, has-parent, hacktoberfest-accepted
