Repository home-assistant/brands, pull requests merged in 2023-09, with the labels that each got.

#4552 Add icon/logo for a new brand AeonMatrix and for its new integration Yardian
  core_integrations/yardian/icon.png
  core_integrations/yardian/icon@2x.png
  core_integrations/yardian/logo.png
  core_integrations/yardian/logo@2x.png
Labels: parent-merged, has-parent

#4658 Add brand images for Apple WeatherKit
  core_integrations/weatherkit/dark_logo.png
  core_integrations/weatherkit/dark_logo@2x.png
  core_integrations/weatherkit/icon.png
  core_integrations/weatherkit/logo.png
  core_integrations/weatherkit/logo@2x.png
Labels: parent-merged, awaits-parent

#4654 Add idasen_desk symlink
  core_integrations/idasen_desk
Labels: awaits-parent, has-parent

#4680 Add ecoforest logo and icon to core integrations
  core_integrations/ecoforest/icon.png
  core_integrations/ecoforest/icon@2x.png
  core_integrations/ecoforest/logo.png
  core_integrations/ecoforest/logo@2x.png
Labels: parent-merged

#4716 Add icon and logo for medcom_ble integration
  core_integrations/medcom_ble/icon.png
  core_integrations/medcom_ble/icon@2x.png
  core_integrations/medcom_ble/logo.png
  core_integrations/medcom_ble/logo@2x.png
Labels: awaits-parent, has-parent

#4732 Move Weatherflow from custom into core
  core_integrations/weatherflow/icon.png
  core_integrations/weatherflow/icon@2x.png
  core_integrations/weatherflow/logo.png
  core_integrations/weatherflow/logo@2x.png
Labels: parent-merged
