Repository home-assistant/brands, pull requests merged in 2023-07, with the labels that each got.

#4256 Create icon for Opower integration
  core_integrations/opower/icon.png
Labels: awaits-parent, has-parent

#4494 Add gardena bluetooth brand
  core_integrations/gardena_bluetooth/icon.png
  core_integrations/gardena_bluetooth/icon@2x.png
  core_integrations/gardena_bluetooth/logo.png
  core_integrations/gardena_bluetooth/logo@2x.png
Labels: awaits-parent, has-parent

#4508 Add Permobil logo and icon
  core_integrations/permobil/dark_logo.png
  core_integrations/permobil/dark_logo@2x.png
  core_integrations/permobil/icon.png
  core_integrations/permobil/icon@2x.png
  core_integrations/permobil/logo.png
  core_integrations/permobil/logo@2x.png
Labels: has-parent

#4555 Add event entity
  core_integrations/event/icon.txt
Labels: has-parent

#3943 add electric kiwi icons
  core_integrations/electric_kiwi/icon.png
  core_integrations/electric_kiwi/icon@2x.png
Labels: awaits-parent, has-parent

#4569 Add duotecno brands
  core_integrations/duotecno/icon.png
  core_integrations/duotecno/icon@2x.png
  core_integrations/duotecno/logo.png
  core_integrations/duotecno/logo@2x.png
Labels: has-parent

#4567 Add pegel_online brands
  core_integrations/pegel_online/icon.png
  core_integrations/pegel_online/logo.png
Labels: awaits-parent, has-parent

#4571 Add icons for opower supported utilities
  core_integrations/atlanticcityelectric/icon.png
  core_integrations/atlanticcityelectric/icon@2x.png
  core_integrations/bge/icon.png
  core_integrations/bge/icon@2x.png
  core_integrations/comed/icon.png
  core_integrations/comed/icon@2x.png
  core_integrations/delmarva/icon.png
  core_integrations/delmarva/icon@2x.png
  core_integrations/evergy/icon.png
  core_integrations/evergy/icon@2x.png
  core_integrations/evergy/logo.png
  core_integrations/evergy/logo@2x.png
  core_integrations/peco_opower/icon.png
  core_integrations/peco_opower/icon@2x.png
  core_integrations/pepco/icon.png
  core_integrations/pepco/icon@2x.png
  core_integrations/pge/icon.png
  core_integrations/pge/icon@2x.png
  core_integrations/pge/logo.png
  core_integrations/pge/logo@2x.png
  core_integrations/pse/icon.png
  core_integrations/pse/icon@2x.png
  core_integrations/pse/logo.png
  core_integrations/pse/logo@2x.png
Labels: awaits-parent, has-parent

#4415 Move Schlage branding images from custom to core
  core_integrations/schlage/icon.png
  core_integrations/schlage/icon@2x.png
  core_integrations/schlage/logo.png
  core_integrations/schlage/logo@2x.png
Labels: parent-merged, has-parent
