Repository home-assistant/brands, pull requests merged in 2023-12, with the labels that each got.

#4888 Add holiday calendar icon
  core_integrations/holiday/icon.txt
Labels: parent-merged, has-parent

#4950 Add icon and logo for Seattle City Light
  core_integrations/scl/icon.png
  core_integrations/scl/icon@2x.png
  core_integrations/scl/logo.png
  core_integrations/scl/logo@2x.png
Labels: awaits-parent, has-parent

#3339 Add OSO Energy brand
  core_integrations/osoenergy/icon.png
  core_integrations/osoenergy/icon@2x.png
  core_integrations/osoenergy/logo.png
  core_integrations/osoenergy/logo@2x.png
Labels: cla-signed, parent-merged, has-parent

#4133 Add Sun WEG brand
  core_integrations/sunweg/dark_icon.png
  core_integrations/sunweg/dark_icon@2x.png
  core_integrations/sunweg/dark_logo.png
  core_integrations/sunweg/dark_logo@2x.png
  core_integrations/sunweg/icon.png
  core_integrations/sunweg/icon@2x.png
  core_integrations/sunweg/logo.png
  core_integrations/sunweg/logo@2x.png
Labels: awaits-parent, has-parent

#4938 Move Tessie from Custom to Core
  core_integrations/tessie/icon.png
  core_integrations/tessie/icon@2x.png
  core_integrations/tessie/logo.png
  core_integrations/tessie/logo@2x.png
Labels: awaits-parent, has-parent

#5002 Add Tailwind integration
  core_integrations/tailwind/icon.png
  core_integrations/tailwind/icon@2x.png
  core_integrations/tailwind/logo.png
  core_integrations/tailwind/logo@2x.png
Labels: parent-merged, has-parent

#5013 Add icons for AEP utilities supported by Opower
  core_integrations/aepohio/icon.png
  core_integrations/aepohio/icon@2x.png
  core_integrations/aeptexas/icon.png
  core_integrations/aeptexas/icon@2x.png
  core_integrations/appalachianpower/icon.png
  core_integrations/appalachianpower/icon@2x.png
  core_integrations/indianamichiganpower/icon.png
  core_integrations/indianamichiganpower/icon@2x.png
  core_integrations/kentuckypower/icon.png
  core_integrations/kentuckypower/icon@2x.png
  core_integrations/psoklahoma/icon.png
  core_integrations/psoklahoma/icon@2x.png
  core_integrations/swepco/icon.png
  core_integrations/swepco/icon@2x.png
Labels: parent-merged

#4861 Add icon and logo for Vogel's MotionMount integration
  core_integrations/motionmount/icon.png
  core_integrations/motionmount/icon@2x.png
  core_integrations/motionmount/logo.png
  core_integrations/motionmount/logo@2x.png
Labels: awaits-parent, has-parent

#4525 add new Brand Refoss
  core_integrations/refoss/icon.png
  core_integrations/refoss/icon@2x.png
  core_integrations/refoss/logo.png
  core_integrations/refoss/logo@2x.png
Labels: awaits-parent, has-parent

#4908 Add DROP brand
  core_integrations/drop_connect/icon.png
  core_integrations/drop_connect/icon@2x.png
  core_integrations/drop_connect/logo.png
  core_integrations/drop_connect/logo@2x.png
Labels: parent-merged, awaits-parent, has-parent

#4495 Add Midea Logos
  core_brands/ccm15/icon.png
  core_brands/ccm15/icon@2x.png
  core_brands/ccm15/logo.png
  core_brands/ccm15/logo@2x.png
Labels: awaits-parent, has-parent

#5033 Move aeptexas to aep_texas
  core_integrations/aep_texas/icon.png
  core_integrations/aep_texas/icon@2x.png
Labels: awaits-parent, has-parent

#5032 Move aepohio to aep_ohio
  core_integrations/aep_ohio/icon.png
  core_integrations/aep_ohio/icon@2x.png
Labels: awaits-parent, has-parent

#4822 Move tedee icons to core
  core_integrations/tedee/icon.png
  core_integrations/tedee/icon@2x.png
  core_integrations/tedee/logo.png
  core_integrations/tedee/logo@2x.png
Labels: parent-merged, awaits-parent, Hacktoberfest, has-parent
