Repository home-assistant/brands, pull requests merged in 2023-03, with the labels that each got.

#4135 Add brand images for custom integration `span_panel`
  custom_integrations/span_panel/dark_icon.png
  custom_integrations/span_panel/dark_icon@2x.png
  custom_integrations/span_panel/dark_logo.png
  custom_integrations/span_panel/dark_logo@2x.png
  custom_integrations/span_panel/icon.png
  custom_integrations/span_panel/icon@2x.png
  custom_integrations/span_panel/logo.png
  custom_integrations/span_panel/logo@2x.png
Labels: in-progress

#4155 Add Vermont Castings Icon
  core_integrations/vermont_castings/icon.png
  core_integrations/vermont_castings/icon@2x.png
Labels: parent-merged, has-parent

#4206 Visuals for new custom integration: Vattenfall InCharge
  custom_integrations/incharge/icon.png
  custom_integrations/incharge/icon@2x.png
  custom_integrations/incharge/logo.png
  custom_integrations/incharge/logo@2x.png
Labels: has-parent

#4023 Move Magicseaweed logos to custom_integrations
  custom_integrations/magicseaweed/icon.png
  custom_integrations/magicseaweed/icon@2x.png
  custom_integrations/magicseaweed/logo.png
  custom_integrations/magicseaweed/logo@2x.png
Labels: in-progress

#4157 Add Quadrafire Brand Icon
  core_integrations/quadrafire/icon.png
Labels: has-parent

#4258 Remove xbox_live integration
  core_integrations/xbox_live/icon.png
  core_integrations/xbox_live/icon@2x.png
  core_integrations/xbox_live/logo.png
  core_integrations/xbox_live/logo@2x.png
Labels: awaits-parent, has-parent
