Repository home-assistant/brands, pull requests merged in 2023-06, with the labels that each got.

#4424 Move Dremel logo to core integrations
  core_integrations/dremel_3d_printer/icon.png
  core_integrations/dremel_3d_printer/icon@2x.png
  core_integrations/dremel_3d_printer/logo.png
  core_integrations/dremel_3d_printer/logo@2x.png
Labels: parent-merged, has-parent

#2740 Add Discovergy logo and icon
  core_integrations/discovergy/icon.png
  core_integrations/discovergy/icon@2x.png
  core_integrations/discovergy/logo.png
  core_integrations/discovergy/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#2826 Renson icons + logos
  core_integrations/renson/icon.png
  core_integrations/renson/icon@2x.png
  core_integrations/renson/logo.png
  core_integrations/renson/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#4452 Remove senseme brand
  core_integrations/senseme/icon.png
  core_integrations/senseme/icon@2x.png
  core_integrations/senseme/logo.png
  core_integrations/senseme/logo@2x.png
Labels: awaits-parent, has-parent
