Repository home-assistant/brands, pull requests merged in 2023-01, with the labels that each got.

#3970 Add brand images for energyzero
  core_integrations/energyzero/icon.png
  core_integrations/energyzero/icon@2x.png
  core_integrations/energyzero/logo.png
  core_integrations/energyzero/logo@2x.png
Labels: awaits-parent, has-parent

#3907 Use core_integrations/upnp icons for upnp_availability
  custom_integrations/upnp_availability/dark_icon.png
  custom_integrations/upnp_availability/dark_icon@2x.png
  custom_integrations/upnp_availability/dark_logo.png
  custom_integrations/upnp_availability/dark_logo@2x.png
  custom_integrations/upnp_availability/icon.png
  custom_integrations/upnp_availability/icon@2x.png
  custom_integrations/upnp_availability/logo.png
  custom_integrations/upnp_availability/logo@2x.png
Labels: in-progress

#4002 Add logo for ANWB Energie virtual integration
  core_integrations/anwb_energie/logo.png
  core_integrations/anwb_energie/logo@2x.png
Labels: awaits-parent, has-parent

#4007 OralB_hacs custom integration
  custom_integrations/oralb_hacs/icon.png
  custom_integrations/oralb_hacs/icon@2x.png
  custom_integrations/oralb_hacs/logo.png
  custom_integrations/oralb_hacs/logo@2x.png
Labels: in-progress

#4008 Add logo Mijndomein energie integration
  core_integrations/mijndomein_energie/icon.png
  core_integrations/mijndomein_energie/icon@2x.png
  core_integrations/mijndomein_energie/logo.png
  core_integrations/mijndomein_energie/logo@2x.png
Labels: awaits-parent, has-parent

#3925 Add assets for LD2410 BLE integration
  core_integrations/ld2410_ble/icon.png
  core_integrations/ld2410_ble/logo.png
Labels: parent-merged, has-parent

#4011 Add logos for growatt_server_hacs (direct copy of growatt_server from…
  custom_integrations/growatt_server_api/icon.png
  custom_integrations/growatt_server_api/icon@2x.png
  custom_integrations/growatt_server_api/logo.png
  custom_integrations/growatt_server_api/logo@2x.png
Labels: in-progress

#3617 Add Starlink images
  core_integrations/starlink/dark_icon.png
  core_integrations/starlink/dark_icon@2x.png
  core_integrations/starlink/dark_logo.png
  core_integrations/starlink/dark_logo@2x.png
  core_integrations/starlink/icon.png
  core_integrations/starlink/icon@2x.png
  core_integrations/starlink/logo.png
  core_integrations/starlink/logo@2x.png
Labels: cla-signed, awaits-parent, has-parent

#3878 Add Google Mail icons
  core_integrations/google_mail/dark_logo.png
  core_integrations/google_mail/dark_logo@2x.png
  core_integrations/google_mail/icon.png
  core_integrations/google_mail/icon@2x.png
  core_integrations/google_mail/logo.png
  core_integrations/google_mail/logo@2x.png
Labels: awaits-parent, has-parent

#3984 Convert ruuvitag_ble to a brand used for both ruuvi_gateway and ruuvitag_ble
  core_brands/ruuvi/dark_icon.png
  core_brands/ruuvi/dark_icon@2x.png
  core_brands/ruuvi/dark_logo.png
  core_brands/ruuvi/dark_logo@2x.png
  core_brands/ruuvi/icon.png
  core_brands/ruuvi/icon@2x.png
  core_brands/ruuvi/logo.png
  core_brands/ruuvi/logo@2x.png
  core_integrations/ruuvi_gateway
  core_integrations/ruuvitag_ble
Labels: awaits-parent, has-parent

#4017 Added Bambu Lab
  custom_integrations/bambu_lab/icon.png
  custom_integrations/bambu_lab/icon@2x.png
  custom_integrations/bambu_lab/logo.png
  custom_integrations/bambu_lab/logo@2x.png
Labels: in-progress

#4033 Adding brand phyn for new phyn custom integration
  custom_integrations/phyn/dark_icon.png
  custom_integrations/phyn/dark_icon@2x.png
  custom_integrations/phyn/icon.png
  custom_integrations/phyn/icon@2x.png
Labels: in-progress

#4034 Symlink bluetooth_adapters to bluetooth
  core_integrations/bluetooth_adapters
Labels: parent-merged

#4028 Add logo for Energie VanOns integration
  core_integrations/energie_vanons/icon.png
  core_integrations/energie_vanons/icon@2x.png
Labels: parent-merged, has-parent

#4030 Add icon and logo for Fire TV (virtual) integration
  core_integrations/fire_tv/icon.png
  core_integrations/fire_tv/icon@2x.png
  core_integrations/fire_tv/logo.png
  core_integrations/fire_tv/logo@2x.png
Labels: awaits-parent, has-parent

#4026 Added logos and icons for the mFi mPower integration
  custom_integrations/mfi_mpower/icon.png
  custom_integrations/mfi_mpower/icon@2x.png
  custom_integrations/mfi_mpower/logo.png
  custom_integrations/mfi_mpower/logo@2x.png
Labels: in-progress

#4039 Add EufyLife logo
  core_brands/eufy/icon.png
  core_brands/eufy/icon@2x.png
  core_brands/eufy/logo.png
  core_brands/eufy/logo@2x.png
  core_integrations/eufylife_ble/logo.png
  core_integrations/eufylife_ble/logo@2x.png
Labels: parent-merged, has-parent, in-progress

#4022 Add logo and icon for Remeha Home
  custom_integrations/remeha_home/dark_icon.png
  custom_integrations/remeha_home/dark_icon@2x.png
  custom_integrations/remeha_home/dark_logo.png
  custom_integrations/remeha_home/dark_logo@2x.png
  custom_integrations/remeha_home/icon.png
  custom_integrations/remeha_home/icon@2x.png
  custom_integrations/remeha_home/logo.png
  custom_integrations/remeha_home/logo@2x.png
Labels: in-progress

#3824 TP-Link Omada proposed integration logos
  core_integrations/tplink_omada/icon.png
  core_integrations/tplink_omada/icon@2x.png
  core_integrations/tplink_omada/logo.png
  core_integrations/tplink_omada/logo@2x.png
Labels: Hacktoberfest, hacktoberfest-accepted

#3908 Replace apple_airplayer symlink with a copy of the icons
  custom_integrations/apple_airplayer
  custom_integrations/apple_airplayer/dark_icon.png
  custom_integrations/apple_airplayer/dark_icon@2x.png
  custom_integrations/apple_airplayer/icon.png
  custom_integrations/apple_airplayer/icon@2x.png
  custom_integrations/apple_airplayer/logo.png
  custom_integrations/apple_airplayer/logo@2x.png
Labels: in-progress

#3937 Add eDIN+ icon and logo for edinplus custom component
  custom_integrations/edinplus/icon.png
  custom_integrations/edinplus/icon@2x.png
  custom_integrations/edinplus/logo.png
  custom_integrations/edinplus/logo@2x.png
Labels: in-progress

#4020 Removes OpenALPR Local integration
  core_integrations/openalpr_cloud
  core_integrations/openalpr_cloud/icon.png
  core_integrations/openalpr_cloud/icon@2x.png
  core_integrations/openalpr_cloud/logo.png
  core_integrations/openalpr_cloud/logo@2x.png
Labels: parent-merged, has-parent

#4037 telenet_telemeter custom HACS integration
  custom_integrations/telenet_telemeter/icon.png
  custom_integrations/telenet_telemeter/logo.png
Labels: in-progress

#3957 Add Stookwijzer
  core_integrations/stookwijzer/icon.png
  core_integrations/stookwijzer/icon@2x.png
  core_integrations/stookwijzer/logo.png
  core_integrations/stookwijzer/logo@2x.png
Labels: awaits-parent, has-parent

#4052 Pixometer
  custom_integrations/pixometer/icon.png
  custom_integrations/pixometer/logo.png
Labels: in-progress

#4054 Add icons for my custom integration oekofen_pellematic_compact
  custom_integrations/oekofen_pellematic_compact/icon.png
  custom_integrations/oekofen_pellematic_compact/icon@2x.png
Labels: in-progress

#4070 Remove Almond integration
  core_integrations/almond/icon.png
  core_integrations/almond/icon@2x.png
  core_integrations/almond/logo.png
  core_integrations/almond/logo@2x.png
Labels: cleanup, has-parent

#4072 Add OTBR assets
  core_integrations/otbr/icon.png
  core_integrations/otbr/logo.png
  core_integrations/otbr/logo@2x.png
Labels: parent-merged, has-parent

#4073 Add Thread assets
  core_integrations/thread/dark_logo.png
  core_integrations/thread/dark_logo@2x.png
  core_integrations/thread/icon.png
  core_integrations/thread/icon@2x.png
  core_integrations/thread/logo.png
  core_integrations/thread/logo@2x.png
Labels: parent-merged, has-parent

#4071 Add OpenAI
  core_integrations/openai_conversation/dark_icon.png
  core_integrations/openai_conversation/dark_icon@2x.png
  core_integrations/openai_conversation/dark_logo.png
  core_integrations/openai_conversation/dark_logo@2x.png
  core_integrations/openai_conversation/icon.png
  core_integrations/openai_conversation/icon@2x.png
  core_integrations/openai_conversation/logo.png
  core_integrations/openai_conversation/logo@2x.png
Labels: awaits-parent, has-parent

#4087 Add mikucare custom integration icons
  custom_integrations/mikucare/icon.png
  custom_integrations/mikucare/icon@2x.png
Labels: in-progress

#4057 Add Beckettlink Logos
  custom_integrations/beckettlink/icon.png
  custom_integrations/beckettlink/icon@2x.png
  custom_integrations/beckettlink/logo.png
  custom_integrations/beckettlink/logo@2x.png
Labels: in-progress
