Repository home-assistant/brands, pull requests merged in 2023-04, with the labels that each got.

#4297 Add icon for VoIP integration
  core_integrations/voip/icon.txt
Labels: has-parent

#4308 Remove Dark Sky
  core_integrations/darksky/icon.png
  core_integrations/darksky/icon@2x.png
  core_integrations/darksky/logo.png
  core_integrations/darksky/logo@2x.png
Labels: cleanup

#4119 Add icons for new rapt_ble core integration
  core_integrations/rapt_ble/dark_icon.png
  core_integrations/rapt_ble/dark_icon@2x.png
  core_integrations/rapt_ble/dark_logo.png
  core_integrations/rapt_ble/dark_logo@2x.png
  core_integrations/rapt_ble/icon.png
  core_integrations/rapt_ble/icon@2x.png
  core_integrations/rapt_ble/logo.png
  core_integrations/rapt_ble/logo@2x.png
Labels: awaits-parent, has-parent

#4159 Add Monessen Fireplace brand
  core_integrations/monessen/icon.png
  core_integrations/monessen/icon@2x.png
Labels: awaits-parent, has-parent

#4050 added branding for anova
  core_integrations/anova/icon.png
  core_integrations/anova/icon@2x.png
  core_integrations/anova/logo.png
  core_integrations/anova/logo@2x.png
Labels: awaits-parent, has-parent

#4227 Create Android TV Remote integration icons and logos
  core_integrations/androidtv_remote
Labels: awaits-parent, has-parent

#3861 Add `date` platform brand
  core_integrations/date/icon.txt
Labels: awaits-parent, has-parent

#3862 Add `time` platform brand
  core_integrations/time/icon.txt
Labels: awaits-parent, has-parent
