Repository home-assistant/brands, pull requests merged in 2023-11, with the labels that each got.

#4844 OSO Energy Community branding
  custom_integrations/osoenergy_community/icon.png
  custom_integrations/osoenergy_community/icon@2x.png
  custom_integrations/osoenergy_community/logo.png
  custom_integrations/osoenergy_community/logo@2x.png
Labels: Hacktoberfest

#4838 Icons for euribor_rates custom component
  custom_integrations/euribor_rates/icon.png
  custom_integrations/euribor_rates/icon@2x.png
Labels: Hacktoberfest

#4788 ACInfinity icon and logo
  custom_integrations/ACInfinity/icon.png
  custom_integrations/ACInfinity/icon@2x.png
  custom_integrations/ACInfinity/logo.png
Labels: Hacktoberfest

#4864 Remove MyQ Integration
  core_integrations/myq/icon.png
  core_integrations/myq/icon@2x.png
  core_integrations/myq/logo.png
  core_integrations/myq/logo@2x.png
Labels: awaits-parent, has-parent

#3235 Use icon@2x as logo@2x in case of a missing logo@2x and no dedicated logo is provided
  README.md
  scripts/build.sh
Labels: cla-signed

#4510 new integration: komfovent
  core_integrations/komfovent/icon.png
  core_integrations/komfovent/icon@2x.png
  core_integrations/komfovent/logo.png
Labels: awaits-parent, has-parent

#4842 Add Countdown images
  custom_integrations/countdown/icon.png
  custom_integrations/countdown/icon@2x.png
  custom_integrations/countdown/logo.png
  custom_integrations/countdown/logo@2x.png
Labels: Hacktoberfest

#4827 Adding Unifi Access logos
  custom_integrations/unifi_access/icon.png
  custom_integrations/unifi_access/icon@2x.png
  custom_integrations/unifi_access/logo.png
  custom_integrations/unifi_access/logo@2x.png
Labels: Hacktoberfest

#4309 Add Linear Garage Door brand icons
  core_integrations/linear_garage_door/icon.png
  core_integrations/linear_garage_door/icon@2x.png
  core_integrations/linear_garage_door/logo.png
  core_integrations/linear_garage_door/logo@2x.png
Labels: awaits-parent, has-parent

#4858 Add OurGroceries assets
  core_integrations/ourgroceries/icon.png
  core_integrations/ourgroceries/icon@2x.png
  core_integrations/ourgroceries/logo.png
Labels: awaits-parent, has-parent
