Repository home-assistant/brands, pull requests merged in 2023-10, with the labels that each got.

#4737 Add Ergomotion Smart Beds logo
  custom_integrations/ergomotion/icon.png
  custom_integrations/ergomotion/icon@2x.png
  custom_integrations/ergomotion/logo.png
  custom_integrations/ergomotion/logo@2x.png
Labels: Hacktoberfest

#4647 Add switchbot cloud integration
  core_brands/switchbot/icon.png
  core_brands/switchbot/logo.png
  core_brands/switchbot/logo@2x.png
  core_integrations/switchbot
  core_integrations/switchbot/icon.png
  core_integrations/switchbot/icon@2x.png
  core_integrations/switchbot/logo.png
  core_integrations/switchbot/logo@2x.png
  core_integrations/switchbot_cloud
  custom_integrations/switchbot_cloud/icon.png
  custom_integrations/switchbot_cloud/icon@2x.png
  custom_integrations/switchbot_cloud/logo.png
  custom_integrations/switchbot_cloud/logo@2x.png
Labels: parent-merged

#4749 Icon for UK Bin Collection Custom Component
  custom_integrations/uk_bin_collection/icon.png
  custom_integrations/uk_bin_collection/icon@2x.png
Labels: Hacktoberfest

#4745 Add bms_connector logos
  custom_integrations/bms_connector/icon.png
  custom_integrations/bms_connector/icon@2x.png
Labels: Hacktoberfest

#4743 Add egddistribuce images
  custom_integrations/egddistribuce/icon.png
  custom_integrations/egddistribuce/icon@2x.png
  custom_integrations/egddistribuce/logo.png
  custom_integrations/egddistribuce/logo@2x.png
Labels: Hacktoberfest

#4741 Add cover_time_based integration
  custom_integrations/cover_time_based/dark_icon.png
  custom_integrations/cover_time_based/dark_icon@2x.png
  custom_integrations/cover_time_based/icon.png
  custom_integrations/cover_time_based/icon@2x.png
Labels: Hacktoberfest

#4740 Add meteoam brand images
  custom_integrations/meteoam/icon.png
  custom_integrations/meteoam/icon@2x.png
Labels: Hacktoberfest

#4739 Added icons for davis_vantage
  custom_integrations/davis_vantage/icon.png
  custom_integrations/davis_vantage/icon@2x.png
Labels: Hacktoberfest

#4738 Added custom_component LifeSmart
  custom_integrations/lifesmart/icon.png
  custom_integrations/lifesmart/icon@2x.png
  custom_integrations/lifesmart/logo.png
  custom_integrations/lifesmart/logo@2x.png
Labels: Hacktoberfest

#4742 added icons for switchbotremote custom integration
  custom_integrations/switchbotremote/icon.png
  custom_integrations/switchbotremote/icon@2x.png
  custom_integrations/switchbotremote/logo.png
  custom_integrations/switchbotremote/logo@2x.png
Labels: Hacktoberfest

#4750 Add icons for `econnect_metronet` custom component
  custom_integrations/econnect_metronet/icon.png
  custom_integrations/econnect_metronet/icon@2x.png
  custom_integrations/econnect_metronet/logo.png
  custom_integrations/econnect_metronet/logo@2x.png
Labels: Hacktoberfest

#4744 Add logo for Eastron
  core_integrations/eastron/dark_logo.png
  core_integrations/eastron/logo.png
Labels: awaits-parent, Hacktoberfest, has-parent

#4751 Add openwrt icon PNG
  custom_integrations/openwrt/icon.png
  custom_integrations/openwrt/icon@2x.png
  custom_integrations/openwrt/logo.png
  custom_integrations/openwrt/logo@2x.png
Labels: Hacktoberfest

#4756 Add brains icon and logo
  custom_integrations/brains/icon.png
  custom_integrations/brains/icon@2x.png
  custom_integrations/brains/logo.png
  custom_integrations/brains/logo@2x.png
Labels: Hacktoberfest

#4752 Adds logo and icon for flichub
  custom_integrations/flichub/icon.png
  custom_integrations/flichub/logo.png
Labels: Hacktoberfest

#4757 Adding Webasto Connect logo and icons
  custom_integrations/webastoconnect/icon.png
  custom_integrations/webastoconnect/icon@2x.png
  custom_integrations/webastoconnect/logo.png
  custom_integrations/webastoconnect/logo@2x.png
Labels: Hacktoberfest

#4759 Adding brands for upcoming custom component - Culligan
  custom_integrations/culligan/icon.png
  custom_integrations/culligan/icon@2x.png
  custom_integrations/culligan/logo.png
  custom_integrations/culligan/logo@2x.png
Labels: Hacktoberfest

#4758 Add icons for speedport custom integration
  custom_integrations/speedport/dark_icon.png
  custom_integrations/speedport/dark_icon@2x.png
  custom_integrations/speedport/icon.png
  custom_integrations/speedport/icon@2x.png
  custom_integrations/speedport/logo.png
  custom_integrations/speedport/logo@2x.png
Labels: Hacktoberfest

#4762 Update Splunk
  core_integrations/splunk/dark_logo.png
  core_integrations/splunk/dark_logo@2x.png
  core_integrations/splunk/icon.png
  core_integrations/splunk/icon@2x.png
  core_integrations/splunk/logo.png
  core_integrations/splunk/logo@2x.png
Labels: Hacktoberfest

#4763 Add Cribl
  core_integrations/cribl/dark_logo.png
  core_integrations/cribl/icon.png
  core_integrations/cribl/logo.png
Labels: awaits-parent, Hacktoberfest, has-parent

#4760 Add icons and logos for thingwala_geyserwala_connect
  custom_integrations/thingwala_geyserwala_connect/icon.png
  custom_integrations/thingwala_geyserwala_connect/icon@2x.png
  custom_integrations/thingwala_geyserwala_connect/logo.png
  custom_integrations/thingwala_geyserwala_connect/logo@2x.png
Labels: Hacktoberfest

#4764 Add healthchecksio custom components Icons
  custom_integrations/healthchecksio/icon.png
  custom_integrations/healthchecksio/icon@2x.png
Labels: Hacktoberfest

#4761 Logo for ha_vscode custom integration
  custom_integrations/ha_vscode/icon.png
  custom_integrations/ha_vscode/icon@2x.png
Labels: Hacktoberfest

#4766 New custom_integration "patch" icons
  custom_integrations/patch/icon.png
  custom_integrations/patch/icon@2x.png
Labels: Hacktoberfest

#4768 Add icon for measureit custom integration
  measureit/icon.png
Labels: Hacktoberfest

#4770 Removed icon background and added dark icons for davis_vantage
  custom_integrations/davis_vantage/dark_icon.png
  custom_integrations/davis_vantage/dark_icon@2x.png
  custom_integrations/davis_vantage/icon.png
  custom_integrations/davis_vantage/icon@2x.png
Labels: Hacktoberfest

#4767 Add icons for portlandgeneral virtual integration
  core_integrations/portlandgeneral/icon.png
  core_integrations/portlandgeneral/icon@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent

#4775 Fix measureit ending up in root iso custom_integration
  custom_integrations/measureit/icon.png
Labels: Hacktoberfest

#4773 Remove Mazda brand
  core_integrations/mazda/icon.png
  core_integrations/mazda/icon@2x.png
Labels: Hacktoberfest

#4777 Add icon for oncharger custom component
  custom_integrations/oncharger/icon.png
  custom_integrations/oncharger/icon@2x.png
Labels: Hacktoberfest

#4778 Add momentary icon.
  custom_integrations/momentary/icon.png
Labels: Hacktoberfest

#4754 Add cloudflare_tunnel_monitor custom_component
  custom_integrations/cloudflare_tunnel_monitor/icon.png
  custom_integrations/cloudflare_tunnel_monitor/icon@2x.png
  custom_integrations/cloudflare_tunnel_monitor/logo.png
  custom_integrations/cloudflare_tunnel_monitor/logo@2x.png
Labels: Hacktoberfest

#4774 Add icon for Seeed Studio-SenseCAP
  custom_integrations/sensecap/icon.png
  custom_integrations/sensecap/icon@2x.png
  custom_integrations/sensecap/logo.png
Labels: Hacktoberfest

#4785 Add icon for termux api
  custom_integrations/termux_api/icon.png
  custom_integrations/termux_api/icon@2x.png
Labels: Hacktoberfest

#4783 Add volvoaaos icon
  custom_integrations/volvoaaos/icon.png
Labels: Hacktoberfest

#4780 Added logos to davis_vantage
  custom_integrations/davis_vantage/dark_logo.png
  custom_integrations/davis_vantage/logo.png
Labels: Hacktoberfest

#4781 Added logos to pvpc_energy
  custom_integrations/pvpc_energy/icon.png
  custom_integrations/pvpc_energy/icon@2x.png
Labels: Hacktoberfest

#4772 Add icon and logo for Bermuda custom integration
  custom_integrations/bermuda/dark_icon.png
  custom_integrations/bermuda/dark_icon@2x.png
  custom_integrations/bermuda/dark_logo.png
  custom_integrations/bermuda/dark_logo@2x.png
  custom_integrations/bermuda/icon.png
  custom_integrations/bermuda/icon@2x.png
  custom_integrations/bermuda/logo.png
  custom_integrations/bermuda/logo@2x.png
Labels: Hacktoberfest

#4776 Add Flexopus brand
  custom_integrations/flexopus/dark_icon.png
  custom_integrations/flexopus/dark_icon@2x.png
  custom_integrations/flexopus/dark_logo.png
  custom_integrations/flexopus/dark_logo@2x.png
  custom_integrations/flexopus/icon.png
  custom_integrations/flexopus/icon@2x.png
  custom_integrations/flexopus/logo.png
  custom_integrations/flexopus/logo@2x.png
Labels: Hacktoberfest

#4786 transparency and dark mode added
  custom_integrations/eeve_mower_willow/dark_icon.png
  custom_integrations/eeve_mower_willow/dark_icon@2x.png
  custom_integrations/eeve_mower_willow/icon.png
  custom_integrations/eeve_mower_willow/icon@2x.png
Labels: Hacktoberfest

#4793 Remove Shiftr brand
  core_integrations/shiftr/icon.png
  core_integrations/shiftr/icon@2x.png
  core_integrations/shiftr/logo.png
  core_integrations/shiftr/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent

#4795 New custom_integration "oref_alert" icons
  custom_integrations/oref_alert/icon.png
  custom_integrations/oref_alert/icon@2x.png
Labels: Hacktoberfest

#4805 Transparent background for "oref_alert"
  custom_integrations/oref_alert/icon.png
  custom_integrations/oref_alert/icon@2x.png
Labels: Hacktoberfest

#4804 Add aquahawk custom integrations images
  custom_integrations/aquahawk/icon.png
  custom_integrations/aquahawk/logo.png
Labels: Hacktoberfest

#4802 Add Icon for SenseCraft
  custom_integrations/sensecraft/icon.png
  custom_integrations/sensecraft/icon@2x.png
  custom_integrations/sensecraft/logo.png
  custom_integrations/sensecraft/logo@2x.png
Labels: Hacktoberfest

#4799 Add ina219_ups_hat custom integration icons
  custom_integrations/ina219_ups_hat/icon.png
  custom_integrations/ina219_ups_hat/icon@2x.png
Labels: Hacktoberfest

#4791 Add icon for smart_maic custom component
  custom_integrations/smart_maic/icon.png
  custom_integrations/smart_maic/icon@2x.png
Labels: Hacktoberfest

#4787 Add Terneo icon and logo
  custom_integrations/terneo/icon.png
  custom_integrations/terneo/icon@2x.png
  custom_integrations/terneo/logo.png
  custom_integrations/terneo/logo@2x.png
Labels: Hacktoberfest

#4808 Add Tuya Cloud Map Extractor Brand
  custom_integrations/tuya_cloud_map_extractor/icon.png
  custom_integrations/tuya_cloud_map_extractor/icon@2x.png
  custom_integrations/tuya_cloud_map_extractor/logo.png
  custom_integrations/tuya_cloud_map_extractor/logo@2x.png
Labels: Hacktoberfest

#4797 Adding icons for custom integration Atag One
  custom_integrations/atagone/icon.png
  custom_integrations/atagone/icon@2x.png
  custom_integrations/atagone/logo.png
  custom_integrations/atagone/logo@2x.png
Labels: Hacktoberfest

#4809 Add elevenlabs_tts brand
  custom_integrations/elevenlabs_tts/dark_icon.png
  custom_integrations/elevenlabs_tts/dark_icon@2x.png
  custom_integrations/elevenlabs_tts/dark_logo.png
  custom_integrations/elevenlabs_tts/dark_logo@2x.png
  custom_integrations/elevenlabs_tts/icon.png
  custom_integrations/elevenlabs_tts/icon@2x.png
  custom_integrations/elevenlabs_tts/logo.png
  custom_integrations/elevenlabs_tts/logo@2x.png
Labels: Hacktoberfest

#4796 Add icon for hvac_group custom integration
  custom_integrations/hvac_group/icon.png
  custom_integrations/hvac_group/icon@2x.png
Labels: Hacktoberfest

#3836 Add brand image for tami4 integration
  core_integrations/tami4/icon.png
  core_integrations/tami4/icon@2x.png
  core_integrations/tami4/logo.png
  core_integrations/tami4/logo@2x.png
Labels: awaits-parent, has-parent

#4807 Add beolink assets
  custom_integrations/beolink/icon.png
  custom_integrations/beolink/icon@2x.png
Labels: Hacktoberfest

#4682 Add icon for todo component
  core_integrations/todo/icon.txt
Labels: awaits-parent, has-parent

#4814 Rename safe_mode to recovery_mode
  core_integrations/recovery_mode/icon.txt
Labels: Hacktoberfest, has-parent

#4815 Added icons for metservice_weather
  custom_integrations/metservice_weather/icon.png
  custom_integrations/metservice_weather/icon@2x.png
  custom_integrations/metservice_weather/logo.png
  custom_integrations/metservice_weather/logo@2x.png
Labels: Hacktoberfest

#4813 Add Google Tasks icon
  core_integrations/google_tasks/icon.png
Labels: awaits-parent, Hacktoberfest

#4818 Add dark variants for improv_ble
  core_integrations/improv_ble/dark_icon.png
  core_integrations/improv_ble/dark_icon@2x.png
  core_integrations/improv_ble/dark_logo.png
  core_integrations/improv_ble/dark_logo@2x.png
Labels: Hacktoberfest

#4812 Add brand icon for local_todo component
  core_integrations/local_todo/icon.txt
Labels: awaits-parent, Hacktoberfest

#4821 Add brand icon and logo for ICONOMI custom component
  custom_integrations/iconomi/dark_icon.png
  custom_integrations/iconomi/dark_icon@2x.png
  custom_integrations/iconomi/dark_logo.png
  custom_integrations/iconomi/dark_logo@2x.png
  custom_integrations/iconomi/icon.png
  custom_integrations/iconomi/icon@2x.png
  custom_integrations/iconomi/logo.png
  custom_integrations/iconomi/logo@2x.png
Labels: Hacktoberfest

#4832 add custom component icons for soundtouchplus
  custom_integrations/soundtouchplus/icon.png
  custom_integrations/soundtouchplus/icon@2x.png
  custom_integrations/soundtouchplus/logo.png
  custom_integrations/soundtouchplus/logo@2x.png
Labels: Hacktoberfest

#4836 Add brand icon and logo for WundaSmart custom component
  custom_integrations/wundasmart/icon.png
  custom_integrations/wundasmart/icon@2x.png
  custom_integrations/wundasmart/logo.png
  custom_integrations/wundasmart/logo@2x.png
Labels: Hacktoberfest

#4834 Add icons for Alpha Innotec custom integration
  custom_integrations/alpha_innotec/icon.png
  custom_integrations/alpha_innotec/icon@2x.png
Labels: Hacktoberfest

#4829 Add icon and image for HA CoAp integration.
  custom_integrations/ha_coap/icon.png
  custom_integrations/ha_coap/icon@2x.png
  custom_integrations/ha_coap/logo.png
  custom_integrations/ha_coap/logo@2x.png
Labels: Hacktoberfest

#4825 Add Timing-Allow-origin CORS header
  netlify.toml
Labels: Hacktoberfest

#4830 Add icons for random entity integration
  custom_integrations/random_entity/icon.png
  custom_integrations/random_entity/icon@2x.png
Labels: Hacktoberfest

#4841 Icons for matkahuolto_tracking custom component
  custom_integrations/matkahuolto_tracking/icon.png
  custom_integrations/matkahuolto_tracking/icon@2x.png
Labels: Hacktoberfest

#4843 Add Orion images
  custom_integrations/orion/icon.png
  custom_integrations/orion/icon@2x.png
Labels: Hacktoberfest

#4837 Add Eeveemobility icons & logos
  custom_integrations/eeveemobility/dark_icon.png
  custom_integrations/eeveemobility/dark_icon@2x.png
  custom_integrations/eeveemobility/dark_logo.png
  custom_integrations/eeveemobility/dark_logo@2x.png
  custom_integrations/eeveemobility/icon.png
  custom_integrations/eeveemobility/icon@2x.png
  custom_integrations/eeveemobility/logo.png
  custom_integrations/eeveemobility/logo@2x.png
Labels: Hacktoberfest

#4840 Icons for posti_tracking custom component
  custom_integrations/posti_tracking/icon.png
  custom_integrations/posti_tracking/icon@2x.png
Labels: Hacktoberfest

#4839 Icons for fmi_waterlevel custom component
  custom_integrations/fmi_waterlevel/icon.png
  custom_integrations/fmi_waterlevel/icon@2x.png
Labels: Hacktoberfest

#4824 Add Yeelock icons
  custom_integrations/yeelock/icon.png
  custom_integrations/yeelock/icon@2x.png
  custom_integrations/yeelock/logo.png
  custom_integrations/yeelock/logo@2x.png
Labels: Hacktoberfest

#4826 Add ManageMyHealth icons
  custom_integrations/managemyhealth/dark_logo.png
  custom_integrations/managemyhealth/dark_logo@2x.png
  custom_integrations/managemyhealth/icon.png
  custom_integrations/managemyhealth/icon@2x.png
  custom_integrations/managemyhealth/logo.png
  custom_integrations/managemyhealth/logo@2x.png
Labels: Hacktoberfest
