Repository home-assistant/brands, pull requests merged in 2024-08, with the labels that each got.

#5704 Add ArtSound integration
  core_integrations/artsound/icon.png
  core_integrations/artsound/logo.png
Labels: parent-merged, has-parent

#5159 Add fujitsu_hvac integration images
  core_brands/fujitsu/icon.png
  core_brands/fujitsu/icon@2x.png
  core_brands/fujitsu/logo.png
  core_brands/fujitsu/logo@2x.png
  core_integrations/fujitsu_fglair
Labels: parent-merged, has-parent

#5709 Add Nice G.O. icons
  core_integrations/nice_go/icon.png
  core_integrations/nice_go/icon@2x.png
Labels: parent-merged

#5530 Branding for new SMLIGHT integration
  core_integrations/smlight/icon.png
  core_integrations/smlight/icon@2x.png
  core_integrations/smlight/logo.png
  core_integrations/smlight/logo@2x.png
Labels: awaits-parent, has-parent

#5766 Remove mailbox
  core_integrations/mailbox/icon.txt
Labels: awaits-parent, has-parent

#5633 Feature/deako
  core_integrations/deako/icon.png
  core_integrations/deako/icon@2x.png
  core_integrations/deako/logo.png
  core_integrations/deako/logo@2x.png
  custom_integrations/deako/icon.png
  custom_integrations/deako/icon@2x.png
Labels: awaits-parent, has-parent

#5808 Add new yale integration
  core_integrations/yale
Labels: parent-merged

#4958 Add icons and logos for Lektrico
  core_integrations/lektrico/dark_icon.png
  core_integrations/lektrico/dark_icon@2x.png
  core_integrations/lektrico/dark_logo.png
  core_integrations/lektrico/icon.png
  core_integrations/lektrico/icon@2x.png
  core_integrations/lektrico/logo.png
  core_integrations/lektrico/logo@2x.png
Labels: awaits-parent, has-parent

#5811 Add Google Photos logo
  core_integrations/google_photos/icon.png
  core_integrations/google_photos/icon@2x.png
Labels: awaits-parent

#5701 Add icon and logo for LG ThinQ integration
  core_integrations/lg_thinq/icon.png
  core_integrations/lg_thinq/icon@2x.png
  core_integrations/lg_thinq/logo.png
  core_integrations/lg_thinq/logo@2x.png
Labels: parent-merged, has-parent
