Repository home-assistant/brands, pull requests merged in 2024-02, with the labels that each got.

#5156 Add icon for Duquesne Light virtual integration
  core_integrations/duquesne_light/icon.png
  core_integrations/duquesne_light/icon@2x.png
Labels: awaits-parent, has-parent

#5173 Add icon for SamSam integration
  core_integrations/samsam/icon.png
  core_integrations/samsam/icon@2x.png
Labels: awaits-parent, has-parent

#4655 Move Husqvanra Automower branding images from custom to core
  core_integrations/husqvarna_automower/icon.png
  core_integrations/husqvarna_automower/icon@2x.png
  core_integrations/husqvarna_automower/logo.png
  core_integrations/husqvarna_automower/logo@2x.png
  custom_integrations/husqvarna_automower/icon.png
  custom_integrations/husqvarna_automower/icon@2x.png
Labels: parent-merged, awaits-parent, has-parent

#5185 Add tplink_tapo to core_integrations
  core_integrations/tplink_tapo/icon.png
  core_integrations/tplink_tapo/icon@2x.png
  core_integrations/tplink_tapo/logo.png
  core_integrations/tplink_tapo/logo@2x.png
Labels: parent-merged

#5225 Add microBees core integration brand images
  core_integrations/microbees/icon.png
  core_integrations/microbees/icon@2x.png
  core_integrations/microbees/logo.png
  core_integrations/microbees/logo@2x.png
Labels: parent-merged

#5052 Add webmin integration
  core_integrations/webmin/icon.png
  core_integrations/webmin/icon@2x.png
  core_integrations/webmin/logo.png
  core_integrations/webmin/logo@2x.png
Labels: parent-merged, awaits-parent, has-parent

#5035 Link new integration weatherflow_cloud to existing weatherflow
  core_brands/weatherflow/icon.png
  core_brands/weatherflow/icon@2x.png
  core_brands/weatherflow/logo.png
  core_brands/weatherflow/logo@2x.png
  core_integrations/weatherflow
  core_integrations/weatherflow_cloud
Labels: parent-merged
