Repository home-assistant/brands, pull requests merged in 2024-01, with the labels that each got.

#3762 Add Rainforest RAVEn integration
  core_brands/rainforest_automation/icon.png
  core_brands/rainforest_automation/icon@2x.png
  core_brands/rainforest_automation/logo.png
  core_brands/rainforest_automation/logo@2x.png
  core_integrations/rainforest_eagle
  core_integrations/rainforest_raven
Labels: awaits-parent, Hacktoberfest, has-parent, hacktoberfest-accepted

#3150 Add icon and logo for new Rabbit Air integration
  core_integrations/rabbitair/icon.png
  core_integrations/rabbitair/icon@2x.png
  core_integrations/rabbitair/logo.png
  core_integrations/rabbitair/logo@2x.png
Labels: cla-signed, parent-merged, awaits-parent, has-parent

#5055 Adding images for Epion integration
  core_integrations/epion/icon.png
  core_integrations/epion/icon@2x.png
  core_integrations/epion/logo.png
  core_integrations/epion/logo@2x.png
Labels: parent-merged, has-parent

#4798 Move lamarzocco icons to core
  core_integrations/lamarzocco/dark_icon.png
  core_integrations/lamarzocco/dark_icon@2x.png
  core_integrations/lamarzocco/icon.png
  core_integrations/lamarzocco/icon@2x.png
  core_integrations/lamarzocco/logo.png
  core_integrations/lamarzocco/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent

#5039 Add Govee Lights local
  core_integrations/govee_light_local/icon.png
  core_integrations/govee_light_local/icon@2x.png
  core_integrations/govee_light_local/logo.png
  core_integrations/govee_light_local/logo@2x.png
  custom_integrations/govee/icon.png
  custom_integrations/govee/icon@2x.png
  custom_integrations/govee/logo.png
  custom_integrations/govee/logo@2x.png
  custom_integrations/govee_lan/icon.png
  custom_integrations/govee_lan/icon@2x.png
  custom_integrations/govee_lan/logo.png
  custom_integrations/govee_lan/logo@2x.png
Labels: parent-merged

#5010 Add branding images for TechnoVE
  core_integrations/technove/icon.png
  core_integrations/technove/icon@2x.png
  core_integrations/technove/logo.png
  core_integrations/technove/logo@2x.png
Labels: awaits-parent, has-parent

#5073 Add analytics insights
  core_integrations/analytics_insights/icon.txt
Labels: awaits-parent, has-parent

#4605 Add bang_olufsen icons to core integrations
  core_integrations/bang_olufsen/dark_icon.png
  core_integrations/bang_olufsen/dark_icon@2x.png
  core_integrations/bang_olufsen/dark_logo.png
  core_integrations/bang_olufsen/dark_logo@2x.png
  core_integrations/bang_olufsen/icon.png
  core_integrations/bang_olufsen/icon@2x.png
  core_integrations/bang_olufsen/logo.png
  core_integrations/bang_olufsen/logo@2x.png
Labels: awaits-parent, has-parent

#4594 Add airtouch5 logos
  core_integrations/airtouch5/icon.png
  core_integrations/airtouch5/icon@2x.png
  core_integrations/airtouch5/logo.png
  core_integrations/airtouch5/logo@2x.png
Labels: parent-merged, has-parent

#5114 Add icon for coautilities virtual provider
  core_integrations/coautilities/icon.png
Labels: has-parent

#5084 Add Teslemetry
  core_brands/teslemetry/icon.png
  core_brands/teslemetry/icon@2x.png
Labels: parent-merged, has-parent

#4413 add romy images
  core_integrations/romy/icon.png
  core_integrations/romy/icon@2x.png
  core_integrations/romy/logo.png
  core_integrations/romy/logo@2x.png
Labels: awaits-parent, has-parent

#5062 Move elvia brand from custom to core
  core_integrations/elvia/dark_icon.png
  core_integrations/elvia/dark_icon@2x.png
  core_integrations/elvia/dark_logo.png
  core_integrations/elvia/dark_logo@2x.png
  core_integrations/elvia/icon.png
  core_integrations/elvia/icon@2x.png
  core_integrations/elvia/logo.png
  core_integrations/elvia/logo@2x.png
Labels: awaits-parent, has-parent

#5141 Symlink traccar as traccar_server
  core_integrations/traccar_server
Labels: has-parent
