Repository home-assistant/brands, pull requests merged in 2024-12, with the labels that each got.

#6146 Add logo/icon for Powerfox integration
  core_integrations/powerfox/icon.png
  core_integrations/powerfox/icon@2x.png
  core_integrations/powerfox/logo.png
  core_integrations/powerfox/logo@2x.png
Labels: awaits-parent, has-parent

#6168 Remove dte_energy_bridge brand
  core_integrations/dte_energy_bridge/icon.png
  core_integrations/dte_energy_bridge/icon@2x.png
  core_integrations/dte_energy_bridge/logo.png
  core_integrations/dte_energy_bridge/logo@2x.png
Labels: parent-merged

#6185 Remove Stookalert integration
  core_integrations/stookalert/icon.png
  core_integrations/stookalert/icon@2x.png
  core_integrations/stookalert/logo.png
  core_integrations/stookalert/logo@2x.png
Labels: awaits-parent, has-parent

#6010 Add Ituran icons and logo
  core_integrations/ituran/icon.png
  core_integrations/ituran/icon@2x.png
  core_integrations/ituran/logo.png
  core_integrations/ituran/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent

#6054 Add Watergate Logo
  core_integrations/watergate/dark_logo.png
  core_integrations/watergate/dark_logo@2x.png
  core_integrations/watergate/icon.png
  core_integrations/watergate/icon@2x.png
  core_integrations/watergate/logo.png
  core_integrations/watergate/logo@2x.png
Labels: awaits-parent, has-parent

#6037 Add cookidoo icons and logos
  core_integrations/cookidoo/icon.png
  core_integrations/cookidoo/icon@2x.png
  core_integrations/cookidoo/logo.png
  core_integrations/cookidoo/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent

#6209 Add Slide local logo
  core_brands/slide/icon.png
  core_brands/slide/icon@2x.png
  core_brands/slide/logo.png
  core_brands/slide/logo@2x.png
  core_integrations/slide
  core_integrations/slide_local
Labels: parent-merged, has-parent

#6218 Move ohme from custom to core integrations
  core_integrations/ohme/dark_icon.png
  core_integrations/ohme/dark_icon@2x.png
  core_integrations/ohme/dark_logo.png
  core_integrations/ohme/dark_logo@2x.png
  core_integrations/ohme/icon.png
  core_integrations/ohme/icon@2x.png
  core_integrations/ohme/logo.png
  core_integrations/ohme/logo@2x.png
Labels: has-parent

#6244 Add Peblar Rocksolid EV Chargers integration
  core_integrations/peblar/peblar/icon.png
  core_integrations/peblar/peblar/logo.png
  custom_integrations/peblar/icon.png
  custom_integrations/peblar/logo.png
Labels: has-parent

#6272 Add harvey branding
  core_integrations/harvey/icon.png
  core_integrations/harvey/icon@2x.png
Labels: parent-merged, has-parent

#6287 Add icons and logos for Overseerr
  core_integrations/overseerr/dark_logo.png
  core_integrations/overseerr/dark_logo@2x.png
  core_integrations/overseerr/icon.png
  core_integrations/overseerr/icon@2x.png
  core_integrations/overseerr/logo.png
  core_integrations/overseerr/logo@2x.png
Labels: awaits-parent, has-parent
