Repository home-assistant/brands, pull requests merged in 2024-05, with the labels that each got.

#5416 Add icons and logos for IMGW-PIB integration
  core_integrations/imgw_pib/dark_logo.png
  core_integrations/imgw_pib/dark_logo@2x.png
  core_integrations/imgw_pib/icon.png
  core_integrations/imgw_pib/icon@2x.png
  core_integrations/imgw_pib/logo.png
  core_integrations/imgw_pib/logo@2x.png
Labels: parent-merged

#5425 Add icon for Intelligent Storage Acceleration
  core_integrations/isal/icon.txt
Labels: parent-merged

#5440 Add airgradient
  core_integrations/airgradient/icon.png
  core_integrations/airgradient/icon@2x.png
  core_integrations/airgradient/logo.png
  core_integrations/airgradient/logo@2x.png
Labels: awaits-parent, has-parent

#4769 Add viam logo and icon
  core_integrations/viam/dark_logo.png
  core_integrations/viam/dark_logo@2x.png
  core_integrations/viam/icon.png
  core_integrations/viam/icon@2x.png
  core_integrations/viam/logo.png
  core_integrations/viam/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent

#5433 Add apsystems-local to core
  core_brands/apsystems/dark_logo.png
  core_brands/apsystems/dark_logo@2x.png
  core_brands/apsystems/icon.png
  core_brands/apsystems/icon@2x.png
  core_brands/apsystems/logo.png
  core_brands/apsystems/logo@2x.png
Labels: parent-merged
