Repository home-assistant/brands, pull requests merged in 2024-03, with the labels that each got.

#5210 Add images for fyta
  core_integrations/fyta/icon.png
  core_integrations/fyta/icon@2x.png
  core_integrations/fyta/logo.png
  core_integrations/fyta/logo@2x.png
Labels: has-parent

#5290 Sacramento Municipal Utility District (SMUD) icon
  core_integrations/smud/icon.png
Labels: parent-merged

#5326 Add ollama
  core_integrations/ollama/dark_icon.png
  core_integrations/ollama/dark_icon@2x.png
  core_integrations/ollama/dark_logo.png
  core_integrations/ollama/dark_logo@2x.png
  core_integrations/ollama/icon.png
  core_integrations/ollama/icon@2x.png
  core_integrations/ollama/logo.png
  core_integrations/ollama/logo@2x.png
Labels: parent-merged, has-parent

#5160 Add eq3btsmart to core integrations
  core_integrations/eq3btsmart
Labels: awaits-parent, has-parent

#5227 Add Energenie images for egps component.
  core_integrations/energenie_power_sockets/icon.png
  core_integrations/energenie_power_sockets/icon@2x.png
  core_integrations/energenie_power_sockets/logo.png
  core_integrations/energenie_power_sockets/logo@2x.png
Labels: awaits-parent, has-parent
