Repository home-assistant/brands, pull requests merged in 2024-06, with the labels that each got.

#3104 added icons for new azure data explorer component
  core_integrations/azure_data_explorer/icon.png
  core_integrations/azure_data_explorer/icon@2x.png
Labels: cla-signed, awaits-parent, has-parent

#5510 Add icons and logos for ista_ecotrend integration
  core_integrations/ista_ecotrend/dark_icon.png
  core_integrations/ista_ecotrend/dark_logo.png
  core_integrations/ista_ecotrend/icon.png
  core_integrations/ista_ecotrend/icon@2x.png
  core_integrations/ista_ecotrend/logo.png
  core_integrations/ista_ecotrend/logo@2x.png
Labels: parent-merged, awaits-parent, has-parent

#5445 Add Aquacell branding
  core_integrations/aquacell/icon.png
  core_integrations/aquacell/icon@2x.png
  core_integrations/aquacell/logo.png
  core_integrations/aquacell/logo@2x.png
Labels: awaits-parent, has-parent

#5581 Add Mealie logo
  core_integrations/mealie/icon.png
Labels: awaits-parent, has-parent

#5595 Add Ambient Weather brand
  core_brands/ambient_weather/icon.png
  core_brands/ambient_weather/icon@2x.png
  core_brands/ambient_weather/logo.png
  core_brands/ambient_weather/logo@2x.png
  core_integrations/ambient_network/icon.png
  core_integrations/ambient_network/icon@2x.png
  core_integrations/ambient_station/icon.png
  core_integrations/ambient_station/icon@2x.png
Labels: parent-merged, has-parent

#5605 Update Huisbaasje to EnergyFlip
  core_integrations/huisbaasje/logo.png
  core_integrations/huisbaasje/logo@2x.png
Labels: parent-merged, has-parent

#5578 Add Knocki logos
  core_integrations/knocki/dark_logo.png
  core_integrations/knocki/icon.png
  core_integrations/knocki/logo.png
Labels: parent-merged, awaits-parent, has-parent
