Repository home-assistant/brands, pull requests merged in 2024-09, with the labels that each got.

#5620 Add iskra integration icons
  core_integrations/iskra/icon.png
  core_integrations/iskra/icon@2x.png
  core_integrations/iskra/logo.png
  core_integrations/iskra/logo@2x.png
Labels: awaits-parent, has-parent

#5548 Sensoterra icons and logos
  core_integrations/sensoterra/dark_logo.png
  core_integrations/sensoterra/dark_logo@2x.png
  core_integrations/sensoterra/icon.png
  core_integrations/sensoterra/icon@2x.png
  core_integrations/sensoterra/logo.png
  core_integrations/sensoterra/logo@2x.png
Labels: awaits-parent, has-parent

#5725 Add Weheat brand images
  core_integrations/weheat/dark_icon.png
  core_integrations/weheat/dark_icon@2x.png
  core_integrations/weheat/dark_logo.png
  core_integrations/weheat/dark_logo@2x.png
  core_integrations/weheat/icon.png
  core_integrations/weheat/icon@2x.png
  core_integrations/weheat/logo.png
  core_integrations/weheat/logo@2x.png
Labels: awaits-parent, has-parent

#5845 Add Cambridge Audio integration
  core_integrations/cambridge_audio/dark_icon.png
  core_integrations/cambridge_audio/dark_icon@2x.png
  core_integrations/cambridge_audio/dark_logo.png
  core_integrations/cambridge_audio/dark_logo@2x.png
  core_integrations/cambridge_audio/icon.png
  core_integrations/cambridge_audio/icon@2x.png
  core_integrations/cambridge_audio/logo.png
  core_integrations/cambridge_audio/logo@2x.png
Labels: parent-merged, has-parent

#5839 Add Duke Energy brand images
  core_integrations/duke_energy/icon.png
  core_integrations/duke_energy/icon@2x.png
  core_integrations/duke_energy/logo.png
  core_integrations/duke_energy/logo@2x.png
Labels: awaits-parent, has-parent

#5638 Adding triggercmd icons and logo
  core_integrations/triggercmd/icon.png
  core_integrations/triggercmd/icon@2x.png
  core_integrations/triggercmd/logo.png
  core_integrations/triggercmd/logo@2x.png
Labels: awaits-parent, has-parent

#5864 Added brand assets for Arizona Public Service for opower virtual integration
  core_integrations/aps/icon.png
  core_integrations/aps/icon@2x.png
  core_integrations/aps/logo.png
  core_integrations/aps/logo@2x.png
Labels: parent-merged, has-parent

#5792 Branding for new WMS WebControl pro integration
  core_integrations/wmspro/icon.png
  core_integrations/wmspro/icon@2x.png
  core_integrations/wmspro/logo.png
  core_integrations/wmspro/logo@2x.png
Labels: parent-merged, awaits-parent, has-parent

#5897 Add NYT Games brands
  core_integrations/nyt_games/icon.png
  core_integrations/nyt_games/icon@2x.png
  core_integrations/nyt_games/logo.png
  core_integrations/nyt_games/logo@2x.png
Labels: awaits-parent, has-parent

#5903 Add Aqara
  core_brands/aqara/dark_icon.png
  core_brands/aqara/dark_icon@2x.png
  core_brands/aqara/dark_logo.png
  core_brands/aqara/dark_logo@2x.png
  core_brands/aqara/icon.png
  core_brands/aqara/icon@2x.png
  core_brands/aqara/logo.png
  core_brands/aqara/logo@2x.png
Labels: parent-merged
