Repository home-assistant/brands, pull requests merged in 2024-07, with the labels that each got.

#5625 Add MINI logo and icon
  core_integrations/mini_connected/dark_icon.png
  core_integrations/mini_connected/dark_icon@2x.png
  core_integrations/mini_connected/dark_logo.png
  core_integrations/mini_connected/dark_logo@2x.png
  core_integrations/mini_connected/icon.png
  core_integrations/mini_connected/icon@2x.png
  core_integrations/mini_connected/logo.png
  core_integrations/mini_connected/logo@2x.png
Labels: parent-merged, awaits-parent, has-parent

#5405 Add dio chacon brand
  core_integrations/chacon_dio/icon.png
  core_integrations/chacon_dio/icon@2x.png
  core_integrations/chacon_dio/logo.png
Labels: parent-merged, awaits-parent, has-parent

#5612 add madvr icons
  core_integrations/madvr/icon.png
  core_integrations/madvr/icon@2x.png
  core_integrations/madvr/logo.png
  core_integrations/madvr/logo@2x.png
Labels: awaits-parent, has-parent

#5122 Adding SimpleFIN Icons
  core_integrations/simplefin/icon.png
  core_integrations/simplefin/icon@2x.png
Labels: awaits-parent, has-parent

#5656 Add logo/icon for Autarco integration
  core_integrations/autarco/dark_logo.png
  core_integrations/autarco/dark_logo@2x.png
  core_integrations/autarco/icon.png
  core_integrations/autarco/icon@2x.png
  core_integrations/autarco/logo.png
  core_integrations/autarco/logo@2x.png
Labels: parent-merged, has-parent

#5657 Add israel rail integration icons
  core_integrations/israel_rail/icon.png
  core_integrations/israel_rail/icon@2x.png
  core_integrations/israel_rail/logo.png
  core_integrations/israel_rail/logo@2x.png
Labels: awaits-parent

#5652 Use Tesla brand for tesla_fleet
  core_integrations/tesla_fleet
Labels: parent-merged, awaits-parent, has-parent

#4966 Added icons for iotty Core Integration
  core_integrations/iotty/dark_icon.png
  core_integrations/iotty/dark_icon@2x.png
  core_integrations/iotty/dark_logo.png
  core_integrations/iotty/dark_logo@2x.png
  core_integrations/iotty/icon.png
  core_integrations/iotty/icon@2x.png
  core_integrations/iotty/logo.png
  core_integrations/iotty/logo@2x.png
Labels: awaits-parent, has-parent

#5315 Add LinkPlay as core integration
  core_integrations/linkplay/icon.png
  core_integrations/linkplay/icon@2x.png
  core_integrations/linkplay/logo.png
  core_integrations/linkplay/logo@2x.png
Labels: awaits-parent, has-parent

#5623 PINE64 Logos for Pinecil integration
  core_integrations/pinecil/dark_logo.png
  core_integrations/pinecil/dark_logo@2x.png
  core_integrations/pinecil/icon.png
  core_integrations/pinecil/icon@2x.png
  core_integrations/pinecil/logo.png
  core_integrations/pinecil/logo@2x.png
Labels: awaits-parent, has-parent

#5714 Add Bryant logo
  core_integrations/bryant_evolution/icon.png
  core_integrations/bryant_evolution/logo.png
Labels: has-parent

#5712 Logos for Pinecil virtual integration
  core_integrations/pinecil/dark_logo.png
  core_integrations/pinecil/dark_logo@2x.png
  core_integrations/pinecil/icon.png
  core_integrations/pinecil/icon@2x.png
  core_integrations/pinecil/logo.png
  core_integrations/pinecil/logo@2x.png
Labels: awaits-parent
