Repository home-assistant/brands, pull requests merged in 2024-11, with the labels that each got.

#6039 Add IRSAP Now Integration
  custom_integrations/irsap_ha/dark_icon.png
  custom_integrations/irsap_ha/dark_icon@2x.png
  custom_integrations/irsap_ha/dark_logo.png
  custom_integrations/irsap_ha/dark_logo@2x.png
  custom_integrations/irsap_ha/icon.png
  custom_integrations/irsap_ha/icon@2x.png
  custom_integrations/irsap_ha/logo.png
  custom_integrations/irsap_ha/logo@2x.png
Labels: Hacktoberfest

#6046 Add vimar_byme_plus icons and logos
  custom_integrations/vimar_byme_plus/icon.png
  custom_integrations/vimar_byme_plus/icon@2x.png
  custom_integrations/vimar_byme_plus/logo.png
  custom_integrations/vimar_byme_plus/logo@2x.png
Labels: Hacktoberfest

#6045 add icons for wire_pilot_climate
  custom_integrations/pilot_wire_climate/icon.png
  custom_integrations/pilot_wire_climate/icon@2x.png
Labels: Hacktoberfest

#6031 Bezeq Energy Custom Component Logo
  custom_integrations/bezeq_energy/icon.png
  custom_integrations/bezeq_energy/icon@2x.png
Labels: Hacktoberfest

#6040 Add Herospeed XVR custom component icon
  custom_integrations/herospeed_xvr/icon.png
Labels: Hacktoberfest

#6027 Add Tartu NLP TTS brand
  custom_integrations/tartunlp_tts/icon.png
Labels: Hacktoberfest

#6026 Add icon file for HA integration APsystems ECU proxy
  custom_integrations/apsystems_ecu_proxy/icon.png
Labels: Hacktoberfest

#6029 Add Creality logos.
  custom_integrations/creality_box_control/dark_icon.png
  custom_integrations/creality_box_control/dark_icon@2x.png
  custom_integrations/creality_box_control/dark_logo.png
  custom_integrations/creality_box_control/dark_logo@2x.png
  custom_integrations/creality_box_control/icon.png
  custom_integrations/creality_box_control/icon@2x.png
  custom_integrations/creality_box_control/logo.png
  custom_integrations/creality_box_control/logo@2x.png
Labels: Hacktoberfest

#6025 Add INSNRG logo files for new brand
  custom_integrations/insnrg_chlorinator/icon.png
  custom_integrations/insnrg_chlorinator/icon@2x.png
  custom_integrations/insnrg_chlorinator/logo.png
  custom_integrations/insnrg_chlorinator/logo@2x.png
Labels: Hacktoberfest

#6038 Add icon and logo for defa_power custom integration
  custom_integrations/defa_power/icon.png
  custom_integrations/defa_power/icon@2x.png
  custom_integrations/defa_power/logo.png
  custom_integrations/defa_power/logo@2x.png
Labels: Hacktoberfest

#6035 Add icons for iAlarm_mk2 custom integration
  custom_integrations/ialarm_mk2/icon.png
  custom_integrations/ialarm_mk2/icon@2x.png
Labels: Hacktoberfest

#4592 Add icon and logo for nasweb integration
  core_integrations/nasweb/icon.png
  core_integrations/nasweb/logo.png
Labels: parent-merged, awaits-parent, has-parent

#6023 Add sky_remote symlink
  core_brands/sky/icon.png
  core_brands/sky/icon@2x.png
  core_brands/sky/logo.png
  core_brands/sky/logo@2x.png
  core_integrations/sky_hub
  core_integrations/sky_remote
Labels: awaits-parent, Hacktoberfest, has-parent

#6075 Move acaia logos from custom to core
  core_integrations/acaia/dark_logo.png
  core_integrations/acaia/icon.png
  core_integrations/acaia/icon@2x.png
  core_integrations/acaia/logo.png
Labels: awaits-parent, has-parent
