Repository home-assistant/brands, pull requests merged in 2024-04, with the labels that each got.

#5285 Added icons for Arve integration
  core_integrations/arve/icon.png
  core_integrations/arve/icon@2x.png
  core_integrations/arve/logo.png
  core_integrations/arve/logo@2x.png
Labels: awaits-parent, has-parent

#5358 Remove epson workforce integration
  core_integrations/epson
  core_integrations/epson/icon.png
  core_integrations/epson/icon@2x.png
  core_integrations/epson/logo.png
  core_integrations/epson/logo@2x.png
  core_integrations/epsonworkforce
Labels: parent-merged

#3820 Add Epic Games (Store) brand
  core_integrations/epic_games_store/dark_icon.png
  core_integrations/epic_games_store/dark_icon@2x.png
  core_integrations/epic_games_store/dark_logo.png
  core_integrations/epic_games_store/dark_logo@2x.png
  core_integrations/epic_games_store/icon.png
  core_integrations/epic_games_store/icon@2x.png
  core_integrations/epic_games_store/logo.png
  core_integrations/epic_games_store/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent, hacktoberfest-accepted

#5044 Add images for Sanix integration
  core_integrations/sanix/icon.png
  core_integrations/sanix/icon@2x.png
  core_integrations/sanix/logo.png
  core_integrations/sanix/logo@2x.png
Labels: parent-merged, has-parent

#4990 Adding brand icons and logos for new ambient weather network integration
  core_integrations/ambient_network/icon.png
  core_integrations/ambient_network/icon@2x.png
  core_integrations/ambient_network/logo.png
  core_integrations/ambient_network/logo@2x.png
Labels: awaits-parent, has-parent
