Repository home-assistant/brands, pull requests merged in 2025-05, with the labels that each got.

#7030 Rename S3 to AWS_S3
  core_integrations/aws_s3/icon.png
  core_integrations/aws_s3/icon@2x.png
Labels: awaits-parent, has-parent

#7072 Briiv brands logo
  core_integrations/briiv/icon.png
  core_integrations/briiv/logo.png
Labels: has-parent

#6932 Add logo for Probe Plus
  core_integrations/probe_plus/logo.png
Labels: awaits-parent, has-parent

#7095 add paperless icon and logos
  core_integrations/paperless_ngx/dark_logo.png
  core_integrations/paperless_ngx/dark_logo@2x.png
  core_integrations/paperless_ngx/icon.png
  core_integrations/paperless_ngx/icon@2x.png
  core_integrations/paperless_ngx/logo.png
  core_integrations/paperless_ngx/logo@2x.png
Labels: awaits-parent, has-parent

#7130 Amazon Devices logo and icon
  core_integrations/amazon_devices/icon.png
  core_integrations/amazon_devices/icon@2x.png
  core_integrations/amazon_devices/logo.png
Labels: parent-merged, has-parent

#6904 Add icon and logo for smarla integration
  core_integrations/smarla/icon.png
  core_integrations/smarla/icon@2x.png
  core_integrations/smarla/logo.png
  core_integrations/smarla/logo@2x.png
Labels: awaits-parent, has-parent
