Repository home-assistant/brands, pull requests merged in 2025-01, with the labels that each got.

#6105 Add logo & icon for igloohome integration
  core_integrations/igloohome/icon.png
  core_integrations/igloohome/icon@2x.png
  core_integrations/igloohome/logo.png
  core_integrations/igloohome/logo@2x.png
Labels: awaits-parent, has-parent

#6295 Add logo for Model Context Protocol server integration
  core_integrations/mcp_server/icon.png
  core_integrations/mcp_server/icon@2x.png
  core_integrations/mcp_server/logo.png
  core_integrations/mcp_server/logo@2x.png
Labels: has-parent

#6319 Move Homee to core_integrations
  core_integrations/homee/icon.png
  core_integrations/homee/icon@2x.png
  core_integrations/homee/logo.png
  core_integrations/homee/logo@2x.png
Labels: parent-merged

#6335 Add branding for letpot
  core_integrations/letpot/dark_logo.png
  core_integrations/letpot/dark_logo@2x.png
  core_integrations/letpot/icon.png
  core_integrations/letpot/icon@2x.png
  core_integrations/letpot/logo.png
  core_integrations/letpot/logo@2x.png
Labels: has-parent

#5931 Add images for qbus integration
  core_integrations/qbus/icon.png
  core_integrations/qbus/icon@2x.png
  core_integrations/qbus/logo.png
  core_integrations/qbus/logo@2x.png
Labels: awaits-parent, Hacktoberfest, has-parent

#6340 Add Model Context Protocol brand
  core_integrations/mcp
Labels: awaits-parent, has-parent

#6334 Add icons for onedrive
  onedrive/icon.png
  onedrive/icon@2x.png
Labels: awaits-parent, has-parent
