Repository home-assistant/brands, pull requests merged in 2025-02, with the labels that each got.

#6348 Add iometer brand
  core_integrations/iometer/dark_logo.png
  core_integrations/iometer/dark_logo@2x.png
  core_integrations/iometer/icon.png
  core_integrations/iometer/icon@2x.png
  core_integrations/iometer/logo.png
  core_integrations/iometer/logo@2x.png
Labels: has-parent

#6487 Add Linx virtual motionblinds integration brand images
  core_integrations/linx/icon.png
  core_integrations/linx/icon@2x.png
  core_integrations/linx/logo.png
  core_integrations/linx/logo@2x.png
Labels: parent-merged, has-parent

#6485 Add Ublockout virtual integration of motionblinds
  core_integrations/ublockout/icon.png
  core_integrations/ublockout/logo.png
Labels: parent-merged, has-parent

#5179 Add pglab logo and icons
  core_integrations/pglab/dark_icon.png
  core_integrations/pglab/dark_icon@2x.png
  core_integrations/pglab/dark_logo.png
  core_integrations/pglab/dark_logo@2x.png
  core_integrations/pglab/icon.png
  core_integrations/pglab/icon@2x.png
  core_integrations/pglab/logo.png
  core_integrations/pglab/logo@2x.png
Labels: awaits-parent, has-parent

#6539 Add branding for EnergyID integration
  core_integrations/energyid/icon.png
  core_integrations/energyid/icon@2x.png
  core_integrations/energyid/logo.png
  core_integrations/energyid/logo@2x.png
Labels: has-parent

#6581 Add Linak
  core_integrations/linak/icon.png
  core_integrations/linak/icon@2x.png
  core_integrations/linak/logo.png
  core_integrations/linak/logo@2x.png
Labels: awaits-parent, has-parent

#6299 Add SensorPush Cloud integration
  core_brands/sensorpush/icon.png
  core_brands/sensorpush/icon@2x.png
  core_integrations/sensorpush
  core_integrations/sensorpush_cloud
Labels: has-parent

#6304 Move Snoo to core for new integration
  core_integrations/snoo/icon.png
  core_integrations/snoo/icon@2x.png
  core_integrations/snoo/logo.png
  core_integrations/snoo/logo@2x.png
Labels: awaits-parent, has-parent

#6521 Add icon for WebDAV
  core_integrations/webdav/icon.txt
Labels: awaits-parent, has-parent

#6292 Add branding for azure_storage
  core_integrations/azure_storage/icon.png
  core_integrations/azure_storage/icon@2x.png
Labels: awaits-parent, has-parent
